### PR TITLE
Use bfb math functions in TMS F90 code

### PR DESCRIPTION
**Pull request by tcclevenger**
BFB fail found in https://github.com/E3SM-Project/scream/pull/2500 (unrelated to that PR). I didn't use the bfb functions and wasn't caught until now. ~~This PR will not be BFB to previous eam code.~~

### CODE REVIEW

**Review by bartgol — APPROVED** [review]
This should be bfb when building SCREAMv0 cases, since `SCREAM_CONFIG_IS_CMAKE` should not be defined, and all the bfb_XYZ calls will resolve to XYZ itself.

**Comment by bartgol** [comment]
I'm puzzled by the diffs. I thought the F90 code was only run during the BFB unit tests. Also, we do not have a v1 test that enables tms anyways, so this is not clear to me.

**Comment by tcclevenger** [comment]
@bartgol Oh yes, I forget that needs to be done. I can bless on mappy if you haven't already

**Comment by bartgol** [comment]
I just fired off the bless job

**Pull request merged**
