### PR TITLE
Use -O1 on SCREAM_MACHINE cori-knl for some SHOC files.

### LINKED ISSUE #1543: Internal error with default Intel compiler (version 19.1.2.254) on Cori using OPT build
Using a scream master of Apr12th, can reproduce with `SMS_Ld1_P16x1.ne4_ne4.F2000SCREAMv1.cori-knl_intel` (ie OPT build) after commenting out abort as noted here https://github.com/E3SM-Project/scream/issues/1539. The test will buidl with DEBUG.

```
[ 95%] Linking CXX executable p3_tables_setup
cd /global/cscratch1/sd/ndk/e3sm_scratch/cori-knl/bio-apr11/f30cpu.F2000SCREAMv1.ne30_ne30.bio-apr11.intel.12s.n011b64x1.nospa.RECe.N576.ts150.s8.opt1/bld/cmake-bld/scream/src/physics/p3 && /global/common/software/nersc/cori-2022q1/spack/cray-cnl7-haswell/cmake-3.22.1-zdiyyvt/bin/cmake -E cmake_link_script CMakeFiles/p3_tables_setup.dir/link.txt --verbose=1
python3 /global/cscratch1/sd/ndk/e3sm_scratch/cori-knl/bio-apr11/f30cpu.F2000SCREAMv1.ne30_ne30.bio-apr11.intel.12s.n011b64x1.nospa.RECe.N576.ts150.s8.opt1/Tools/e3sm_compile_wrap.py  /opt/cray/pe/craype/2.6.2/bin/CC  -traceback -DRRTMGP_EXPENSIVE_CHECKS -restrict -Wall -diag-disable=remark -O3 -DNDEBUG -O3 -qopenmp-simd -Wl,-rpath,/opt/cray/pe/atp/3.14.9/lib -Wl,--undefined=__libAtpSigHandler_ctor -L/opt/cray/dmapp/7.1.1-7.0.3.1_3.7__g93a7e9f.ari/lib64 -DKOKKOS_DEPENDENCE -fopenmp -xMIC-AVX512 CMakeFiles/p3_tables_setup.dir/p3_tables_setup.cpp.o -o p3_tables_setup  libp3.a ../share/libphysics_share.a ../../share/libscream_share.a ../../../../externals/ekat/src/ekat/libekat.a ../../../../externals/kokkos/containers/src/libkokkoscontainers.a ../../../../externals/kokkos/core/src/libkokkoscore.a ../../../../externals/yaml-cpp/libyaml-cpp.a ../../../../externals/spdlog/libspdlog.a /opt/cray/pe/libsci/20.09.1/INTEL/16.0/x86_64/lib/libsci_intel_mpi_mp.a /opt/cray/pe/libsci/20.09.1/INTEL/16.0/x86_64/lib/libsci_intel_mp.a /opt/intel/compilers_and_libraries_2019.3.199/linux/compiler/lib/intel64/libiomp5.a /opt/intel/compilers_and_libraries_2019.3.199/linux/compiler/lib/intel64/libifcoremt.a /opt/intel/compilers_and_libraries_2019.3.199/linux/compiler/lib/intel64/libiomp5.a /opt/intel/compilers_and_libraries_2019.3.199/linux/compiler/lib/intel64/libifcoremt.a -lhdf5hl_fortran_parallel -lhdf5_fortran_parallel -lnetcdff -lmpichf90_intel -lifcore 
": internal error: 010101_13941
```

Originally noted here, https://github.com/E3SM-Project/scream/issues/1540, but I now see this is a diff issue and fails to build this file: `components/scream/src/physics/shoc/shoc_assumed_pdf.cpp`

I tried several compiler flag changes, and other module changes (including different Intel compiler version), but was unable to get beyond the error. 

However, I had been able to successfully build Intel optimized with a clone from a few weeks ago.

What about first bisecting to find which PR might have introduced a change?
And then if that's not successful, I have several modifications in the clone that does allow Intel optimized build that I can look at one-by-one (already tried the obvious changes, such as compiler flags) ?

### PR DESCRIPTION
**Pull request by ambrad**
This fix resolves an internal compiler error.

Fixes #1543.

[BFB]

### CODE REVIEW

**Comment by ambrad** [comment]
@ndkeen would you like to test this? @bartgol I added you as a reviewer to be sure this is where you want such cmake code to go. Thanks.

**Review by ndkeen — COMMENTED** [review]
I have not seen an issue with the other source, only shoc_assumed.  Also, would we only want to do this for non-DEBUG builds?

**Review by bartgol — APPROVED** [review]
Drastic ICEs call for drastic measures.

**Comment by ambrad** [comment]
@ndkeen I see the issue with shoc_calc_shoc_varorcovar.cpp, too. Didn't someone else report that? Note that the build will fail on shoc_assumed_pdf.cpp before it reaches the second file if GMAKE_J is small.

Good point about debug builds. I'll put in an additional condition for that.

**Review by bartgol — APPROVED** [review]

**Comment by PeterCaldwell** [comment]
dumb question, but would this approach also work for #1557, where we know that opt builds on Perlmutter give corrupted answers unless kokkos debug flag is used to build? In other words, do we know if kokkos debug is only needed in a single location in the code?

**Comment by ambrad** [comment]
@PeterCaldwell the issue there -- I haven't looked into it, but this this is what I understand from others -- is that right now the workaround is to apply a flag globally to all files, so it's not known yet what individual files are the cause of the PM runtime problems. In contrast, this Cori-KNL issue was the much simpler one of two translation units (out of a gazillion) leading to ICEs, solved by decreasing the opt level for just those two cpp files.

**Comment by ndkeen** [comment]
I added this to my local repo and tried 
```
SMS_Ld1_P96x1.ne4_ne4.F2010-SCREAMv1.cori-knl_intel
SMS_D_Ld1_P96x1.ne4_ne4.F2010-SCREAMv1.cori-knl_intel
```

Both worked and seemed to have the right flags for `shoc_assumed_pdf.cpp`

**Comment by ambrad** [comment]
@ndkeen great. Do you intend to do further testing, or are you fine with the PR? If the latter, would you hit "Approve"?

**Comment by ndkeen** [comment]
Well I tried to hit approve, but I no longer see a place where I am given that option again

**Comment by ambrad** [comment]
@ndkeen I think you have to hit the "Files changed" tab to get that button.

**Review by ndkeen — APPROVED** [review]

**Pull request merged**
