### PR TITLE
Explicitly source the sems modules init script on mappy

### PR DESCRIPTION
**Pull request by bartgol**
Without it, and if you don't already have it in your bashrc, test-all-scream failes when trying to setup the env.

### CODE REVIEW

**Comment by jgfouca** [comment]
What was the context where this failed? The SEMS module setup is in the system init scripts.

**Comment by jgfouca** [comment]
Previously, we had this module setup stuff in `scripts/jenkins/mappy_setup` but I removed it (because we aren't using the legacy modules anymore).

**Comment by bartgol** [comment]
> What was the context where this failed? The SEMS module setup is in the system init scripts.

It was failing when running a container image on mappy, while mounting the sems tpl folders for using them inside the container.

**Comment by jgfouca** [comment]
Did this work before the rebuild?

**Pull request merged**
