### PR TITLE
Write P3 microphysics tendencies to output file

### PR DESCRIPTION
**Pull request by AaronDonahue**
This commit will include the microphysical tendencies as output
in the default output file when using the P3 microphysics
parameterization.

This will provide a tool for understanding what physics are impacting
the solution and should assist in understanding the solutions and
debugging.

### CODE REVIEW

**Comment by AaronDonahue** [comment]
@jgfouca , I think this latest push should fix the Travis CI issue.

**Comment by jgfouca** [comment]
> I think this latest push should fix the Travis CI issue.

Yep. Looks good.

**Comment by AaronDonahue** [comment]
As per the telecon today, I commented out the extra "outfld" calls and ran the baseline comparison based on a baseline created from the master branch and I get one fail:

```test 18
      Start 18: p3_regression

18: Test command: /p/lustre2/donahue5/E3SM_simulations/SCREAM/Baseline_Tests/BuildTest/src/physics/p3/tests/p3_run_and_cmp "/p/lustre2/donahue5/E3SM_simulations/SCREAM/Baseline_Tests/BuildTest/data/p3_run_and_cmp.baseline"
18: Test timeout computed to be: 82800
18: terminate called after throwing an instance of 'std::logic_error'
18:   what():  /g/g17/donahue5/Code/e3sm/scream/scream/components/scream/src/share/util/file_utils.hpp:25: FAIL:
18: nread == sz
18: read: nread = 0 sz = 1
18: sizeof(Real) 8 avx -AVX packsize 16 compiler Intel FPE on #threads 32
18: Comparing with /p/lustre2/donahue5/E3SM_simulations/SCREAM/Baseline_Tests/BuildTest/data/p3_run_and_cmp.baseline8 at tol 0.0e+00
18: 
18: p3_run_and_cmp:181335 terminated with signal 6 at PC=2aaaad017207 SP=7fffffffbf98.  Backtrace:
18: /lib64/libc.so.6(gsignal+0x37)[0x2aaaad017207]
18: /lib64/libc.so.6(abort+0x148)[0x2aaaad0188f8]
18: /usr/tce/packages/gcc/default/lib64/libstdc++.so.6(_ZN9__gnu_cxx27__verbose_terminate_handlerEv+0x15d)[0x2aaaac464ffd]
18: /usr/tce/packages/gcc/default/lib64/libstdc++.so.6(+0x5e086)[0x2aaaac463086]
18: /usr/tce/packages/gcc/default/lib64/libstdc++.so.6(+0x5e0d1)[0x2aaaac4630d1]
18: /usr/tce/packages/gcc/default/lib64/libstdc++.so.6(+0x5e2e8)[0x2aaaac4632e8]
18: /p/lustre2/donahue5/E3SM_simulations/SCREAM/Baseline_Tests/BuildTest/src/physics/p3/tests/p3_run_and_cmp[0x41f5b9]
18: /p/lustre2/donahue5/E3SM_simulations/SCREAM/Baseline_Tests/BuildTest/src/physics/p3/tests/p3_run_and_cmp(main+0x3a7)[0x4196b7]
18: /lib64/libc.so.6(__libc_start_main+0xf5)[0x2aaaad0033d5]
18: /p/lustre2/donahue5/E3SM_simulations/SCREAM/Baseline_Tests/BuildTest/src/physics/p3/tests/p3_run_and_cmp[0x41923f]
18: ERROR : Process exiting while Kokkos::Threads is still initialized
18/57 Test #18: p3_regression ....................***Failed    0.16 sec```

Not sure what the problem is.  @jgfouca , @ambrad  do you have any thoughts?

**Comment by AaronDonahue** [comment]
I should note that there is an error with building the E3SM version of the code that I will fix with a different PR going in soon.

**Comment by ambrad** [comment]
@AaronDonahue, thanks. Let me spend a few minutes running this PR on my computer to investigate the output you posted. I'll get back to you with some analysis.

**Comment by ambrad** [comment]
OK, this is a great example of how to test BFBness up to a small modification.

First I checked out master, built it, and ran `make baseline`.

Then I checked out this branch, built it, and confirmed that `ctest -R
p3_regression -V` (`-V` for extra output) failed.

Finally, I edited p3_f90.cpp:99 to comment out the new field:
```  fdipb(rcldm); fdipb(lcldm); fdipb(icldm); //fdipb(p3_tend_out);```
I rebuilt and confirmed that `ctest -R p3_regression -V` passes. So the failure
is due purely to the new field; everything else remains BFB. Both of these are
as expected. We can now be confident this PR passes the way it should, and
rebaselining in master will produce a good baseline file.

**Comment by AaronDonahue** [comment]
Excellent, thank you to the reviewers.  I'll merge now.

**Pull request merged**
