### PR TITLE
fix build error caused by cxx_* function, replace it with bfb_*

### PR DESCRIPTION
**Pull request by xyuan**
fix build error caused by cxx_* function, replace it with bfb_* function.

BUG

### CODE REVIEW

**Comment by xyuan** [comment]
> Based on this fix... Are lines 19-22 even needed? Given that these are now never used and are defined in bfb_math.inc anyway?

we still need to include this module because it is used when cxx builds

**Comment by AaronDonahue** [comment]
> > Based on this fix... Are lines 19-22 even needed? Given that these are now never used and are defined in bfb_math.inc anyway?
> 
> we still need to include this module because it is used when cxx builds

But looking through the shoc.F90 code I don't see any use of cxx_* anywhere.  I'm guessing that at the shoc.F90 layer only `bfb_*` is used, based on the definition inside `bfb_math.inc`.  Within `bfb_math.inc` the `cxx_*` syntax is used when needed.

Based on that my theory is that we don't need to load the module in shoc.F90 since we are already getting what we need in `bdb_math.inc`.  But I could be wrong.  @jgfouca may know better than me.

**Comment by AaronDonahue** [comment]
I checked this branch for the test: `SMS.ne4_ne4.F2000-SCREAM-LR.cori-knl_intel` and it passed.  This is a good indication it will pass for the other failed tests on Cori.

**Comment by jgfouca** [comment]
Let's fix this as part of #504

**Pull request closed without merging**
