### PR TITLE
Pm-cpu: do static libc++ linking

### PR DESCRIPTION
**Pull request by jgfouca**
There are several libraries we use that were built with gcc-11:

```
    <environment_variables compiler="gnu" mpilib="mpich">
      <env name="ADIOS2_ROOT">$SHELL{if [ -z "$ADIOS2_ROOT" ]; then echo /global/cfs/cdirs/e3sm/3rdparty/adios2/2.9.1/cray-mpich-8.1.25/gcc-11.2.0; else echo "$ADIOS2_ROOT"; fi}</env>
      <env name="BLA_VENDOR">Generic</env>
      <env name="Albany_ROOT">$SHELL{if [ -z "$Albany_ROOT" ]; then echo /global/common/software/e3sm/albany/2024.03.26/gcc/11.2.0; else echo "$Albany_ROOT"; fi}</env>
      <env name="Trilinos_ROOT">$SHELL{if [ -z "$Trilinos_ROOT" ]; then echo /global/common/software/e3sm/trilinos/15.1.1/gcc/11.2.0; else echo "$Trilinos_ROOT"; fi}</env>
    </environment_variables>
```

This PR fixes the error:
```
 92: /pscratch/sd/a/acmetest/e3sm_scratch/pm-cpu/ERS_Ln22.ne30_ne30.F2010-SCREAMv1.pm-cpu_gnu.scream-internal_diagnostics_level--scream-output-preset-3.20240826_132116_eilkpw/bld/e3sm.exe: /opt/cray/pe/gcc-libs/libstdc++.so\
.6: version `GLIBCXX_3.4.30' not found (required by /pscratch/sd/a/acmetest/e3sm_scratch/pm-cpu/ERS_Ln22.ne30_ne30.F2010-SCREAMv1.pm-cpu_gnu.scream-internal_diagnostics_level--scream-output-preset-3.20240826_132116_eilkpw/b\
ld/e3sm.exe)
```

... which started happening after the upstream merge, which changed the pm-cpu compiler to 12.2

### CODE REVIEW

**Comment by ndkeen** [comment]
No we moved to gcc 12 now.
If the adios libs need to rebuilt, we can do that.
We can also comment out that section for now as things will still work without adios

**Comment by jgfouca** [comment]
@bartgol , I was wondering that too. I guessed that they aren't linking adios2.

**Comment by jgfouca** [comment]
OK, according to `ldd` the only library that scream is loading that e3sm is not is:
```
	libyaml-cpp.so.0.6 => /usr/lib64/libyaml-cpp.so.0.6
```

**Comment by jgfouca** [comment]
Some updates. I did a comparison of `ldd` between an e3sm.exe from a non-eamxx case that worked and an eamxx case that did not work. They were basically identical with the exception of yaml-cpp, which the eamxx case linked against a system install one. I thought maybe this was the problem, so I built a new yaml-cpp with gcc-12 and made sure to use that one instead. I was surprised to see that did not fix the issue. With no more leads, I decided to statically link libstdc++ and that did fix the problem.

**Comment by bartgol** [comment]
> EKAT was bringing it in, as expected. Changing it to a freshly built yaml-cpp did not fix the issue.

Are you saying that EKAT_SKIP_FIND_YAML_CPP still caused ekat to find yaml instead of locally building it? Or it built locally, but then still linked the system one?

**Comment by jgfouca** [comment]
I built my own yaml-cpp with gcc-12 and then set YAML_CPP_ROOT. It linked mine and I no longer saw the system yaml-cpp in the ldd output.

**Comment by bartgol** [comment]
Oh. So the system yamlcpp was _not_ the responsible one, since you still got the GLIBXX error with your custom yaml. Interesting.

**Comment by jgfouca** [comment]
Hey, @ndkeen , @bartgol , can I merge this?

**Comment by ndkeen** [comment]
I thought we were trying to go away from static linking? Do we know why this is needed in scream, but not e3sm? Was it because adios used differently?

**Comment by jgfouca** [comment]
> I thought we were trying to go away from static linking?

This is news to me. We use .a libraries all over our build system.

> Do we know why this is needed in scream, but not e3sm?

No, it's a mystery at the moment. `ldd` output showed e3sm and scream loading the same libraries.

> Was it because adios used differently?

I don't think so. The adios stuff was all linking statically.

**Comment by ndkeen** [comment]
I chatted with Jim and I don't want to hold up the larger merge. We can experiment later.

I know we have .a's, but I thought the final e3sm.exe was dynamically linked. nbd

**Pull request merged**
