### PR TITLE
Some fixes

### PR DESCRIPTION
**Pull request by jgfouca**
Use Approx in lin_interp_test since fp-model might not be strict.

Enable OPENMP for blake and bowman kokkos.

### CODE REVIEW

**Comment by ambrad** [comment]
We can't allow approximate testing in all builds as a means to get around some build configs. Maintaining BFB-ness in code conversions is essential because usually there is not sufficient science/math testing of each piece of the original code to allow drifting away from BFB equivalence in the two implementations with confidence. In this case, the function being tested is not very complicated, but it just happens to be the first instance of something we'll face more generally.

Here, you should generalize the test to permit BFB testing when the build implies it should hold. In `cmake/SetCompilerFlags.cmake`, there is code associated with the function `SCREAM_set_fpmodel_flags`. If the flag is set to `strict`, then define something like `SCREAM_BFB_BUILD` in `scream_config.h.in`. Use this to determine whether to do an approximate comparison or an exact one. You might introduce a test utility function `equal` (or something like that) whose definition switches at compile time on this flag.

**Comment by jgfouca** [comment]
@ambrad , see what you think of this. bowman nfs is acting up so I wasn't able to test there yet.

**Comment by jgfouca** [comment]
OK, bowman seems to work.

**Comment by jgfouca** [comment]
@ambrad , done. My initial visual parsing of SetCompilerFlags.cmake made me think fp-model only impacted fortran, but it clearly impacts C and C++ too.

**Pull request merged**
