### PR TITLE
[WIP] Fix fsurdat defaults for SCREAM compsets

### LINKED ISSUE #489: Build-time error (at case.setup) with new SCREAM compsets (with no other changes, out-of-box)
Using a repo of July 28th (and testing again with repo of Aug 3rd), the scripts I was using to launch ne256 and ne1024 jobs have not been acting the same.  The last repo I used to launch a successful ne256 test was July 15th.

It looks like I need to use either `F2000-SCREAM-HR-DYAMOND1` or `F2010-SCREAM-HR-DYAMOND1` compset, but both seem to fail with my ne256 and ne1024 scripts.
For ne256, I am trying res=`ne256pg2_r0125_oRRS18to6v3` and for ne1024, `ne1024pg2_r0125_oRRS18to6v3`

```
ERROR: Command: '/global/cscratch1/sd/ndk/wacmy/s23-aug3/components/clm/bld/build-namelist -infile /global/cscratch1/sd/ndk/e3sm_scratch/cori-knl/s23-aug3/F2000-SCREAM-HR-DYAMOND1.ne25
6pg2tri.s23-aug3.n0128t64x211121.wr.24s.nc00c.N144/Buildconf/clmconf/namelist  -csmdata /global/cfs/cdirs/e3sm/inputdata -inputdata /global/cscratch1/sd/ndk/e3sm_scratch/cori-knl/s23-a
ug3/F2000-SCREAM-HR-DYAMOND1.ne256pg2tri.s23-aug3.n0128t64x211121.wr.24s.nc00c.N144/Buildconf/clm.input_data_list -ignore_ic_date -namelist " &clm_inparm  start_ymd=20160801  /" -use_c
ase 2000_control  -res r0125  -clm_start_type default -envxml_dir /global/cscratch1/sd/ndk/e3sm_scratch/cori-knl/s23-aug3/F2000-SCREAM-HR-DYAMOND1.ne256pg2tri.s23-aug3.n0128t64x211121.
wr.24s.nc00c.N144 -l_ncpl 144 -lnd_frac /global/cfs/cdirs/e3sm/inputdata/share/domains/domain.lnd.r0125_oRRS18to6v3.200212.nc -glc_nec 0 -co2_ppmv 367.0 -co2_type diagnostic  -config /
global/cscratch1/sd/ndk/e3sm_scratch/cori-knl/s23-aug3/F2000-SCREAM-HR-DYAMOND1.ne256pg2tri.s23-aug3.n0128t64x211121.wr.24s.nc00c.N144/Buildconf/clmconf/config_cache.xml -bgc sp -mask 
oRRS18to6v3' failed with error 'File::Glob::glob() will disappear in perl 5.30. Use File::Glob::bsd_glob() instead. at /global/cscratch1/sd/ndk/wacmy/s23-aug3/components/clm/bld/CLMBui
ldNamelist.pm line 3743.
ERROR : CLM build-namelist::CLMBuildNamelist::add_default() : No default value found for fsurdat.
            Are defaults provided for this resolution and land mask?' from dir '/global/cscratch1/sd/ndk/e3sm_scratch/cori-knl/s23-aug3/F2000-SCREAM-HR-DYAMOND1.ne256pg2tri.s23-aug3.n0
128t64x211121.wr.24s.nc00c.N144/Buildconf/clmconf'
```

I can confirm that the issue is in case.setup.  Easy to repeat:

```
create_newcase --case c --res ne256pg2_r0125_oRRS18to6v3 --compset F2010-SCREAM-HR-DYAMOND1
cd c
case.setup

create_newcase --case c --res ne1024pg2_r0125_oRRS18to6v3 --compset F2010-SCREAM-HR-DYAMOND1
cd c
case.setup

Same in both cases for compset F2000-SCREAM-HR-DYAMOND1
```

Using master, I also seem to get related error, but I'm being told this is a different issue.

```
create_newcase --case c --res ne256pg2_r0125_oRRS18to6v3 --compset FC5AV1C-H01A
cd c
case.setup

Creating component namelists
  2020-08-05 12:33:16 atm 
   Calling /global/cscratch1/sd/ndk/wacmy/m37-jul7/components/cam/cime_config/buildnml
  2020-08-05 12:33:16 lnd 
   Calling /global/cscratch1/sd/ndk/wacmy/m37-jul7/components/clm/cime_config/buildnml
ERROR: Command: '/global/cscratch1/sd/ndk/wacmy/m37-jul7/components/clm/bld/build-namelist -infile /global/cscratch1/sd/ndk/wacmy/m37-jul7/cime/scripts/c/Buildconf/clmconf/namelist  -csmdata /global/cfs/cdirs/e3sm/inputdata -inputdata /global/cscratch1/sd/ndk/wacmy/m37-jul7/cime/scripts/c/Buildconf/clm.input_data_list -ignore_ic_year -namelist " &clm_inparm  start_ymd=00010101  /" -use_case 2000_control  -res r0125  -clm_start_type default -envxml_dir /global/cscratch1/sd/ndk/wacmy/m37-jul7/cime/scripts/c -l_ncpl 48 -lnd_frac /global/cfs/cdirs/e3sm/inputdata/share/domains/domain.lnd.r0125_oRRS18to6v3.200212.nc -glc_nec 0 -co2_ppmv 368.865 -co2_type diagnostic  -config /global/cscratch1/sd/ndk/wacmy/m37-jul7/cime/scripts/c/Buildconf/clmconf/config_cache.xml -bgc sp -mask oRRS18to6v3' failed with error 'File::Glob::glob() will disappear in perl 5.30. Use File::Glob::bsd_glob() instead. at /global/cscratch1/sd/ndk/wacmy/m37-jul7/components/clm/bld/CLMBuildNamelist.pm line 3743.
ERROR : CLM build-namelist::CLMBuildNamelist::add_default() : No default value found for fsurdat.
            Are defaults provided for this resolution and land mask?' from dir '/global/cscratch1/sd/ndk/wacmy/m37-jul7/cime/scripts/c/Buildconf/clmconf'
```

### PR DESCRIPTION
**Pull request by brhillman**
Make sure the fsurdat namelist variable for the land model (which specifies the land surface input data file) is set properly for SCREAM compsets using the r0125 land model. This was neglected for different reasons in the F2000 and F2010 SCREAM compsets. For F2000, it appears that somewhere along the way a default fsurdat stopped being specified for `sim_year=2000` and `hgrid=r0125`. For F2010, our compset definition failed to pick up the correct `2010_CMIP6_control` use case file for CLM. Fixes #489.

### CODE REVIEW

**Comment by brhillman** [comment]
I think actually the change to components/clm/bld/namelist_files/namelist_defaults_clm4_5.xml should go upstream. I will fix.

**Comment by brhillman** [comment]
Changing this to WIP for now since @ndkeen and I have discovered build errors with ne256.

**Comment by PeterCaldwell** [comment]
@brhillman - what's holding up this PR? Seems like it would be really helpful if it was integrated...

**Comment by brhillman** [comment]
Changes implemented upstream and in #637 so closing this.

**Pull request closed without merging**
