### PR TITLE
Update EKAT (tridiag namespace)

### PR DESCRIPTION
**Pull request by tcclevenger**
Update EKAT to include tridiag namespace addition.

### CODE REVIEW

**Review by ambrad — APPROVED** [review]

**Review by jeff-cohere — APPROVED** [review]

**Review by bartgol — APPROVED** [review]

**Review by jgfouca — CHANGES_REQUESTED** [review]
Can you please grab latest EKAT master that has my host_to_device/device_to_host changes?

**Comment by tcclevenger** [comment]
@jgfouca This includes the latest version. I think our PRs got merged around the same time.

**Comment by bartgol** [comment]
Yeah, it does. I think this can be merged.

**Comment by jgfouca** [comment]
My bad, it has it.

**Review by jgfouca — APPROVED** [review]

**Pull request merged**
