### PR TITLE
Default ne120 and ne512 to use rough topo

### PR DESCRIPTION
**Pull request by tcclevenger**
Update `namelist_defaults_scream.xml`

### CODE REVIEW

**Review by AaronDonahue — APPROVED** [review]
@ndkeen  can you check this too since you are running ne120 and ne512 runs.  Are you already using rough topo?

**Comment by tcclevenger** [comment]
@AaronDonahue I'm also testing ne120 now (waiting on summit job to run). I was planning on testing ne512 as well. I'll update here when I confirm they run.

**Comment by tcclevenger** [comment]
I've tested ne120pg2 for a 1 day run. It ran error free and I made sure the correct topo file was used. 

@ndkeen @AaronDonahue For ne512, what grid resolution `RES=?` do I use? I found `ne512pg2_r0125_oRRS18to6v3` in the config files, but summit is complaining 
```
File not found: atm2ocn_smapname = /gpfs/alpine/cli115/world-shared/e3sm/inputdata/cpl/gridmaps/ne512pg2/map_ne512pg2_to_oRRS18to6v3_bilin.200212.nc
```
so I think I'm venturing into a part of the code I don't know...

**Comment by tcclevenger** [comment]
@AaronDonahue Looks like a file name for ne512 in `cim_config/config_grids.xml` was incorrect (no file on the inputdata server). I changed the name to one in inputdata and it's queued up. If this works I'll add a commit updating the file name (probably reach out on slack to folks to make sure the file is correct).

**Comment by tcclevenger** [comment]
My setup for ne512 is incorrect. I'll reach out to Noel on slack for a simple setup.

**Comment by tcclevenger** [comment]
@AaronDonahue Talked to @ndkeen, he has not run ne512 SCREAMv1 and suggested we avoid. In my mind, we can merge this since I have verified it grabs the correct topo file for ne512.

**Pull request merged**
