### PR TITLE
EAMxx: Skip calling free_decomp when a file is closed.

### PR DESCRIPTION
**Pull request by ambrad**
We're going to try keeping decomps around indefinitely for maximal reuse.

[BFB]

### CODE REVIEW

**Review by AaronDonahue — APPROVED** [review]

**Comment by AaronDonahue** [comment]
@bartgol Is the AT timing out because of the overload you noted on mappy, on the infastructure Slack channel?

**Comment by bartgol** [comment]
> @bartgol Is the AT timing out because of the overload you noted on mappy, on the infastructure Slack channel?

Yes.

**Comment by ambrad** [comment]
@AaronDonahue when you get a chance, would you re-review this? I fixed a uniqueness issue with tag names. I also noticed some memory leaks in the SPA map-reading routine and fixed them by using `std::vector` instead of raw arrays.

**Review by AaronDonahue — APPROVED** [review]
Thanks for catching the remap issues and fixing those too.

**Comment by ambrad** [comment]
In #1980 I reinstated the free_decomp line because there are tag uniqueness issues in specific runs. We'll have to investigate those before we can keep decomps persistent. But the memory leak is at least fixed.

**Pull request merged**
