### PR TITLE
better testing for small pack size

### LINKED ISSUE #381: Most BFB tests aren't actually being checked on GPUs?
I think I've discovered a flaw in our BFB unit testing on GPUs. A lot of our tests follow a paradigm where you come up with 16 different sets of input you want to test, then try to stuff all 16 of those cases into a single set of input Spacks so we can get their solutions by a single call to the C++ version of our function of interest. To do this, data is stuffed into these input Spacks via `for (Int s = 0; s < Spack::n; ++s)`  statements... but Spack::n ==1 on GPUs. Thus this loopy assignment doesn't fail, but it only checks the first case we wanted to test!

[p3_autoconversion_unit_tests.cpp ](https://github.com/E3SM-Project/scream/blob/master/components/scream/src/physics/p3/tests/p3_autoconversion_unit_tests.cpp) is a canonical example. Look in particular around line 76.

I've confirmed empirically that this is the case by putting print statements in the code on device for Spack::n and also just printing out the output from the autoconversion bfb test... and there's only 1 output value.

I'm not sure what a better testing paradigm would be... making each Spack just repeat a single value and looping over each case we test on CPUs is wasteful but trying to stuff lots of data into a single function call on GPUs doesn't work. Ideas? @jgfouca , @pbtoast , @ambrad , @bartgol ? Also of interest to @pressel , @xyuan , @singhbalwinder .

### PR DESCRIPTION
**Pull request by jgfouca**
Fixes #381 

This work uncovered a number of FPEs so was definitely worth doing, thanks @PeterCaldwell

### CODE REVIEW

**Comment by jgfouca** [comment]
When reviewing, I recommend hiding whitespace changes.

**Comment by jgfouca** [comment]
Attn those who may have duplicated the previous flawed ut pattern: @jeff-cohere , @pressel , @singhbalwinder

**Comment by jgfouca** [comment]
@bartgol , the idea is that we need to test all the values in the Data[max_pack_size] arrays, even when max_pack_size > pack_size.

**Comment by bartgol** [comment]
> @bartgol , the idea is that we need to test all the values in the Data[max_pack_size] arrays, even when max_pack_size > pack_size.

Why do you need to test all those values? If there are different input configurations to test, since they trigger different behaviors, that's fine, but why is the input sizes as `max_pack_size` then? 

It seems to me that the p3 functions tested operate on a single pack. So adding more iterations over an array of inputs doesn't really add testing _for the p3 functions_, unless the additional iterations have data that triggers different behaviors. But then, no point in creating a template based on `max_pack_size`. It gives the developers the idea that the size of those arrays is dictated by impl details (the pack), while it should actually be dictated by however many scenarios the particular function needs to be tested on. Which can vary from function to function.

**Comment by jgfouca** [comment]
@PeterCaldwell there are static asserts to check that pack size evenly divides 16.

**Comment by PeterCaldwell** [comment]
Thanks for the explanation Jim. Is it reasonable to limit ourselves to having pack size evenly divide 16?

**Comment by bartgol** [comment]
> Thanks for the explanation Jim. Is it reasonable to limit ourselves to having pack size evenly divide 16?

I think we enforce pack sizes to be a power of 2, so it should be fine.

**Comment by PeterCaldwell** [comment]
Ok, I have no complaints at all then. Nice work - thanks!

**Comment by bartgol** [comment]
I meant to squash the commits you did, and leave the PR with 1 commit + merge commit.

By the way, tests were passing before the master merge (at least that's how it appears looking at the PR log up here). Do you need the master merge? If not, then we could avoid it, so we don't end up with 2 merge commits (master->branch and branch->master).

**Pull request merged**
