### PR TITLE
Jgfouca/pre loop unit test

### PR DESCRIPTION
**Pull request by jgfouca**

### CODE REVIEW

**Comment by jgfouca** [comment]
Needed a review from someone, so picked @jeff-cohere ; feel free to pass it to someone else.

**Comment by jgfouca** [comment]
Trying to figure out why white failed. Waterman worked fine.

**Comment by jgfouca** [comment]
Finally got this to pass. @jeff-cohere plz review or let me know if you can't

**Comment by jeff-cohere** [comment]
Hey Jim,

Sorry for not getting back to you on this sooner--this was also in my spam box. I'll review today.

**Comment by jgfouca** [comment]
@jeff-cohere , I totally agree re the argument lists; they are brutal. This is not normally how I would write code, but I feel like we are trying to stay from OOP in this effort, at least until the porting is done.

**Comment by PeterCaldwell** [comment]
Interesting comment about collecting related variables and parameters into structs rather than passing huge numbers of variables into each main function. I don't have a strong preference, but perhaps we should discuss during today's physics call...

**Comment by bartgol** [comment]
> My only thought (and this isn't specific to this PR, and shouldn't prevent its being merged) is: we're dealing with an eye-crossing number of parameters in these functions, both in the Fortran and C++. I've been thinking about this issue picking through the EAGLES aerosol stuff too. Are we at all interested in gathering related sets of parameters for these functions into structs to make them more human-readable, or is that too far afield of porting efforts?
> 

> Interesting comment about collecting related variables and parameters into structs rather than passing huge numbers of variables into each main function. I don't have a strong preference, but perhaps we should discuss during today's physics call...

I would strongly encourage such a guideline. A list of 10+ arguments (all of the same type or sharing the same context) makes the reader give up quickly. They are (to some extent) the way to go for C-F interoperable functions, but otherwise they are quite ugly, and should be avoided.

Notice that wrapping a N views in a struct is relatively cheap (since a View is mostly just 2 pointers), so one could do it on the fly too (no need to restructure all the code upstream to package data in a certain way).

**Pull request merged**
