### PR TITLE
Fixes #69

### LINKED ISSUE #69: Strange warning when building SCREAM
I get the following warning when building scream locally that I don't think is related to my P3 changes.  Not sure if it is important.

```
In file included from /g/g17/donahue5/Code/e3sm/scream/scream/components/scream/src/share/util/scream_kokkos_utils.hpp(6),
                 from /g/g17/donahue5/Code/e3sm/scream/scream/components/scream/src/share/tests/pack_kokkos_tests.cpp(7):
/g/g17/donahue5/Code/e3sm/scream/scream/components/scream/src/share/util/scream_std_meta.hpp(68): warning #488: template parameter "T" is not used in declaring the parameter types of function template "scream::util::impl::holder<HeldType>::holder<T>(std::enable_if<std::is_base_of<HeldType, T>::value, std::shared_ptr<T>>::type)"
    template<typename T>
```

### PR DESCRIPTION
**Pull request by bartgol**
When using enable_if, the condition inside cannot depend (directly or
indirectly) on the type it defines. In other words, something like

```
template<typename T>
void f(typename std::enable_if<std::is_same<T,double>::value, T>::type arg);

```
is not correct, since T cannot be deduced until the enable_if is deduced,
but the enable_if needs T to be deduced in order to be deduced...

This PR changes the implementation of the `holder` class (an implementation detail for the `any` class in `scream_std_meta.hpp`): we can no longer create them calling the constructor, but we need instead to use the static method `create`, which is overloaded for different scenarios.

### CODE REVIEW

**Comment by AaronDonahue** [comment]
@bartgol , not sure if this is related but the original warning message went away and a new one has come up:

`/g/g17/donahue5/Code/e3sm/scream/scream/components/scream/src/share/scream_pack.hpp(250): warning #15552: loop was not vectorized with "simd"`

**Comment by ambrad** [comment]
I don't think the two can be related. The simd warning is not uncommon; it's compiler dependent. There's no code mod possible except to remove the pragma around line 250 of scream_pack.hpp, but that would mean we wouldn't get vectorization on platforms that support that particular operation. Also, it seems one can't silence this warning. So as far as I can tell, no action is possible to address this warning.

**Comment by AaronDonahue** [comment]
@bartgol , thanks for the explanation.  Then I'll approve this fix.

**Comment by bartgol** [comment]
I'm going to merge this, since @AaronDonahue confirmed it fixed the warning.

**Pull request merged**
