### PR TITLE
SHOC fix to prevent raising negative value to fraction power

### PR DESCRIPTION
**Pull request by bogensch**
This PR prevents SHOC from taking the cubed root of the convective velocity scale if it is less than zero.  This was causing restart tests to fail on Cori with specific compilers.  Note that I verified that this code actually produces bit for bit results (in both SCM and global runs) with master because this convective velocity scale (conv_var) was/is only ever used (see line 1865 in shoc.F90) if it was greater than zero.

### CODE REVIEW

**Comment by PeterCaldwell** [comment]
Hi @bogensch - Ultimately I think what you're doing is ok, but I was initially freaked out that you weren't alarmed that the convective velocity scale could be negative. My current understanding is that conv_vel is the vertical integral of the SGS buoyancy flux scaled by a positive scaling factor. This will be negative when the column integral of SGS buoyancy flux is negative. I think it's physically appropriate for this to be negative, and that it makes most sense to clip this to zero. Am I getting this correctly? Would it make more sense to do this clipping where conv_vel is calculated rather than where it is used?

**Comment by bogensch** [comment]
@PeterCaldwell completely confused by your comment.  I feel like I'm doing exactly what you want... ?

**Comment by PeterCaldwell** [comment]
haha - my job is done then. I was suggesting you put a "max(0.,... on line 1835 rather than on line 1858 like you have now. My reasoning is that future developers may use conv_vel for new things without realizing it could be negative. Making sure conv_vel is always non-negative is safer than just fixing it where you use it. I don't really care if you make this change though - ignore me if I still don't make sense.

**Comment by ndkeen** [comment]
I can verify that `SMS_D.ne11_ne11.FSCREAM-LR.cori-knl_intel` as well as `SMS_D.ne11_ne11.FSCREAM-LR.cori-knl_intel19` work.

**Pull request merged**
