### PR TITLE
Speed up rain_sed bfb unit test on GPU

### PR DESCRIPTION
**Pull request by jgfouca**
The f90 implementation was taking a very long time, the CXX impl is super fast.

### CODE REVIEW

**Review by AaronDonahue — APPROVED** [review]
Does this PR impact the slowdown seen in the F90 test, as referenced in the PR description?  Since it only change cpp code I'm thinking no.

**Comment by jgfouca** [comment]
@AaronDonahue , it changes `dt` on GPU so that it does way fewer steps. This affects both f90 and cxx but the primary goal was to speed up f90.

**Comment by jgfouca** [comment]
That reminded me to add a comment.

**Comment by jgfouca** [comment]
Passed on Blake and weaver, retesting on mappy.

**Pull request merged**
