### PR TITLE
Integrating work on AD infrastructure

### PR DESCRIPTION
**Pull request by bartgol**
This is a relatively large PR, whose primary goal is to get a beta (alpha?) version of the AD working.

Among other things, this PR does:

1) Formalize the concept of grids and remap between grids.
2) There is a 'reference' grid for the simulation, where each AtmosphereProcess (AP) remaps its inputs/outputs from/to.
3) The AtmosphereProcessGroup (APG) class is now responsible of creating remapping logic, so that inputs/outputs of AP's are synced between the ref grid and the AP's own grid.
4) Pervasively tests the "phys-dyn" remap.
5) Fixes/adds a few things in the field stack (notably, the addition of the Units framework).

Note: the tests involving p3 (in the form of an atm process) still fail due to lookup table version  mismatching. @AaronDonahue is working to fix them. Everything else passes on my workstation.

### CODE REVIEW

**Comment by ambrad** [comment]
Are all the shoc* files supposed to be here, i.e., in scream/src/...? I believe shoc(_intr).F90 is intended to be the one in components/cam.

**Comment by AaronDonahue** [comment]
@ambrad , no they shouldn't be.  Yes, the interface should grab the shoc files from the /cam/src/physics/cam/ folder.  I will clean these files up, this is legacy from when we were experimenting with getting a shoc stand-alone in the AD.

**Comment by bartgol** [comment]
@AaronDonahue you have two choices, I think: a) clean up this branch from "experimenting stuff" (includes extraneous files, as well as debug print statements), b) merge as is, and then open a clean-up PR.

I'm fine with both.

**Comment by AaronDonahue** [comment]
@bartgol , That is a good suggestion.  I've cleaned up the obvious issues and pushed a new branch.  I.e. removed the shoc files as @ambrad pointed out.  I will go ahead and approve/merge this branch when the build tests have finished and then we can work to put in a clean-up PR if needed.

**Comment by AaronDonahue** [comment]
@ambrad , @jgfouca , @bartgol .  All of the tests for the `   Build name: scream_unit_tests_full_sp_debug` failed.  Is this something we should look in to?  For the other two suites of tests the fails are for the p3_stand_alone and for the p3_shoc_coupled.  Both of which are new tests we expect to fail.  But nothing in this PR should impact the other tests in the SCREAM suite, unless I'm missing something.

**Comment by bartgol** [comment]
Might be useful to merge master into the branch, to rule out the branch being behind...

**Comment by AaronDonahue** [comment]
@bartgol , I'll do that and see how it goes

**Comment by AaronDonahue** [comment]
Also, I would have expected the stand-alone homme test to show up as a new failed test like the p3_stand_alone but I'm going to guess that the Travis CI build doesn't include a build that has homme.

**Comment by bartgol** [comment]
@AaronDonahue good point! We may have to modify the testing scripts to enable homme as a dycore.

**Comment by AaronDonahue** [comment]
Also, I changed the number of homme steps to 10 in the stand_alone test just because the test takes so long.  I would leave it to you @bartgol to have the final say though.

**Comment by bartgol** [comment]
10 steps is enough for now. Without a bfb check, we are basically only testing that the code builds and runs.

**Comment by AaronDonahue** [comment]
That was my thinking as well, and even when we get a BFB (i.e. output based) test we may want to think about having a short test for the TravisCI testing, even if we want to run the full homme test for more robust development testing.

**Comment by AaronDonahue** [comment]
With these newest changes the SP build passes and the two fails from the testing suite match the expected fails from the other builds.  Namely `p3_stand_alone` and `p3_shoc_coupled`.  Final question, should we go ahead and merge?  Or should we wait to add the homme stand alone test to the testing suite so that future PR's will also test the dycore?

**Comment by bartgol** [comment]
I am for merging the PR. It's been out for a long time, and other PRs will continue to go in, making the merging of this only more complicated.

The testing of standalone homme can be added in a second time. Also, if p3 standalone and p3-shoc fail, I would not enable those tests, so that other PRs don't have to keep track of whether the failures they see are "expected" or not. A fail should never be expected (save very special scenarios). We can re-enable them later, when we figure out how to fix them.

**Comment by AaronDonahue** [comment]
Sounds good.  Unless there is any other objections/thoughts I'm going to go ahead and merge.

**Comment by AaronDonahue** [comment]
I'm going to suspend the p3 tests that are causing fails in Kokkos so as to not hold up this PR any longer. Once it goes in I can work on fixing these tests and issuing a new PR with them.

**Pull request merged**
