### PR TITLE
Tune max_ni

### PR DESCRIPTION
**Pull request by hassanbeydoun**
Changed max_total_ni to 740e3 from 500e3 to achieve desired decrease in global longwave cooling

### CODE REVIEW

**Review by crterai — APPROVED** [review]
Changes look good to me and consist with multiplying the ni_max threshold by 1.48. Thanks, @hassanbeydoun!

**Review by AaronDonahue — CHANGES_REQUESTED** [review]
This needs an equivalent change in the F90 code to pass p3_run_and_cmp

**Review by AaronDonahue — APPROVED** [review]

**Comment by AaronDonahue** [comment]
@jgfouca , @bartgol - it's been awhile since we've made a change that impacted run_and_cmp.  Remind me, we would expect p3_run_and_cmp to actually fail if we made a non-BFB change to C++ and F90 right?  Even if they actually match.  Because the comparison is based on baselines generated from the current `master` right?

**Comment by jgfouca** [comment]
@AaronDonahue , yes, i think that's right

**Comment by AaronDonahue** [comment]
okay cool, then I think this is ready to merge

**Pull request merged**
