### PR TITLE
Update F2000v1 compset to use 24 procs

### PR DESCRIPTION
**Pull request by tcclevenger**
Previously, test only used 1 proc. Now, test with 24 procs.

### CODE REVIEW

**Review by AaronDonahue — APPROVED** [review]

**Comment by AaronDonahue** [comment]
The fails on mappy are expected.  although I still don't see the `gnu9` tests in the mappy read outs.  I assume that the gnu9 test suite did run (i.e. F2000SCREAMv1) and didn't report a fail.  If so we can manually merge this PR.  @jgfouca , @bartgol or @tcclevenger can one of you confirm that mappy will pass the F2000SCREAMv1 ran through the AT and passed?

**Comment by tcclevenger** [comment]
@AaronDonahue Looked at the log, failed tests are the expected ones, the F2000Screamv1 gives DIFF test status like before. Good to merge?

**Comment by AaronDonahue** [comment]
Excellent, then I will manually merge.

**Comment by tcclevenger** [comment]
Thanks @AaronDonahue!

**Pull request merged**
