### PR TITLE
Add total precipitation diagnostic

### PR DESCRIPTION
**Pull request by tcclevenger**
Adding new diagnostic for for total precipitation surface flux that we want to measure for rough topo runs.

### CODE REVIEW

**Comment by PeterCaldwell** [comment]
Dumb/minor comment, but maybe we should call it `precip_total_surf_mass_flux` instead of `total_precip_surf_mass_flux` in order to be consistent with the liquid and ice precip variable names?

**Review by AaronDonahue — CHANGES_REQUESTED** [review]
@tcclevenger , Looks great!  I'm happy to approve but I had a question about testing.  Would it be hard to add to the test a check that the new diagnostic matches the PrecipLiq and PrecipIce diagnostics added together?  IT would be a two-fer, checking that PrecipTotal is correct and that the relationship with Liq and Ice also matches our expectations.

**Comment by tcclevenger** [comment]
@PeterCaldwell No problem changing the name.

@AaronDonahue Yeah, that will be a nice check. BFB may fail, I'll probably just change the way I calculate the total flux to match.

**Comment by tcclevenger** [comment]
Name changed and test extended to include comparison to the sum of liq/ice diagnostics.

**Review by AaronDonahue — APPROVED** [review]
Thanks for adding the test @tcclevenger

**Review by AaronDonahue — DISMISSED** [review]

**Comment by tcclevenger** [comment]
Thanks @AaronDonahue. I'm back now, I'll start to investigate the fails.

**Review by AaronDonahue — APPROVED** [review]
Welcome back @tcclevenger , looks good.  Thanks for taking care of this right away.

**Pull request merged**
