### PR TITLE
ni2nr_melt_tend tendency should be multiplied by nmltratio in conserv…

### PR DESCRIPTION
**Pull request by AaronDonahue**
…ation calc

Quick bugfix to how tendencies for rain number conservation are calculated.

Addresses issue #866

This is likely non-BFB at some level as it does adjust the impact of one of the
rain-number concentration tendencies.

[NBFB]

### CODE REVIEW

**Review by PeterCaldwell — CHANGES_REQUESTED** [review]
Needs to be fixed on C++ side too... which should be similarly trivial.

**Comment by AaronDonahue** [comment]
ahh yes, my bad :-)

**Comment by AaronDonahue** [comment]
@PeterCaldwell , I believe this is now ready.  The AT shows fails in p3_run_and_cmp_X, but that should be expected since this is a non-BFB test (right?).  I performed `test-all-scream` on this branch for both syrah and lassen where the baseline is built using the same branch and those pass.  I also tested that the F-Compset will build and run using the SMS_D test.

**Review by PeterCaldwell — APPROVED** [review]
Looks great, thanks @AaronDonahue !!!

**Comment by PeterCaldwell** [comment]
Just for posterity - I was creeped out that p3_run_and_cmp* was failing for "cases" 1 and 2 but passing for cases 3 and 4. Is this expected? I did a little sleuthing and found that cases 3 and 4 are predicted_nc=False cases so passing is the correct behavior: we're not allowing nc or ni to change.

**Pull request merged**
