### PR TITLE
Fix gptl include and remove Kokkos_ROOT settings

### PR DESCRIPTION
**Pull request by jgfouca**
Confirmed that this fixes all build errors for eamxx CIME cases on pm-cpu.

### CODE REVIEW

**Comment by ndkeen** [comment]
Are we going to have differences in e3sm/scream repo?  Or will this be downstreamed to e3sm?

**Comment by bartgol** [comment]
Jim, do you think we should fix this in the upstream? Or maybe just do a downstream merge (which we were planning anyways) when this is merged?

**Comment by jgfouca** [comment]
I'm making the same change upstream, so it should be OK.

**Comment by jgfouca** [comment]
Re-running the tests. Looking at the mappy fail, it's hard to see what went wrong. It claims the build failed but I don't see a build error anywhere. Also, it seems to work OK when I run it myself.

**Comment by ndkeen** [comment]
When I try to build on pm-cpu with `ERP_Ln9.ne4pg2_ne4pg2.F2010-SCREAMv1.pm-cpu_gnu`

```
/global/cfs/cdirs/e3sm/ndk/repos/jgfouca_cleanup_kokkos_tril/components/eamxx/src/share/atm_process/atmosphere_process_dag.cpp: In lambda function:
/global/cfs/cdirs/e3sm/ndk/repos/jgfouca_cleanup_kokkos_tril/components/eamxx/src/share/atm_process/atmosphere_process_dag.cpp:149:37: error: 'const Units' {aka 'const class ekat::units::Units'} has no member named 'get_string'\
; did you mean 'get_si_string'?
  149 |         s += " [" + fid.get_units().get_string() + "]";
      |                                     ^~~~~~~~~~
      |                                     get_si_string
```

**Comment by jgfouca** [comment]
@bartgol , did something change in Ekat::Units? @ndkeen , are you sure your submodules are updated?

**Review by bartgol — APPROVED** [review]

**Comment by ndkeen** [comment]
Jim: you said this fixed build errors on pm-cpu. What tests did you run?  You can see the test I ran to get build error.

**Comment by jgfouca** [comment]
@ndkeen something is up with your repo. `./create_test e3sm_scream_v1_medres --compiler=gnu --no-run` all built fine for me.

**Comment by bartgol** [comment]
> Jim: you said this fixed build errors on pm-cpu. What tests did you run? You can see the test I ran to get build error.

Noel, i think you tried the e3sm branch though, no? At least that's my understanding from the slack convo. This PR is in the scream repo, where `get_string` is not used anymore...

**Comment by ndkeen** [comment]
ah, ok.  i just made this comment on the wrong PR

**Review by ndkeen — APPROVED** [review]

**Pull request merged**
