### PR TITLE
Addresses some suggestions in issue #2858.

### PR DESCRIPTION
**Pull request by overfelt**
There were two issues to be addressed:
Use lambdas instead of functions in some Kokkos::parallel_for loops over team members.
Fuse some Kokkos::parallel_for loops to improve efficiency.

Addresses #2858 's 2nd point

### CODE REVIEW

**Comment by singhbalwinder** [comment]
Hi @susburrows: This is one of the smaller PRs for addressing some of the issues in the ACI PR. The tests are passing. I am not sure how you would like to handle small PRs. I have assigned @bartgol and @mahf708 as reviewers since they reviewed this part of the ACI PR.

**Comment by singhbalwinder** [comment]
I am going to WIP this PR to save testing cycles but we can turn it back before merging.

**Review by bartgol — APPROVED** [review]

**Comment by AaronDonahue** [comment]
@overfelt , @bartgol , @mahf708 is this ready to merge now?  @susburrows did you want to review first before we merge?

**Comment by overfelt** [comment]
Sure, ready to merge.

**Comment by susburrows** [comment]
@singhbalwinder thanks for flagging me on this, and apologies for the slight delay in following up: as you know, I was on vacation for part of last week, and I've been catching up on a few time-sensitive things since returning.  For smaller PRs like this one, I think it's fine to just have them reviewed by appropriate folks such as Naser and Luca and then merge (if they pass reviews and testing) without me needing to additionally review and approve them.  However, I would appreciate it if you could flag me (e.g., via a mention) for my awareness.  Thanks!

**Pull request merged**
