### PR TITLE
Jgfouca/duplicate xyuan

### PR DESCRIPTION
**Pull request by jgfouca**

### CODE REVIEW

**Comment by jgfouca** [comment]
@xyuan , this is a renamed version of the branch you were using for #505 .

**Comment by bartgol** [comment]
Notice that this branch missed your commit from 19h ago, and the master merge from 5h ago. I wonder if the same shenanigans show up if we add those commits. Looking carefully at the git tree, I see no reason for the old PR list of commits to be so bloated.

**Comment by xyuan** [comment]
@jgfouca let me close this PR, and redo it based on the master branch solves this issue.

**Comment by jgfouca** [comment]
@bartgol , @xyuan , i restored his work. I mistakenly had an older version of his branch when I initially set this up. I think we are OK.

**Comment by bartgol** [comment]
@xyuan this seems fine now, no need to close and re-do. I have no idea why your PR looked messy, while this one doesn't. It's the same git history.

The good old "turn it off and turn it on" strikes again.

**Comment by jgfouca** [comment]
I'm done with my modifications. I think this is finally ready to merge, so I've turned on automerge.

**Pull request merged**
