### PR TITLE
Jgfouca/upstream merge 2022 10 10

### PR DESCRIPTION
**Pull request by jgfouca**
CONFLICTS:

### File: components/eam/bld/build-namelist

```
<<<<<<< HEAD
#RRTMGP
add_default($nl, 'do_spa_optics');

# MMF Microphysics scheme
add_default($nl, 'MMF_microphysics_scheme');
add_default($nl, 'use_MMF');
add_default($nl, 'use_ECPP');
=======
if ($cfg->get('use_MMF')) {
    # MMF Microphysics scheme
    add_default($nl, 'MMF_microphysics_scheme');
    add_default($nl, 'use_MMF');
    add_default($nl, 'use_ECPP');

    # MMF Variance Transport
    add_default($nl, 'use_MMF_VT');
    add_default($nl, 'MMF_VT_wn_max');
>>>>>>> upstream/master
```

Solution: Keep upstream but add do_spa_optics above it

### File: components/eam/src/control/runtime_opts.F90

Line ~180
```
<<<<<<< HEAD
logical  :: scm_multcols
logical  :: dp_crm
=======
logical  :: scm_zero_non_iop_tracers
>>>>>>> upstream/master
```

Solution: Keep both

Line 340
```
   ! scam
   namelist /cam_inparm/ iopfile,scm_iop_srf_prop,iop_dosubsidence, &
                         iop_nudge_tq, iop_nudge_uv, iop_nudge_tq_low, &
                         iop_nudge_tq_high, iop_nudge_tscale, &
                         scm_diurnal_avg,scm_crm_mode,scm_clubb_iop_name, &
                         scm_observed_aero, precip_off, &
<<<<<<< HEAD
                         iop_perturb_high, dp_crm
=======
                         scm_zero_non_iop_tracers
>>>>>>> upstream/master
```

Solution: Keep both

Line ~380
```
      call scam_default_opts(scmlat_out=scmlat,scmlon_out=scmlon, &
        single_column_out=single_column, &
        scm_iop_srf_prop_out=scm_iop_srf_prop,&
        iop_dosubsidence_out=iop_dosubsidence, &
        iop_nudge_tq_out=iop_nudge_tq, &
        iop_nudge_uv_out=iop_nudge_uv, &
        iop_nudge_tq_low_out=iop_nudge_tq_low, &
        iop_nudge_tq_high_out=iop_nudge_tq_high, &
        iop_nudge_tscale_out=iop_nudge_tscale, &
        iop_perturb_high_out=iop_perturb_high, &
        scm_diurnal_avg_out=scm_diurnal_avg, &
        scm_crm_mode_out=scm_crm_mode, &
        scm_observed_aero_out=scm_observed_aero, &
        precip_off_out=precip_off, &
<<<<<<< HEAD
        scm_multcols_out=scm_multcols, &
        dp_crm_out=dp_crm, &
        scm_clubb_iop_name_out=scm_clubb_iop_name)
=======
        scm_clubb_iop_name_out=scm_clubb_iop_name, &
        scm_zero_non_iop_tracers_out=scm_zero_non_iop_tracers)
>>>>>>> upstream/master
```

Solution: Keep both (without duplicating scm_clubb_iop_name_out)

Line ~480

 ```
        call scam_setopts( scmlat_in=scmlat,scmlon_in=scmlon, &
                            iopfile_in=iopfile,single_column_in=single_column,&
                            scm_iop_srf_prop_in=scm_iop_srf_prop,&
                                                iop_dosubsidence_in=iop_dosubsidence,&
                            iop_nudge_tq_in=iop_nudge_tq, &
                            iop_nudge_uv_in=iop_nudge_uv, &
                                                iop_nudge_tq_low_in=iop_nudge_tq_low, &
                            iop_nudge_tq_high_in=iop_nudge_tq_high, &
                            iop_nudge_tscale_in=iop_nudge_tscale, &
                            iop_perturb_high_in=iop_perturb_high, &
                            scm_diurnal_avg_in=scm_diurnal_avg, &
                            scm_crm_mode_in=scm_crm_mode, &
                            scm_observed_aero_in=scm_observed_aero, &
                            precip_off_in=precip_off, &
<<<<<<< HEAD
                            scm_multcols_in=scm_multcols,&
                                                dp_crm_in=dp_crm,&
                            scm_clubb_iop_name_in=scm_clubb_iop_name)
=======
                            scm_clubb_iop_name_in=scm_clubb_iop_name, &
                            scm_zero_non_iop_tracers_in=scm_zero_non_iop_tracers)
>>>>>>> upstream/master
```

Solution: Keep both (w/out duplicating scm_clubb_iop_name_in)

### File: components/eam/src/control/scamMod.F90

```
subroutine scam_default_opts( scmlat_out,scmlon_out,iopfile_out, &
        single_column_out,scm_iop_srf_prop_out, &
        iop_dosubsidence_out,  &
        iop_nudge_tq_out, iop_nudge_uv_out, iop_nudge_tq_low_out, &
        iop_nudge_tq_high_out, iop_nudge_tscale_out, &
        scm_diurnal_avg_out, scm_crm_mode_out, scm_observed_aero_out, &
<<<<<<< HEAD
        precip_off_out, scm_clubb_iop_name_out, &
        scm_multcols_out, dp_crm_out, iop_perturb_high_out)
=======
        precip_off_out, scm_clubb_iop_name_out, scm_zero_non_iop_tracers_out)
>>>>>>> upstream/master
```

Solution: Keep both (without duplication)

```
subroutine scam_setopts( scmlat_in, scmlon_in,iopfile_in,single_column_in, &
                         scm_iop_srf_prop_in, &
                         iop_dosubsidence_in, &
                         iop_nudge_tq_in, iop_nudge_uv_in, iop_nudge_tq_low_in, &
                         iop_nudge_tq_high_in, iop_nudge_tscale_in, &
                         scm_diurnal_avg_in, scm_crm_mode_in, scm_observed_aero_in, &
                         precip_off_in, scm_clubb_iop_name_in, &
<<<<<<< HEAD
                         scm_multcols_in, dp_crm_in, iop_perturb_high_in)
=======
                         scm_zero_non_iop_tracers_in)
>>>>>>> upstream/master
```

Solution: Keep both

```
<<<<<<< HEAD
  real(r8), intent(in), optional       :: iop_nudge_tq_low_in
  real(r8), intent(in), optional       :: iop_nudge_tq_high_in
  real(r8), intent(in), optional       :: iop_nudge_tscale_in
  real(r8), intent(in), optional       :: iop_perturb_high_in
=======
  real(r8), intent(in), optional       :: scm_relaxation_low_in
  real(r8), intent(in), optional       :: scm_relaxation_high_in
  logical, intent(in), optional        :: scm_zero_non_iop_tracers_in
>>>>>>> upstream/master
```

Solution: Remove scm_relaxation_low_in and scm_relaxation_high_in since they aren't in the subroutine
signature and aren't used within the subroutine. Add scm_zero_non_iop_tracers_in to HEAD

### File: components/eam/src/dynamics/se/se_single_column_mod.F90

```
subroutine scm_setinitial(elem)

<<<<<<< HEAD
  use kinds, only : real_kind
=======
  use constituents, only: qmin
>>>>>>> upstream/master

```
Solution: Take both

```
subroutine apply_SC_forcing(elem,hvcoord,hybrid,tl,n,t_before_advance,nets,nete)
!
    use scamMod
    use kinds, only : real_kind
    use dimensions_mod, only : np, np, nlev, npsq, nelem
    use control_mod, only : use_cpstar, qsplit, qsplit
    use hybvcoord_mod, only : hvcoord_t
    use element_mod, only : element_t
    use physical_constants, only : Cp, Rgas, cpwater_vapor
    use time_mod
<<<<<<< HEAD
    use hybrid_mod, only : hybrid_t
    use constituents, only: pcnst
=======
>>>>>>> upstream/master
```

Solution: Take HEAD since both items are used in the subroutine.

### File: components/elm/bld/namelist_files/namelist_definition.xml

```
<entry id="mask" type="char*20" category="default_settings"
       group="default_settings"
<<<<<<< HEAD
       valid_values="USGS,gx3v7,gx1v6,navy,test,tx0.1v2,tx1v1,T62,TL319,cruncep,oEC60to30v3,oEC60to30v3wLI,ECwISC30to60E1r2,EC30to60E2r2,WC14to60E2r3,WCAtl12to45E2r4,SOwISC12to60E2r4,ECwISC30to60E2r1,oRRS18to6,oRRS18to6v3\
,oRRS15to5,oARRM60to10,oARRM60to6,oQU480,oQU240,oQU240wLI,oQU120,oRRS30to10v3,oRRS30to10v3wLI,360x720cru,NLDASww3a,NLDAS,tx0.1v2,ICOS10">
=======
       valid_values="USGS,gx3v7,gx1v6,navy,test,tx0.1v2,tx1v1,T62,TL319,cruncep,oEC60to30v3,oEC60to30v3wLI,ECwISC30to60E1r2,EC30to60E2r2,WC14to60E2r3,WCAtl12to45E2r4,SOwISC12to60E2r4,ECwISC30to60E2r1,oRRS18to6,oRRS18to6v3\
,oRRS15to5,oARRM60to10,oARRM60to6,ARRM10to60E2r1,oQU480,oQU240,oQU240wLI,oQU120,oRRS30to10v3,oRRS30to10v3wLI,360x720cru,NLDASww3a,NLDAS,tx0.1v2">
>>>>>>> upstream/master
Land mask description
</entry>
```

Solution: Merge value lists (adds ARRM10to60E2r1 from upstream and ICOS10 from HEAD)

### CODE REVIEW

**Comment by ambrad** [comment]
We should have @bogensch look over the SCM and IOP conflict resolutions.

**Review by bogensch — APPROVED** [review]

**Review by brhillman — APPROVED** [review]

**Review by oksanaguba — DISMISSED** [review]
conflicts are not related to hip homme PR.

**Comment by ambrad** [comment]
@AaronDonahue @jgfouca we have a path forward on the HIP part of the issue.

While Oksana and I work out the logistics, @jgfouca can study the cuda version module issues.

**Comment by jgfouca** [comment]
@ambrad, I've sync'd our summit entry in config_machines.xml with the upstream. When we split summit into summit-cpu and summit-gpu, then later undid that change by merging them, we got out-of-sync with the upstream. My attempt to sync will have the following impacts for SCREAM users:

1) gnu and gnugpu compiler version of GCC will be bumped up from 7.5.0 to 9.1.0
2) gnu and pgi compiler (non-gpu versions) will now have 84 MPI tasks per node
3) gnugpu will have cuda version bumped up from 10.1.168 to 11.0.3

Our summit entry will continue to be a bit different than the upstream due to the `PAMI_*` env variables we have added to a couple of the compilers.

**Comment by ambrad** [comment]
@jgfouca great, that makes sense; thanks. 1 and 3 are what we want. 2 is irrelevant.

**Comment by ambrad** [comment]
Re: the HIP part, Oksana will submit a PR to upstream with this commit: https://github.com/E3SM-Project/E3SM/commit/9ad04c6f871c958e4ad31d9d578e47ea10603669, once she has tested standalone hxx on weaver. Jim, you can then merge that commit into this branch (should merge right on top, perhaps also bringing in a handful of upstream PRs, which is fine) and then let the AT rerun.

**Comment by ambrad** [comment]
I merged Oksana's branch https://github.com/E3SM-Project/E3SM/pull/5233 into this one. The SHA1s are the same. Thus, in our next upstream merge, the merge process will see these commits are already present and move on.

**Comment by AaronDonahue** [comment]
The AT reports that standalone testing failed on `mappy` but the error log doesn't show what failed.  Should we just retest?

**Comment by ambrad** [comment]
Yes, I just added RETEST. If it fails again, we'll check mappy manually.

**Comment by jgfouca** [comment]
@ambrad , I see it too. Working on it.

**Comment by jgfouca** [comment]
@bartgol , I pushed a ninja fix for the fetch problem. I'm wondering how this ever worked? All our submodules are managed through ssh protocol, so they can only be fetched if you have a valid ssh key in $HOME/.ssh. This can be a problem for entity accounts like e3sm-jenkins.

My fix makes it so the subm update is done without fetching as a backup if the first try fails.

**Review by bartgol — APPROVED** [review]

**Pull request merged**
