### PR TITLE
Verify that every C++ file has been formatted with clang-format

### PR DESCRIPTION
**Pull request by mfdeakin-sandia**

### CODE REVIEW

**Comment by mfdeakin-sandia** [comment]
This should be accompanied by running clang-format 5 (what travis-ci has, though I believe we can change that) on the reported files

**Comment by mfdeakin-sandia** [comment]
Travis output:
```
+git push -u origin master
remote: Invalid username or password.
fatal: Authentication failed for 'https://github.com/E3SM-Project/scream.git/'
```
I was afraid of this...

**Comment by jgfouca** [comment]
Why does the implementation require push access?

**Comment by mfdeakin-sandia** [comment]
@ambrad and I think the best way to enforce formatting is to automatically apply it to master after a merge

**Comment by jgfouca** [comment]
@mfdeakin-sandia , that would be nice I guess, but how are you going to allow the travis bot to have push access? I think it would be fine to simply reject the PR if the formatting isn't right.

**Comment by ambrad** [comment]
I want to clarify two things.

First, I personally am weakly opposed to any formatting requirements.

Second, and that personal opinion aside, the decision process so far has been this: Some folks want enforced formatting. Not everyone has convenient access to the same formatter (clang, clang version). Thus, if uniform formatting is to be implemented w/o imposing a burden on individual devs, it must be done automatically in the background.

**Comment by mfdeakin-sandia** [comment]
https://gist.github.com/willprice/e07efd73fb7f13f917ea explains how to do it. I'm setting up a github account (which I will immediately transfer to someone else) which I'll generate a public access token for travis with. Travis has a way of securely passing tokens to the job, so I'll use that to get it in.
Note that the code here isn't quite complete - it needs to only run when the branch is master.

**Comment by mfdeakin-sandia** [comment]
@jgfouca The most important part of this PR is actually working now, though you might want to make some tweaks to how travis-ci makes the formatting commits - ie, only do it when a commit comes in to master.

**Comment by ambrad** [comment]
A Travis CI format commit went into master. I'm going to revert that tomorrow. @mfdeakin-sandia, is it possible this branch is affecting master? I speculate the Travis CI that runs on this branch is pushing a format commit to master. I would prefer that not happen until everyone has had a chance to weigh in on and agree to format commits. Thanks.

**Comment by mfdeakin** [comment]
Yes, that is what happened; and is why it needs the check to ensure it's only done when a commit comes into master

**Comment by mfdeakin** [comment]
On another note, since the project is relying on automatic code formatting commits, we can upgrade to a higher version of clang-format which has more features like indenting preprocessor directives (similar to how you do).

**Comment by ambrad** [comment]
I'm closing this since an attempt to enforce auto formatting would likely require a new PR.

**Pull request closed without merging**
