### PR TITLE
Fixing issues with EkatDisableAllWarning

### PR DESCRIPTION
**Pull request by bartgol**
This mini PR should fix some warnings we see across the board on CDash with Intel compilers. Basically, I was using the wrong compiler flags to ignore warnings.

### CODE REVIEW

**Comment by AaronDonahue** [comment]
It looks like p3_run_and_cmp failed the AutoTester for the SP case.  I don't see how this PR would effect p3_run_and_cmp.  Should we RETEST?

**Comment by bartgol** [comment]
Might be due to @jeff-cohere PR that changed the number of fields in the baselines. I will rebase on master and force push.

**Comment by bartgol** [comment]
Uhm, no, the branch is already up to date. This is weird, since all it changed was suppressing warnings via compiler flag. I'd wait another round of testing before checking what's wrong.

Either way, I am leaving for vacation in 3, 2, 1... so I won't be able to check again till Monday.

**Comment by jgfouca** [comment]
Upstream merge to resolve cime issues.

**Comment by bartgol** [comment]
I'm back from vacation. I'll take a look at the failure on GPU, and try to fix it.

**Comment by bartgol** [comment]
I'm assuming this PR fails for the same reason that master fails in SP. I will wait for that to be fixed first.

**Pull request merged**
