### PR TITLE
Jgfouca/upstream merge 2022 01 27

### PR DESCRIPTION
**Pull request by jgfouca**
Conflicting files were:

```
	both modified:   cime_config/allactive/config_compsets.xml
	both modified:   components/eam/cime_config/config_component.xml
	both modified:   components/homme/src/theta-l_kokkos/prim_driver_mod.F90
```

None of the conflicts were tricky to resolve.

This should allow us to finally close: https://github.com/E3SM-Project/scream/pull/1151

### CODE REVIEW

**Review by bartgol — APPROVED** [review]
I may or may not have skipped a few of the 531 files modified...

**Comment by AaronDonahue** [comment]
It looks like this upstream merge might be causing fails in our unit tests.  @jgfouca can you check the logs and see which one(s)?  That might help us narrow down why.

**Comment by jgfouca** [comment]
@AaronDonahue , scream unit test failures are a surprise. I did test the CIME stuff and it worked. I will do the unit tests by hand to see what's going on.

**Comment by jgfouca** [comment]
@bartgol , on this branch, `./homme_standalone` is failing with:

```
Error in init_simulation_params_c: unsupported value '-1' for input parameter 'nsplit'.
 The value should satisfy nsplit >= 1.
```

**Comment by bartgol** [comment]
> @bartgol , on this branch, `./homme_standalone` is failing with:
> 
> ```
> Error in init_simulation_params_c: unsupported value '-1' for input parameter 'nsplit'.
>  The value should satisfy nsplit >= 1.
> ```

Ugh, I need to hurry up and replace scream's version of namelist parsing with native homme's `readnl`. I need to modify the upstream in order to do that though. I will work on that today. Meanwhile, I will add a patch to this PR.

**Comment by bartgol** [comment]
@jgfouca the nsplit error should be fixed. The test runs on my laptop now.

**Comment by bartgol** [comment]
The baselines were just re-blessed. Re-testing (skipping weaver/blake, since they already passed).

**Comment by AaronDonahue** [comment]
@bartgol , it looks like we still have a DIFF in the SCREAMv1 test on mappy.  That being said, is this one of those things where we would need to manually test on mappy?

**Comment by bartgol** [comment]
@AaronDonahue @jgfouca I think this requires a master merge, in order to pass the v1 tests.

**Comment by jgfouca** [comment]
@bartgol , done. thanks for the heads up

**Comment by jgfouca** [comment]
The one CIME V1 diff on mappy is expected, merging.

**Comment by jgfouca** [comment]
Tested the minor changes since the last AT run by hand on mappy. Merging.

**Pull request merged**
