### PR TITLE
Change name of surf_latent_heat to surf_evaporation to match coupler.

### PR DESCRIPTION
**Pull request by AaronDonahue**
This commit change the name of the field manager variable
surf_latent_heat to be surf_evaporation.  Which is what the actual
variable passed by the component coupler represents.

This commit also changes the units of the variable in the FM to
match the units in the component coupler.

### CODE REVIEW

**Comment by PeterCaldwell** [comment]
Looks good to me. I prefer the name `surf_evap` because I think our goal is to be as short as possible so long as our meaning is unambigious... but I don't care too much.

**Comment by PeterCaldwell** [comment]
I'd approve, but I want Peter B to get a chance to look at it before it auto-merges.

**Comment by AaronDonahue** [comment]
> Looks good to me. I prefer the name `surf_evap` because I think our goal is to be as short as possible so long as our meaning is unambigious... but I don't care too much.

I can make that change, super easy, and we might as well do it right the first time.

**Comment by bogensch** [comment]
Looks good to me!

**Review by bogensch — APPROVED** [review]

**Comment by AaronDonahue** [comment]
@bartgol (pinging you because you wrote the test) , this is failing the AT for just the suite of `model_restart` tests.  I'm thinking this is because those tests expect the old variable, `surf_latent_heat` to be present in the netCDF init file and it's missing.  Does this sound correct?  If so then I just need to update the name in that file I should be good to go.

**Comment by bartgol** [comment]
I think you're right, but let me hop on the testbeds, and manually inspect the cprnc output.

**Comment by bartgol** [comment]
Yeah

```
  PIO ERROR: could not find variable surf_evap in file     homme_physics_ne2np4.nc
```

**Comment by AaronDonahue** [comment]
Okay, so we need to change the file.  I'm going to hold off on that until Jims big refactor PR goes in #1391 .  Then I can update the file on blues and change its name so it will be automatically downloaded.

**Comment by AaronDonahue** [comment]
Chatted with @jgfouca on Slack and we decided that I'll make the init condition file change here and he can take care of the changes in his PR.

**Comment by AaronDonahue** [comment]
@bogensch , do you mind re-approving.  I think this needs to be reapproved after I made a new commit.

**Review by bogensch — APPROVED** [review]

**Comment by AaronDonahue** [comment]
This one is pending a rebase and a file upload to blues, since we need a different initial condition file for the model_restart tests.

**Comment by AaronDonahue** [comment]
I don't have easy access to mappy so I'm speculating here, but I think that this PR is failing for the SCREAMv1 CIME based runs because the initial condition files those cases are using have the variable `latent_heat_flux` instead of `surf_evap`.  That being said, isn't this information coming from the surface coupler?  I wouldn't expect SCREAM to need to grab this info from the initial condition file anyway.  The easy fix would be to change the name of `latent_heat_flux` to `surf_evap` in our two initial condition files for SCREAMv1.  But I wanted to check on the behavior in general in case it is something we expect.

@bartgol or @tcclevenger , do you have any thoughts?  Also, if one of you have a chance could you hop on mappy and check that my speculation is correct?

**Comment by tcclevenger** [comment]
@AaronDonahue I can hop on mappy real quick and check.

**Comment by tcclevenger** [comment]
The error is 
```
PIO ERROR: could not find variable surf_evap in file /sems-data-store/ACME/inputdata/atm/scream/init/init_ne4np4.nc
```

Does that `.nc` file need to be updated? I don't think this has to do with SC since it does not deal with `latent_heat_flux/surf_evap`.

**Comment by tcclevenger** [comment]
Also, `latent_heat_flux/surf_evap` isn't in the SC. We do have `surf_latent_flux` (SCREAM name)/`Faxx_evap` (surface model name). I'm assuming those are not the same?

**Comment by AaronDonahue** [comment]
> The error is
> 
> ```
> PIO ERROR: could not find variable surf_evap in file /sems-data-store/ACME/inputdata/atm/scream/init/init_ne4np4.nc
> ```
> 
> Does that `.nc` file need to be updated?

Yeah, that was my theory.  I had to update the homme+physics model restart test to have `surf_evap` instead of `surf_latent_flux`

**Comment by AaronDonahue** [comment]
> > The error is
> > ```
> > PIO ERROR: could not find variable surf_evap in file /sems-data-store/ACME/inputdata/atm/scream/init/init_ne4np4.nc
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Does that `.nc` file need to be updated?
> 
> Yeah, that was my theory. I had to update the homme+physics model restart test to have `surf_evap` instead of `surf_latent_flux`

@tcclevenger , yes sorry, I meant `surf_latent_flux`.

**Comment by AaronDonahue** [comment]
> Also, `latent_heat_flux/surf_evap` isn't in the SC. We do have `surf_latent_flux` (SCREAM name)/`Faxx_evap` (surface model name). I'm assuming those are not the same?

Yes, @tcclevenger , sorry, I mean `surf_latent_flux`.  I guess the question still applies, if `surf_latent_flux` is one of the import variables do we know why SCREAM is even looking for it in the first place.  Note that with this PR it has been changed to `surf_evap` and that is what it can't find in the IC file.

**Comment by tcclevenger** [comment]
So the mystery is that something that is specific to the SCREAMv1 run is asking for `surf_evap`? I'm running in debug to see if I can get a more useful error that points me to where this is begin queried.

**Comment by tcclevenger** [comment]
When we register an import, we need to call
```
SurfaceCoupling::register_import(fname) {
  .
  . 
  .
  Field field = m_field_mdr->get_field(fname)
  .
  .
  .
}
```
I'm guessing this is what is being called.

**Comment by bartgol** [comment]
> > Also, `latent_heat_flux/surf_evap` isn't in the SC. We do have `surf_latent_flux` (SCREAM name)/`Faxx_evap` (surface model name). I'm assuming those are not the same?
> 
> Yes, @tcclevenger , sorry, I mean `surf_latent_flux`. I guess the question still applies, if `surf_latent_flux` is one of the import variables do we know why SCREAM is even looking for it in the first place. Note that with this PR it has been changed to `surf_evap` and that is what it can't find in the IC file.

Are you saying that scream is looking in the IC file for the imported fields? Yeah, that sounds wrong...

**Comment by AaronDonahue** [comment]
Yeah, I think it probably doesn't use them.  But looks for them all the same.  We will want to fix that.

**Comment by bartgol** [comment]
It's probably an issue with the DAG. I think addressing #1255 would fix this, since the SC imported fields would not appear as inputs for the ATM group anymore.

Note: we do print a correct DAG, including the surface coupling, but when we check which fields need an Initial Condition ([here](https://github.com/E3SM-Project/scream/blob/32ffa4b57f28591ad208b9aa61198c7e7ccd43a0/components/scream/src/control/atmosphere_driver.cpp#L557)), we do not keep into account the surface coupling...

**Comment by tcclevenger** [comment]
@bartgol Yeah, that's what I figured I would move to next. Figured out why p3 wasn't scaling (loading decently large tables on host, which can be done during initialization).

**Comment by AaronDonahue** [comment]
Closing because this branch is stale and #1751 does the same thing.

**Pull request closed without merging**
