### PR TITLE
Crusher: Add -scream identifier to machine configuration.

### PR DESCRIPTION
**Pull request by ambrad**
This identifier will deconflict SCREAM's configuration code blocks from anything upstream. Work to consolidate settings, if desired, can then proceed at a natural pace rather than be rushed by our SCREAM->E3SM merge effort.

### CODE REVIEW

**Comment by ambrad** [comment]
@oksanaguba @rljacob: Do either of you object to this approach?

**Comment by jgfouca** [comment]
@ambrad , this change will have some downstream effects. I would have to make some minor changes to some of the test scripts in E3SM_test_scripts and it would change the "Site" field on Cdash.

**Comment by rljacob** [comment]
Can you also implement the decision we made here:  https://acme-climate.atlassian.net/wiki/spaces/EIDMG/pages/3446079573/How+to+describe+heterogenous+node+machines+with+CIME
Namely, don't have "gpu" and "cpu" machine entries for single-node-architecture systems like Summit/crusher.  Instead use the compiler entires for a cpu-only compile.

**Review by oksanaguba — DISMISSED** [review]

**Comment by oksanaguba** [comment]
@rljacob i was in the middle of this PR for that suggestion (no -cpu, no -gpu machine) https://github.com/E3SM-Project/scream/pull/2129 , but i thought after today that it would be abandoned and the focus would be on keeping scream machines setup separate and functioning.

**Comment by ambrad** [comment]
@rljacob your request in my opinion is orthogonal to the spirit of this effort, which is to get EAMxx cleanly into upstream ASAP for the benefit of MMF while preserving current SCREAM functionality. In my opinion, the "-scream" identifier is sufficient to make clear that the machine configs are for a specific purpose. Subsequent work on improving compliance with E3SM's approach can occur without a deadline.

**Comment by ambrad** [comment]
@jgfouca yes I was planning to make the script changes myself and then ask you for a cdash entry update once this PR goes in.

**Comment by jgfouca** [comment]
Sounds good.

**Comment by rljacob** [comment]
@oksanaguba adding "scream" is what keeps them separate.   A follow-up PR that gets rid of "-cpu" and "-gpu" would be welcome but it can wait.

**Comment by oksanaguba** [comment]
thanks, however, now i do not know what to do with that PR even after Ben's merge happens. I will close it for now.

**Comment by ambrad** [comment]
> thanks, however, now i do not know what to do with that PR even after Ben's merge happens. I will close it for now.

@oksanaguba one thing you might consider is the following: Once Ben's PR is merged into E3SM, SCREAM will run just as well from that repo as the SCREAM repo. You can then work with Az and others, as necessary, to consolidate the Crusher configurations in E3SM. When the consolidated configuration works for SCREAMv1 tests on Crusher, the -scream one can be removed from E3SM. The next upstream merge to SCREAM will then bring in the consolidated configuration and remove the -scream one.

**Review by rljacob — DISMISSED** [review]

**Comment by ambrad** [comment]
@oksanaguba The CPU test was failing due to an invalid project ID. I've fixed it here: https://github.com/E3SM-Project/scream/commit/8dbac84373ce4d9a663b96ec547eea7f30fa77fd. Have you experienced that before, and are you OK with this change?

**Comment by oksanaguba** [comment]
Andrew, i received your comment " Have you experienced that before, and are you OK with this change?" in email, do not see it here. Yes, i changed project id in the PR i was working on.

**Comment by ambrad** [comment]
I ran several GPU and one CPU test with these modifications and got all PASSes. Manually merging.

**Pull request merged**
