### PR TITLE
Jgfouca/upstream merge 2021 07 16

### PR DESCRIPTION
**Pull request by jgfouca**
Conflicts were minimal:

### File: eam/src/physics/cam/cam_diagnostics.F90

Line 1980:
```
<<<<<<< HEAD
   call pbuf_get_field(pbuf, pblh_idx, pblh)
=======
   if (linearize_pbl_winds) then
      call pbuf_get_field(pbuf, wsresp_idx, wsresp)
      call pbuf_get_field(pbuf, tau_est_idx, tau_est)
   end if
>>>>>>> upstream/master
```

Solution: keep both

### File: eam/src/physics/cam/phys_control.F90

Line 199:
```
<<<<<<< HEAD
      conv_water_in_rad, history_clubb, do_clubb_sgs, do_shoc_sgs, do_tms, state_debug_checks, &
=======
      conv_water_in_rad, history_clubb, do_clubb_sgs, do_tms, state_debug_checks, &
      linearize_pbl_winds, export_gustiness, &
>>>>>>> upstream/master
```

Solution: Add do_shoc_sgs to upstream

Line 491:
```
<<<<<<< HEAD
                        do_clubb_sgs_out, do_shoc_sgs_out, do_tms_out, state_debug_checks_out, &
=======
                        do_clubb_sgs_out, do_tms_out, state_debug_checks_out, &
                        linearize_pbl_winds_out, export_gustiness_out, &
>>>>>>> upstream/master
```

Solution: Add do_shoc_sgs_out to upstream

Note: this update should return mappy CIME scream test reports.

### CODE REVIEW

**Comment by jgfouca** [comment]
Note: the CIME scream test `ERS_R_Ln10.ne4_ne4.FDPSCREAMA97` still fails with this PR and it will start showing on our dashboard. As a reminder, the root cause of the fail is:

    `Merge Pull Request #922 from E3SM-Project/scream/bogensch/dp_scream`

**Comment by AaronDonahue** [comment]
> Note: the CIME scream test `ERS_R_Ln10.ne4_ne4.FDPSCREAMA97` still fails with this PR and it will start showing on our dashboard. As a reminder, the root cause of the fail is:
> 
> ```
> `Merge Pull Request #922 from E3SM-Project/scream/bogensch/dp_scream`
> ```

@jgfouca , didn't #1086 address this issue?

**Comment by jgfouca** [comment]
@AaronDonahue , based on the discussion of #1086 , it caused this issue:

```
@jgfouca , I wonder if we could still merge this PR now and let the new set of fails get into master? We won't lose sight of them since they will keep popping up on CDash but at least CDash will move from showing build failures to runtime failures which will be more informative. Since very few PR's use the AT:CIME Label this shouldn't impact development but will at least let us move on from this PR to a subsequent fix.

Thoughts?
```

**Comment by AaronDonahue** [comment]
> @AaronDonahue , based on the discussion of #1086 , it caused this issue:
> 
> > @jgfouca , I wonder if we could still merge this PR now and let the new set of fails get into master? We won'tlose sight of them since they will keep popping up on CDash but at least CDash will move from showing build failures to runtime failures which will be more informative. Since very few PR's use the AT:CIME Label this shouldn't impact development but will at least let us move on from this PR to a subsequent fix.

Oh yes, now I remember that.  Sorry.  So this shouldn't hold up getting the upstream merge in because it is an unexpected fail.  I think when I first read this I thought that we somehow reverted back to pre-1086.

**Review by AaronDonahue — APPROVED** [review]
@tcclevenger , This PR will introduce 3 new fields to the atmosphere surface coupling export values.  I'm going to add them to the Confluence page so you can quickly reference them.  Just want to ping you here too so you can see the source.

**Comment by tcclevenger** [comment]
@AaronDonahue Thanks! I'll look out for it.

**Pull request merged**
