### PR TITLE
Update ekat to include new Kokkos::initialize settings

### PR DESCRIPTION
**Pull request by tcclevenger**
This incorporates the change in ekat that sets `--kokkos-num-devices=numGPUs` so that standalone tests run  efficiently with MPI and GPU combos.

I'm running CIME tests since it uses the no-argument version of `ekat_test_session()`.

### CODE REVIEW

**Review by bartgol — APPROVED** [review]

**Comment by tcclevenger** [comment]
Actually, I tested manually on mappy with `./cime/scrips/create_test e3sm_scream_v1 --compiler=gnu9` and it passes. I'll remove the CIME label since I believe that it will fail with unrelated tests.

**Comment by bartgol** [comment]
Why do you think it would fail?

**Comment by tcclevenger** [comment]
> Why do you think it would fail?

Are there not still those unrelated v0 fails?

**Comment by bartgol** [comment]
I think Jim blessed the last nightly run. Tbc, I'm ok not running v0 tests. I was just curious what fails you were talking about. :)

**Comment by tcclevenger** [comment]
@AaronDonahue Do you know what I am referring to? Or am I talking nonsense.. Were there v1-unrelated CIME test fails?

**Comment by AaronDonahue** [comment]
> @AaronDonahue Do you know what I am referring to? Or am I talking nonsense.. Were there v1-unrelated CIME test fails?

The only recent v1 Fails that we've had are DIFF's from non-BFB PR's and Jim has blessed the most recent round.  So I think we are okay.

**Comment by tcclevenger** [comment]
> > @AaronDonahue Do you know what I am referring to? Or am I talking nonsense.. Were there v1-unrelated CIME test fails?
> 
> The only recent v1 Fails that we've had are DIFF's from non-BFB PR's and Jim has blessed the most recent round. So I think we are okay.

Weren't there non-v1 tests that were also failing?

**Comment by AaronDonahue** [comment]
Yes, for the same reason.  The mass-mixing-ration PR impacted cxx and f90 code.

**Comment by tcclevenger** [comment]
Ahh ok. Then I'll keep the CIME tag just to be thorough.

**Comment by bartgol** [comment]
Looks like a comm channel interruption. Retesting.

**Comment by tcclevenger** [comment]
Thanks @bartgol

**Comment by tcclevenger** [comment]
I just manually rebased. This PR isn't stopping me currently so it's not a big deal to let it rerun.

**Comment by bartgol** [comment]
@jgfouca on mappy, v1 tests seem to pass (based on output), and yet the line `+ [[ 1 > 0 ]]` suggests that there was a fail during v1 run. Is the 'PASS' only referring to the 'run' phase but not the compare phase? If that was the case, though, I would expect to see a message informing about the DIFF... Any idea of what the fail can be?

**Comment by tcclevenger** [comment]
@jgfouca @bartgol Should this be fixed? Can't remember if I saw in the scream slack chat.. Anyways, I've added retest.

**Comment by jgfouca** [comment]
@tcclevenger , I would do an upstream merge from origin/master just to be sure.

**Comment by tcclevenger** [comment]
@bartgol or @jgfouca I think I may need another approval.

**Review by bartgol — APPROVED** [review]
Here you go.

**Pull request merged**
