### PR TITLE
Fixes an undefined variable in shoc interface

### PR DESCRIPTION
**Pull request by singhbalwinder**

### CODE REVIEW

**Review by bartgol — APPROVED** [review]

**Comment by bartgol** [comment]
@jgfouca I'm not sure what the phase `phase COMPARE_base_rest` means, and whether it can be caused by non BFB changes to the source code. The name sounds like a fail when comparing output of peLayout1 with that of peLayout2, which is odd.

@singhbalwinder was the previous pr (the wet/dry stuff in shoc) supposed to cause nonBFB diffs in v0 tests?

**Comment by AaronDonahue** [comment]
My guess is that the phrase `phase COMPARE_base_rest` is a fail when comparing restarted vs monolithic since that phrase pops up for the ERP tests.  Is that a test that changes the number of ranks?  If so then it may be due to the discussion in issue #1676 .

As for the non-BFB, I'm surprised this is not non-BFB across the board for SCREAMv0.  It looks like it only is for one of the many tests.  @singhbalwinder , any thoughts?

**Comment by singhbalwinder** [comment]
It should definitely be non-BFB for the tests which invoke SHOC, which I am assuming would include all the v0 CIME tests. I was not able to run CIME tests on Compy and Summit so far but I will try them on Cori to investigate this.

**Comment by jgfouca** [comment]
@bartgol , `COMPARE_base_rest` should not be impacted by non-bfb changes because it is not a baseline check. It is checking that a restarted run and a non-restart run produce the exact same results.

**Review by AaronDonahue — APPROVED** [review]

**Comment by AaronDonahue** [comment]
@jgfouca , I have a question before I manually merge this PR.   Do ERP tests change PE-Layout?  I know ERS doesn't, but isn't that what the "P" in the test name refers to?

**Comment by AaronDonahue** [comment]
Follow-up question, we are seeing DIFFs in the SCREAMv1 tests.  This PR shouldn't be non-BFB in v1.  I suspect this is because #1706 went in so now `master` is non-BFB with the baselines right?  Is there a way to confirm that the DIFFs we are seeing in the AT results are not due to this PR?

**Comment by AaronDonahue** [comment]
> So, yes, it looks like it uses half the PEs for one of the runs.

Okay, then these fails are probably related to issue #1676 .

**Comment by singhbalwinder** [comment]
@AaronDonahue : To find out if v1 tests are failing due to #1706 or not, I can merge master into this PR. That way, this PR will include non-BFB effects of 1706.

**Comment by AaronDonahue** [comment]
@singhbalwinder , I think that's what the AT already does.  I think the baseline comparison is against the baselines that are saved on mappy, the ones we occasionally bless after the nightlies come in.

**Comment by singhbalwinder** [comment]
Ok, thanks! That makes sense.

**Comment by bartgol** [comment]
@AaronDonahue v1 tests were passing in the second to last AT run. The fact that they fail now is probably due to something else that got merged in master between the two runs.

**Comment by singhbalwinder** [comment]
> As for the non-BFB, I'm surprised this is not non-BFB across the board for SCREAMv0. It looks like it only is for one of the many tests. @singhbalwinder , any thoughts?

Just for the record, I ran SMS test with and without shoc's wet<->dry conversion (PR #1515), and the baseline comparisons showed a FAIL as expected (i.e. adding wet<->dry conversions do change the model answers):
```
PASS SMS.ne4pg2_ne4pg2.F2010-SCREAM-LR.cori-knl_intel CREATE_NEWCASE
PASS SMS.ne4pg2_ne4pg2.F2010-SCREAM-LR.cori-knl_intel XML
PASS SMS.ne4pg2_ne4pg2.F2010-SCREAM-LR.cori-knl_intel SETUP
PASS SMS.ne4pg2_ne4pg2.F2010-SCREAM-LR.cori-knl_intel SHAREDLIB_BUILD time=39
PASS SMS.ne4pg2_ne4pg2.F2010-SCREAM-LR.cori-knl_intel NLCOMP
PASS SMS.ne4pg2_ne4pg2.F2010-SCREAM-LR.cori-knl_intel MODEL_BUILD time=141
PASS SMS.ne4pg2_ne4pg2.F2010-SCREAM-LR.cori-knl_intel SUBMIT
PASS SMS.ne4pg2_ne4pg2.F2010-SCREAM-LR.cori-knl_intel RUN time=268
FAIL SMS.ne4pg2_ne4pg2.F2010-SCREAM-LR.cori-knl_intel BASELINE shoc_wet_dry_baseline: DIFF
PASS SMS.ne4pg2_ne4pg2.F2010-SCREAM-LR.cori-knl_intel MEMCOMP
PASS SMS.ne4pg2_ne4pg2.F2010-SCREAM-LR.cori-knl_intel TPUTCOMP
PASS SMS.ne4pg2_ne4pg2.F2010-SCREAM-LR.cori-knl_intel MEMLEAK
PASS SMS.ne4pg2_ne4pg2.F2010-SCREAM-LR.cori-knl_intel SHORT_TERM_ARCHIVER
```

**Pull request merged**
