### PR TITLE
Converted prevent_ice_overdepletion to C++/Kokkos.

### PR DESCRIPTION
**Pull request by jeff-cohere**

### CODE REVIEW

**Comment by ambrad** [comment]
Improbable, but the lack of `sp(.)` in polysvp1 [here](https://github.com/E3SM-Project/scream/blob/4ced768b91b53f364806c0255007dc023ee798ce/components/scream/src/physics/p3/p3_functions_math_impl.hpp#L32) might be causing the full_sp_debug fails. In any case, that line should have `sp` around the constants.

**Comment by PeterCaldwell** [comment]
> Improbable, but the lack of `sp(.)` in polysvp1 [here](https://github.com/E3SM-Project/scream/blob/4ced768b91b53f364806c0255007dc023ee798ce/components/scream/src/physics/p3/p3_functions_math_impl.hpp#L32) might be causing the full_sp_debug fails. In any case, that line should have `sp` around the constants.

@ambrad - can you expand on this? Should all constants be sp(const)?

**Comment by ambrad** [comment]
@PeterCaldwell, yes, to get BFB in single precision builds.

**Comment by jgfouca** [comment]
@PeterCaldwell 

sp is needed around any floating point literal that is used in a computation, example:

```
Scalar bar = something;
Scalar foo = bar * 2.5;
```

In single precision, bar and foo are `float` (32-bit) but C++ always interprets non-integer literals as `double`. In order for the multiplication to happen, bar must be promoted to `double` and then the result is rounded back down to a `float` and stored in foo. In fortran (in sp builds), the literal is interpreted as a float, so the promotion and rounding down doesn't happen and therefore is not BFB with C++.

To do this correctly, use the sp macro to force C++ to interpret the literal as a float and then the computation will be BFB with fortran again:

```
Scalar bar = something;
Scalar foo = bar * sp(2.5);
```

**Comment by jgfouca** [comment]
I can get the problem to repeat on melvin; it is still a mystery to me why this PR is not BFB.

**Pull request merged**
