### PR TITLE
Update nudging to use correct wind fields `U` and `V`

### PR DESCRIPTION
**Pull request by elynnwu**
Per #2556, we conclude that `U` and `V` are the appropriate wind fields to use.

### CODE REVIEW

**Comment by bartgol** [comment]
I am reluctant to simply brush the issue under the rug, changing u to U and v to V. There clearly is something that makes u/v valid names, even though they are never used. More importantly, in #2556 you showed that while u/v are bfb with horiz_winds, and so are U/V, mixing cases causes diffs. That's not clear why, so I am not sure U/V is the solution, simply put, because I don't understand what the _real_ problem is.

That said, feel free to merge this, as it is probably ok to switch u/v to U/V. But we are not solving the problem, we are hiding it.

**Comment by elynnwu** [comment]
> I am reluctant to simply brush the issue under the rug, changing u to U and v to V. There clearly is something that makes u/v valid names, even though they are never used. More importantly, in #2556 you showed that while u/v are bfb with horiz_winds, and so are U/V, mixing cases causes diffs. That's not clear why, so I am not sure U/V is the solution, simply put, because I don't understand what the _real_ problem is.
> 
> That said, feel free to merge this, as it is probably ok to switch u/v to U/V. But we are not solving the problem, we are hiding it.

I agree. I think it can be a separate PR that actually resolves the issue, we'll keep the issue open.

**Comment by AaronDonahue** [comment]
@bartgol and @elynnwu , After some digging I found a simple explanation for why `u` and `U` both work.  Fields are stored in the field manager w/ a ekat::case_insensitive name for the `map` of fields.  Thus, when a user requests a `get_field` it doesn't matter what the case of the string is, you will get the correct pointer to the field.

Of course, then the field will be saved in the netCDF file with the wrong case, so this can lead to confusion if some users use `U` while others use `u`.

@bartgol can speak to whether or not there are places for other bugs, like when registering a field, as this PR attempts to address. Maybe we should drop the case-insensitive declaration for the field manager map of fields (?)

Note, you can verify this is true by asking for T_MID for example.  That will work too.

**Comment by bartgol** [comment]
I think I originally used CI strings because I thought we wanted to allow, e.g., both `Temperature` and `temperature`. It would be annoying to see a run crash because of a different case. That said, if we really wanted our fields to be case insensitive, we should propagate the usage of CI strings in a lot of places. In the long run, some regular std::string usage will creep up, and may cause this kind of confusion again (or, worse, some odd crash due to some string not being found).

Perhaps @PeterCaldwell may want to chime in, but personally I think it's best to remove CI strings usage from the code. I don't feel that strongly about it though, so I could go either way.

**Comment by bartgol** [comment]
> I imagine a future where folks get confused about the proper capitalization of variable names or - worse yet - try to add variables of identical spelling but different capitalization and are surprised when chaos ensues. Although maybe they would deserve it - that would be dumb.

Yes, this is a legit concern. I can foresee someone testing some sort of algorithmic mod to variable "blah", and saving its new version as "BLAH", thinking they will be two different outputs. I agree that relying on name casing is a bad habit, and as you say, such users would somewhat ask for it. Still, let's gain karma points and save them some stress.

**Comment by PeterCaldwell** [comment]
I definitely prefer U and V to u and v because the former is actually the correct name for the variables and folks might see the latter in our simulations and figure that's the right name for future simulations... which will cause failures because we're going to get rid of case insensitive behavior. 

That said, I think the Cess runs have already started and I'm not sure they have been updated to use U and V... So maybe it's too late.

**Comment by bartgol** [comment]
It may be too late for the Cess runs, but not for master. Let's stick with uppercase, as Peter said. I'll take care of removing CI strings and make everything consistent.

**Comment by elynnwu** [comment]
It sounds like we're in agreement to use uppercase `U` and `V`. Can either one of you approve this PR @bartgol @AaronDonahue?

**Review by AaronDonahue — APPROVED** [review]

**Pull request merged**
