### PR TITLE
Disable intel diagnostic messages about vectorization

### PR DESCRIPTION
**Pull request by jgfouca**

### CODE REVIEW

**Comment by jgfouca** [comment]
This seems to remove the output:

```
/ascldap/users/jgfouca/scream/components/scream/src/share/util/scream_lin_interp_impl.hpp(55): (col. 3) remark: simd loop has only one iteration
```

That I was seeing on blake.

**Comment by bartgol** [comment]
Does this also disable warnings like "loop was not vectorized"? Those are sometimes useful, and would be nice to keep them. We have a couple of those warnings in hommexx which we can't fix (and hence we ignore), but in general they can reveal flaws or areas with potential for improvement.

**Comment by jgfouca** [comment]
> Does this also disable warnings like "loop was not vectorized"? Those are sometimes useful, and would be nice to keep them. We have a couple of those warnings in hommexx which we can't fix (and hence we ignore), but in general they can reveal flaws or areas with potential for improvement.

I think it depends on if it's a warning or diagnostic message. If it's a diagnostic, then I believe so.

**Comment by ambrad** [comment]
Nice. Re: Luca's comment, what happens if you disable just "remark"? If that alone solves the problem, then I recommend disabling just that.

**Comment by jgfouca** [comment]
> Nice. Re: Luca's comment, what happens if you disable just "remark"? If that alone solves the problem, then I recommend disabling just that.

When I set pksize to 1, I get thousands of:
```
remark: simd loop has only one iteration
```
I don't see any other diags/warnings involving vectorization, and this is a "remark", so I think that would work.

**Comment by jgfouca** [comment]
Done. Seems to work.

**Comment by ambrad** [comment]
That's what I'm thinking. It has no ID, so I can't think of a way to get more specific than that.

**Pull request merged**
