### PR TITLE
bartgol/upstream merge 11 24 21

### PR DESCRIPTION
**Pull request by bartgol**
Upstream merge, mostly to bring in some changes in Homme.

There were only a couple of conflicting files. One in Homme, but picking the upstream was clearly the right thing, and one in eam's radiation.F90, for which I ended up picking always the scream version. You can see the conflicts resolution by looking at commit 4740f88ad1.

 @brhillman @oksanaguba I'm tagging you two, since you are the most knowledgeable on the files that had conflicts, and can double check I did not mess up the conflict resolution.

### CODE REVIEW

**Comment by oksanaguba** [comment]
In commit 4740f88 with resolved conflict there are 235 files. I could not figure out which files to look for and where conflicts  were.

**Comment by bartgol** [comment]
> In commit [4740f88](https://github.com/E3SM-Project/scream/commit/4740f88ad178c9cb445429d831189094d0d46677) with resolved conflicts there are 235 files. I could not figure out which files to look for and where conflicts were.

Ah, sorry, when I ran gitk on my laptop, it showed only 2 modified files:

- components/eam/src/physics/rrtmgp/radiation.F90
- components/homme/src/theta-l_kokkos/prim_driver_mod.F90

I guess those are the only two that might need a double check.

**Review by oksanaguba — APPROVED** [review]

**Comment by oksanaguba** [comment]
Thanks -- I opened 2 copies of prim_driver_mod side by side and saw nothing wrong.

**Comment by bartgol** [comment]
Unfortunately there's an undef reference link error, which is rooted in Homme. I think I'm gonna close this PR, open a fix PR in E3SM, then issue a new upstream merge.

**Pull request closed without merging**
