### PR TITLE
Fix F2000SCREAMv1 test

### PR DESCRIPTION
**Pull request by tcclevenger**
Various updates required to get the F200SCREAMv1 nightly test to run.

### CODE REVIEW

**Review by bartgol — APPROVED** [review]

**Comment by tcclevenger** [comment]
@AaronDonahue The F2000 test ran, but instead of passing if returned "DIFF"
```
15:04:29 RUNNING TESTS:
15:04:29   SMS_D_Ln2_P1x1.ne4_ne4.F2000SCREAMv1.mappy_gnu9.scream-30min_ts
15:04:29 Starting CREATE_NEWCASE for test SMS_D_Ln2_P1x1.ne4_ne4.F2000SCREAMv1.mappy_gnu9.scream-30min_ts with 1 procs
15:04:29 Finished CREATE_NEWCASE for test SMS_D_Ln2_P1x1.ne4_ne4.F2000SCREAMv1.mappy_gnu9.scream-30min_ts in 0.685153 seconds (PASS)
15:04:29 Starting XML for test SMS_D_Ln2_P1x1.ne4_ne4.F2000SCREAMv1.mappy_gnu9.scream-30min_ts with 1 procs
15:04:30 Finished XML for test SMS_D_Ln2_P1x1.ne4_ne4.F2000SCREAMv1.mappy_gnu9.scream-30min_ts in 0.140613 seconds (PASS)
15:04:30 Starting SETUP for test SMS_D_Ln2_P1x1.ne4_ne4.F2000SCREAMv1.mappy_gnu9.scream-30min_ts with 1 procs
15:04:31 Finished SETUP for test SMS_D_Ln2_P1x1.ne4_ne4.F2000SCREAMv1.mappy_gnu9.scream-30min_ts in 1.545740 seconds (PASS)
15:04:31 Starting SHAREDLIB_BUILD for test SMS_D_Ln2_P1x1.ne4_ne4.F2000SCREAMv1.mappy_gnu9.scream-30min_ts with 1 procs
15:05:08 Finished SHAREDLIB_BUILD for test SMS_D_Ln2_P1x1.ne4_ne4.F2000SCREAMv1.mappy_gnu9.scream-30min_ts in 37.017903 seconds (PASS)
15:05:08 Starting MODEL_BUILD for test SMS_D_Ln2_P1x1.ne4_ne4.F2000SCREAMv1.mappy_gnu9.scream-30min_ts with 16 procs
15:06:32 Finished MODEL_BUILD for test SMS_D_Ln2_P1x1.ne4_ne4.F2000SCREAMv1.mappy_gnu9.scream-30min_ts in 83.470337 seconds (PASS)
15:06:32 Starting RUN for test SMS_D_Ln2_P1x1.ne4_ne4.F2000SCREAMv1.mappy_gnu9.scream-30min_ts with 1 procs
15:08:48 Finished RUN for test SMS_D_Ln2_P1x1.ne4_ne4.F2000SCREAMv1.mappy_gnu9.scream-30min_ts in 136.082287 seconds (PASS). [COMPLETED 1 of 1]
15:08:48 Waiting for tests to finish
15:08:49 DIFF SMS_D_Ln2_P1x1.ne4_ne4.F2000SCREAMv1.mappy_gnu9.scream-30min_ts (phase BASELINE)
15:08:49     Case dir: /ascldap/users/e3sm-jenkins/acme/scratch/SMS_D_Ln2_P1x1.ne4_ne4.F2000SCREAMv1.mappy_gnu9.scream-30min_ts.C.20211105_150429_e2xcgi
```

**Comment by AaronDonahue** [comment]
@tcclevenger I'm pretty sure that is okay.  Mappy has baselines, I'm not sure what mappy reports if there is no baseline to compare with.  Or maybe there is a very old baseline that is still present that it is of course different from.

**Comment by AaronDonahue** [comment]
I'm comfortable merging this and then seeing what we get on CDash after we reset the baselines.  I'll give it till the end of today before merging though to allow for any comments to the contrary.

**Comment by tcclevenger** [comment]
Great, thanks Aaron. Have a good weekend.

**Pull request merged**
