### PR TITLE
Converted back_to_cell_average

### PR DESCRIPTION
**Pull request by jeff-cohere**
This one was fairly straightforward (just a bunch of multiplies to convert quantities to cell averages, no branches). Good touch typing workout.

### CODE REVIEW

**Comment by jeff-cohere** [comment]
Jim, I used a slightly simpler approach than yours to populate the testing struct with random values, because it's just a bunch of multiplications. Hope it's clear what's going on.

**Comment by jeff-cohere** [comment]
Man, I am batting zero this week!

Jim, can you remind me what kind of hardware Blake is running? I'll hop on Cori to debug the White-related issue.

**Comment by jgfouca** [comment]
@jeff-cohere , blake is intel skylake

**Comment by jeff-cohere** [comment]
Strange. I can't reproduce the bowman failures on my local Linux machine, and now Blake looks fine. I do see some trouble on Cori, however.

I'm looking at the other PR right now, but I'll circle back to this one.

**Comment by jeff-cohere** [comment]
Today I learned that C++ default constructors and CUDA don't play well out of the box!

**Comment by jeff-cohere** [comment]
Hey @jgfouca , looks like this finally passed after I merged the latest from master in. The errors I saw before that were strange and not descriptive, so maybe I should just be thankful. :-)

**Pull request merged**
