### PR TITLE
set initial pblh to zero to avoid uninitialization issue

### PR DESCRIPTION
**Pull request by xyuan**
set initial pblh to zero to avoid uninitialization issue in corresponding c++ code

[BFB]

### CODE REVIEW

**Comment by bogensch** [comment]
This is not correct.  Setting pblh to zero here will overwrite the calculation of pblh done in previous subroutine calls in "pblintd" and would have dire consequences on the model solution.  

Though I do see "pblh" is designated as "intent(out)" here when it should be "intent(inout)".

**Comment by xyuan** [comment]
> This is not correct. Setting pblh to zero here will overwrite the calculation of pblh done in previous subroutine calls in "pblintd" and would have dire consequences on the model solution.
> 
> Though I do see "pblh" is designated as "intent(out)" here when it should be "intent(inout)".

yes, it need to be intent(inout) in these subroutines. it has been changed to intent(inout)

**Comment by xyuan** [comment]
> > This is not correct. Setting pblh to zero here will overwrite the calculation of pblh done in previous subroutine calls in "pblintd" and would have dire consequences on the model solution.
> > Though I do see "pblh" is designated as "intent(out)" here when it should be "intent(inout)".
> 
> yes, it need to be intent(inout) in these subroutines. it has been changed to intent(inout)

@bogensch please review the changes, so I can move to get the porting PRs pass the autotest.

**Review by bogensch — APPROVED** [review]

**Comment by xyuan** [comment]
@jgfouca could you merge this PR? Peter has approved for the changes.

**Pull request merged**
