### PR TITLE
update p3 unit tests to include 39 instead of 37 fields for p3_main

### PR DESCRIPTION
**Pull request by AaronDonahue**
Addresses issue #90

### CODE REVIEW

**Comment by AaronDonahue** [comment]
@bartgol , I'm not sure.  I ran the unit tests locally on my machine and it builds and passes all the p3 regression tests.  I still had fails in all of the `lin_interp_ut_np1` tests but I don't think those are related to p3, or are they?

see:

```
53: Test command: /usr/bin/sh "-c" "./lin_interp"
53: Environment variables: 
53:  OMP_NUM_THREADS=16
53: Test timeout computed to be: 82800
53: sizeof(Real) 8 avx -AVX2-AVX packsize 16 compiler Intel FPE on #threads 16
53: 
53: ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
53: lin_interp is a Catch v2.2.3 host application.
53: Run with -? for options
53: 
53: -------------------------------------------------------------------------------
53: lin_interp
53: -------------------------------------------------------------------------------
53: /g/g17/donahue5/Code/e3sm/scream/scream/components/scream/src/share/tests/lin_interp_test.cpp:65
53: ...............................................................................
53: 
53: /g/g17/donahue5/Code/e3sm/scream/scream/components/scream/src/share/tests/lin_interp_test.cpp:65: FAILED:
53: due to a fatal error condition:
53:   SIGFPE - Floating point error signal
53: 
53: ===============================================================================
53: test cases: 1 | 1 failed
53: assertions: 1 | 1 failed
53: 
53: [quartz2300:mpi_rank_0][error_sighandler] Caught error: Floating point exception (signal 8)
53/74 Test #53: lin_interp_ut_np1_omp16 ..........***Exception: Numerical  0.23 sec
```

**Comment by AaronDonahue** [comment]
that could also be a fail just due to my machine

**Comment by bartgol** [comment]
I think @jgfouca wrote the lin interp code.

**Comment by bartgol** [comment]
But tests pass on travis, so it might be your machine.

**Comment by bartgol** [comment]
Hold on. it fails on my machine too.

**Comment by AaronDonahue** [comment]
have you remade the baselines?

**Comment by ambrad** [comment]
@jgfouca the lin-interp FPE reported above should be looked at once you're working on scream again. it may be unavoidable with SCREAM_PACK_SIZE=16, but that should be checked and confirmed.

**Comment by jgfouca** [comment]
@ambrad , I don't think FPE should be enabled if PACK_SIZE > 1.

```
if (CMAKE_BUILD_TYPE_ci STREQUAL "debug")
  set(DEFAULT_FPMODEL "strict")
  if (${SCREAM_PACK_SIZE} EQUAL 1 AND NOT ${CUDA_BUILD})
    set(DEFAULT_FPE TRUE)
  endif ()
endif()
```

**Comment by ambrad** [comment]
True, but I think Aaron (and me, too) turned it on explicitly.

**Comment by ambrad** [comment]
Jim and I talked about this issue a while ago. We decided it's not wise to spend time chasing FPEs when vectorization (SCREAM_PACK_SIZE > 1) is enabled. FPEs occur in the unused part of the vector pack. Avoiding them explicitly requires nonperformant changes to the code. Thus, when doing final testing, either run with SCREAM_PACK_SIZE=1 and SCREAM_FPE=ON, or run with SCREAM_FPE=OFF.

**Comment by bartgol** [comment]
> Thus, when doing final testing, either run with SCREAM_PACK_SIZE=1 and SCREAM_FPE=ON, or run with SCREAM_FPE=OFF.

I would suggest doing both. They both add value (either FPEs or packs)

**Comment by AaronDonahue** [comment]
ok, the two FPE options worked for me so I am going to merge

**Pull request merged**
