### PR TITLE
Hooking up homme

### PR DESCRIPTION
**Pull request by bartgol**
This PR sets up the structure for hooking up homme to scream.

There were some issues related to the fact that homme requires configure-time variables/macros to be defined in order to be compiled. This forced to abandon the strategy of a once-and-for-all compiled dynamics library (like we do for `scream_share`, for instance). Instead, now we compile the dynamics library just-in-time for the executable. We can probably find a way to pre-compile the dynamics library for a bunch of values of homme's configure time option, which would help with compilation time, if there are 2+ tests that use the same configuration. This can be done in a second time, I think. This PR mainly deals with bringing homme in.

Note: this work required to edit some of homme's cmake logic. Not much (mainly not defining the project if already defined, and using `HOMME_[SOURCE|BINARY]_DIR` instead of `CMAKE_[SOURCE|BINARY]_DIR`), but it may cause some issues next time we merge upstream e3sm into scream. At some point it may end up being easier to port the modifications inside e3sm.

### CODE REVIEW

**Comment by ambrad** [comment]
Wasn't clear if you're ready for a review yet, but an initial config gives:
```
CMake Error at src/dynamics/CMakeLists.txt:5 (MESSAGE):
  The dynamics dycore '' is currently not supported.
```

**Comment by ambrad** [comment]
Also consider the long-term merge conflict hazard of making changes to Homme cmake stuff in scream rather than in E3SM.

**Comment by bartgol** [comment]
Ah, yeah, I added some mandatory cmake options. I can put some defaults, so that things should build smoothly.

**Comment by ambrad** [comment]
Defaults should be such that Homme isn't brought in.

**Comment by bartgol** [comment]
Yeah, that's why I thought about putting it in e3sm. I guess I can take the commit and replicate in e3sm, then put up a PR in there. The reason why I didn't is that e3sm right now does not have a use of a cmake build of homme that is not standalone. But I guess e3sm does not _need_ standalone homme either, so I can just do it.

**Comment by bartgol** [comment]
> Defaults should be such that Homme isn't brought in.

Well, if you don't want homme to be brought in by default, that's what's happening now. Scream needs some sort of dynamics dycore to operate. We either throw an error if none is specified, or we use a default one (homme seems the most reasonable, at least for now).

**Comment by ambrad** [comment]
For clarity: Right now, standalone scream is intended to test P3 and SHOC without bringing in a lot of E3SM. These don't require a dycore. We also want standalone scream to unit test coupler capabilities; some of this testing does require a dycore. The default should be to build without a dycore (as master currently does) and turn off the coupler tests that require a dycore.

**Comment by bartgol** [comment]
Uhm, ok, I guess I can allow that use easily.

**Comment by ambrad** [comment]
@bartgol please ping me when you're ready for me to look at this again; thanks.

**Comment by bartgol** [comment]
@ambrad , I think this is ready. I may port the changes in Homme's cmake build to e3sm too, but I can take care of the upstream merge after that, so that the burden of solving conflicts does not fall on anyone else. Meanwhile, I think we can proceed with having the mods inside the scream fork.

**Pull request merged**
