### PR TITLE
For integer types storing sizes in bytes, use size_t

### PR DESCRIPTION
**Pull request by ndkeen**
For ne30 cases, some integers were overflowing. Using size_t can help.

Fixes https://github.com/E3SM-Project/scream/issues/1492

### CODE REVIEW

**Comment by PeterCaldwell** [comment]
This is great, thanks Noel! It looks like you've went through the whole v1 code and found all the places where ints were being used as buffer size, then changed them into sizeT types. This is exactly what I was hoping someone would do. I think when we first talked about this, someone (Luca) was saying we should only make this change in cases where we knew overflow would occur, but I think we should do this everywhere because who knows what resolution we will move to in the future and because the error messages we get when things go wrong are very hard to track down...

My one question is - how confident are you that you found all the cases of using int32 to set memory buffer size?

**Review by jgfouca — APPROVED** [review]
Looks good. Can we use the compiler to help us find narrowing conversions?

**Comment by PeterCaldwell** [comment]
"Can we use the compiler to help us find narrowing conversions?" - can you expand on this, @jgfouca ? I'm not sure how I'd do this...

**Comment by jgfouca** [comment]
@PeterCaldwell , I'm concerned that this type of problem will be common in the code:

```
int var_with_wrong_type = api_that_returns_size_t();
```

So, even though the API is set to use the correct type, the clients will continue to use the wrong type and the compiler will not catch this mistake. I just wrote a small test program and even `-Wall` does not catch this.

**Comment by jgfouca** [comment]
Ok, it looks like `-Wconversion` does what we want, at least for clang:

```
clang++ -Wconversion testNarrowingConversion.cc
testNarrowingConversion.cc:12:13: warning: implicit conversion loses integer precision: 'size_t' (aka 'unsigned long') to 'int' [-Wshorten-64-to-32]
  int foo = my_api();
      ~~~   ^~~~~~~~
```

We probably have a crazy number of conversion warnings in our code, so we'd have to be clever in how we used this warning. Maybe modify the API header and recompile with the warning on.

**Comment by ndkeen** [comment]
afaik, there isn't a compiler flag to detect overflow, but I'm testing the use of a gnu-specific pragma

**Comment by PeterCaldwell** [comment]
@jgfouca - it's not really the narrowing conversion that's the problem, right? It's that the narrowing conversion doesn't bother to complain when it can't squeeze the sizeT integer into the int32 it's asked to. For example, the narrowing isn't a problem with ne4 because ne4 data volumes are small enough to fit into int32... 

Are you suggesting we look for narrowing conversions because they are easier to ask the compiler to to than to catch overflows like Noel is attempting?

**Comment by PeterCaldwell** [comment]
Ok. I'm inclined to merge this PR and to keep issue #1492 open (or create a more pointed issue) while we try to figure out whether there are any other instances we missed here.

**Review by PeterCaldwell — APPROVED** [review]
just re-approving after fixing merge conflicts.

**Comment by ndkeen** [comment]
With todays master after upstream merge (March 23), which does NOT have these particular `size_t` changes, I am able to run ne30 (at least with 4 nodes and 16 MPI's).  So that indicates we may not need these changes for ne30 and I'm now wondering why the branch I had been working in seemed to require this change. I still think these (or similar) changes are a step in the right direction.

**Pull request merged**
