### PR TITLE
Better handling of Kokkos_ENABLE_Debug

### LINKED ISSUE #445: View bounds error on Compy
@pressel and I got this error on Compy with both GCC and Intel compilers. The error is:
```
ExecSpace name: OpenMP
ExecSpace initialized: yes
sizeof(Real) 8 avx -AVX512F-AVX2-AVX compiler Intel FPE off #threads 4
terminate called after throwing an instance of 'std::runtime_error'
  what():  View bounds error of view  ( -1 < 80 )
Traceback functionality not available
```
I get this error if I run `p3_tests`( `shoc_tests` runs fine)

I used totalview and here are my findings (which may not be that useful):

The failure always seem to occur differently. I am noting here the consistent behavior. During p3_tests, failure occurs in the call to run_bfb_p3_main  which then calls P3F::p3_main. The code dies just calling this function while working on the arguments. That is, it doesn’t actually goes into p3_main function. While working on the arguments, it calls the following function in Kokkos_View.hpp :
```
template< class RT , class ... RP >
  KOKKOS_INLINE_FUNCTION
  View( const View<RT,RP...> & rhs )
    : m_track( rhs.m_track , traits::is_managed )
    , m_map()
    {
      typedef typename View<RT,RP...>::traits  SrcTraits ;
      typedef Kokkos::Impl::ViewMapping< traits , SrcTraits , typename traits::specialize >  Mapping ;
      static_assert( Mapping::is_assignable , "Incompatible View copy construction" );
      Mapping::assign( m_map , rhs.m_map , rhs.m_track );
    }
```
The above function is called twice and the code dies after the second call. It seems to take different routes after this, if I run it again and again. 

[Here](https://gist.github.com/singhbalwinder/1fdfc6021a6d316b06ae32dd8340d8b5) is a gist file which has the trace from gdb (thanks @ambrad !)

### PR DESCRIPTION
**Pull request by jgfouca**
The variable was not being referred to by the correct name in Kokkos.cmake.
Also, this setting did not belong in the machine files since both release and
debug builds are valid for any machine. Instead, we allow the user to select
Kokkos_ENABLE_Debug explicitly; if they do not, then we select a default based
on the build type.

Fixes #445

### CODE REVIEW

**Comment by jgfouca** [comment]
With some quick testing on melvin, this appears to work as intended. If build type is debug, then Kokkos is built in debug mode, regardless of what's in the machine file. If it's built in release, then it respects what's in the machine file.

**Comment by bartgol** [comment]
Uhm, this, however, prevents the user from manually forcing kokkos debug=false in a debug build. Are we ok with that? Meaning, are we ok forcing Kokkos DEBUG to ON in debug builds, regardless of what the user may want?

If we are ok with that, then why not setting KOKKOS_ENABLE_DEBUG to ON if and only if CMAKE_BUILD_TYPE is debug? Meaning, set it to OFF in a release build?

At this point, we may as well hide the KOKKOS_ENABLE_DEBUG option from the user altogether, and handle it internally in scream. That is, *if* we are ok not giving the user the possibility of manually turn it on/off at will.

**Comment by bartgol** [comment]
Also, I don't think `Kokkos_ENABLE_Debug` has any effect. Grepping it in the kokkos submodule doesn't return anything, unlike `KOKKOS_ENABLE_DEBUG`.

**Comment by jgfouca** [comment]
@bartgol , that's right. I'm not actually sure why we put Kokkos_ENABLE_Debug in the machine files in the first place.

**Comment by jgfouca** [comment]
@bartgol , I'm pretty sure it has the effect we want:

```
-- ****************** Kokkos Settings ******************
-- Execution Spaces
--   Device Parallel: None
--     Host Parallel: OpenMP
--       Host Serial: Serial
-- 
-- Architectures:
--     None
-- 
-- Enabled options
--   KOKKOS_ENABLE_SERIAL
--   KOKKOS_ENABLE_OPENMP
--   KOKKOS_ENABLE_LIBRT
--   KOKKOS_ENABLE_DEBUG
--   KOKKOS_ENABLE_PROFILING
--   KOKKOS_ENABLE_AGGRESSIVE_VECTORIZATION
-- 
-- Final kokkos settings variable:
--   env;KOKKOS_CMAKE=yes;KOKKOS_SRC_PATH=/home/jgfouca/scream/externals/kokkos;KOKKOS_PATH=/home/jgfouca/scream/externals/kokkos;KOKKOS_INSTALL_PATH=/usr/local;KOKKOS_ARCH=None;KOKKOS_DEVICES=OpenMP,Serial;KOKKOS_DEBUG=yes;KOKKOS_OPTIONS=aggressive_vectorization,disable_deprecated_code,disable_dualview_modify_check;KOKKOS_USE_TPLS=librt;KOKKOS_CXX_STANDARD="c++11"
```

**Comment by jgfouca** [comment]
An approach that would make more sense to me is to remove Kokkos_ENABLE_Debug from the machine files and instead process it in our main CMakeLists.txt file. It should prefer any explicit setting from the user. If the user didn't provide one, then it will be set based on the build type (debug->enable_debug, otherwise disable).

**Comment by jgfouca** [comment]
Your grep is likely missing some kind of generic "forwards-compatibility" layer.

**Comment by bartgol** [comment]
Ah, yeah, this is why:

```
foreach(opt ${KOKKOS_INTERNAL_ENABLE_OPTIONS_LIST})
  string(TOUPPER ${opt} OPT )
  IF(DEFINED Kokkos_ENABLE_${opt})
    IF(DEFINED KOKKOS_ENABLE_${OPT})
      IF(NOT ("${KOKKOS_ENABLE_${OPT}}" STREQUAL "${Kokkos_ENABLE_${opt}}"))
        IF(DEFINED KOKKOS_ENABLE_${OPT}_INTERNAL)
          MESSAGE(WARNING  "Defined both Kokkos_ENABLE_${opt}=[${Kokkos_ENABLE_${opt}}] and KOKKOS_ENABLE_${OPT}=[${KOKKOS_ENABLE_${OPT}}] and they differ! Could be caused by old CMakeCache Variable. Run CMake again and warning should disappear. If not you are truly setting both variables.")
          IF(NOT ("${Kokkos_ENABLE_${opt}}" STREQUAL "${KOKKOS_ENABLE_${OPT}_INTERNAL}"))
            UNSET(KOKKOS_ENABLE_${OPT} CACHE)
            SET(KOKKOS_ENABLE_${OPT} ${Kokkos_ENABLE_${opt}})
            MESSAGE(WARNING "SET BOTH VARIABLES KOKKOS_ENABLE_${OPT}: ${KOKKOS_ENABLE_${OPT}}")
          ELSE()
            SET(Kokkos_ENABLE_${opt} ${KOKKOS_ENABLE_${OPT}})
          ENDIF()
        ELSE()
          MESSAGE(FATAL_ERROR "Defined both Kokkos_ENABLE_${opt}=[${Kokkos_ENABLE_${opt}}] and KOKKOS_ENABLE_${OPT}=[${KOKKOS_ENABLE_${OPT}}] and they differ!")
        ENDIF()
      ENDIF()
    ELSE()
      SET(KOKKOS_INTERNAL_ENABLE_${OPT}_DEFAULT ${Kokkos_ENABLE_${opt}})
    ENDIF()
  ENDIF()
endforeach()
```

Kokkos handles both `Kokkos_` and `KOKKOS_`, as well as `Debug` and `DEBUG`, when dealing with cmake options.

I think, however, that we should use always the same cmake vars casing for kokkos. In our mach files we have some `Kokkos` and some `KOKKOS`. It'd be nice to stick with one (I don't care which one).

**Comment by jgfouca** [comment]
@bartgol and I talked this out on the side and came up with a better solution.

**Comment by jgfouca** [comment]
Testing results:
Debug build type, no explicit setting from user => Kokkos debug is ON
Debug build type, but explicitly disable by user => Kokkos debug is OFF
Release build type, no explicit setting from user => Kokkos debug is OFF
Release build type, but explicitly enabled by user => Kokkos debug is ON

**Comment by jgfouca** [comment]
@bartgol , I have to make some changes to test-all-scream to get it to work for me. pathlib.resolve() raises an exception if the file doesn't exist, so i had to switch some of those calls to absolute().

Having Kokkos-debug=on uncovered a problem with rain_sedimentation where negative indices were being used in some cases. I have fixed that.

I also took the opportunity to reduce the number of workspaces requested by p3_main to the high-water (42) instead of my initial guess of 100.

**Comment by PeterCaldwell** [comment]
> Having Kokkos-debug=on uncovered a problem with rain_sedimentation where negative indices were being used in some cases. I have fixed that.

Hey @jgfouca - could you expand on this a bit? Was this affecting answers? Did it affect the F90 version as well? I'm surprised our unit tests didn't catch this...

**Comment by jgfouca** [comment]
@PeterCaldwell , I answered your question in the commit message, but I should have changed the PR description:

```
Fix <0 indexing on sflux_qx

It was technically harmless since the result was being
masked-out, but it was causing kokkos to raise errors if
kokkos debug was on.
```

**Pull request merged**
