### PR TITLE
Adds functionality to call fortran subroutine for vertflux property test

### PR DESCRIPTION
**Pull request by singhbalwinder**
Adds boiler-plate C++ code to call fortran function `calc_shoc_vertflux`. Fortran subroutine is called from the property test written by @bogensch. I followed the @pressel code to call the Fortran subroutine from this property test.

This property test tests `calc_shoc_vertflux` for the following properties:
1. Reasonable inputs
2. Validates down gradient assumption for various possible layers  (conditionally stable layer, well mixed layer, unstable layer)

### CODE REVIEW

**Comment by singhbalwinder** [comment]
This PR is still WIP. All the code is there but I need to make some minor changes to the property test so that it accepts 2nd column input and I also need to set bounds for checking the subroutine output in the property test.

@bogensch : Please feel free to change the PR description. 
@pressel : Thanks a lot for setting the first test, I pretty much followed your code to make this work.

**Comment by pressel** [comment]
@singhbalwinder This is looking good to me!

**Comment by PeterCaldwell** [comment]
As a heads-up, Peter B is on vacation until Thurs. He should approve, so this PR probably won't be merged before that.

**Comment by singhbalwinder** [comment]
Thanks @bogensch for fixing this test. I also would like to mention that initially you had `shcol=2`. I changed it to 1, so that I can debug these test failures. Would you like to revert it to 2?

**Comment by bogensch** [comment]
Yes, I think reverting it to 2 would be good.  Thanks.

**Comment by bogensch** [comment]
@singhbalwinder okay, I see once I switch to shcol = 2 the tests fail again.  I will look into this.

**Comment by bogensch** [comment]
@singhbalwinder issue found.  All systems should be good now, thanks for bringing this to my attention.

**Comment by singhbalwinder** [comment]
Thats great! Thanks @bogensch ! 

I will let the AT run once more to see if it passes all the tests. I still need to add/remove some comments and do some cleanup.

**Comment by singhbalwinder** [comment]
This is now ready to merge.

**Comment by jgfouca** [comment]
@singhbalwinder , i've tagged this PR as automerge. Once the white fix is on master, upstream merge or rebase this branch. Tests should then pass and it will automerge.

**Pull request merged**
