### PR TITLE
Have dynamic expose omega as a computed field

### PR DESCRIPTION
**Pull request by bartgol**
Also build a single version of the dyn library for all our unit tests, with qsize_d=10 (before we built one with qsize_d=35 and one with qsize_d=4).

### CODE REVIEW

**Review by AaronDonahue — APPROVED** [review]
Looks good!  Thanks for getting on the fix so quickly Luca.  I'm approving, but I a question comes to mind.  Did you test that with these changes SHOC gets different results?  I suppose we will see that by expecting SCREAMv1 tests to be non-BFB...

**Comment by bartgol** [comment]
> Looks good! Thanks for getting on the fix so quickly Luca. I'm approving, but I a question comes to mind. Did you test that with these changes SHOC gets different results? I suppose we will see that by expecting SCREAMv1 tests to be non-BFB...

Yes, and I have some issues with what I saw. First, I manually removed omega from the input file, and verified the dyn+physics test still passes, so I'm confident that SHOC is indeed using the omega field produced by dynamics (rather than relying on the input file). Then I cprnc-ed the output with current master, and found 40 fields differ.

Some fields that differ are the spa fields, which I thought were "inputs", but I guess we save them after interpolation on the vert grid, which could be affected by using a different omega.

**Comment by PeterCaldwell** [comment]
> Some fields that differ are the spa fields, which I thought were "inputs", but I guess we save them after interpolation on the vert grid, which could be affected by using a different omega.

spa reads in variables on pressure levels, then interpolates them to the model grid. So any non-bfb change would change them, right? I don't think the issue is specific to omega (since vert interp doesn't care about omega)...

**Comment by AaronDonahue** [comment]
@bartgol , I'm confused why this didn't fail the mappy tests with DIFF in the SCREAMv1 tests.  Doesn't adding the `SCREAMv1` label cause the CIME tests to be run?

**Comment by bartgol** [comment]
> > Some fields that differ are the spa fields, which I thought were "inputs", but I guess we save them after interpolation on the vert grid, which could be affected by using a different omega.
> 
> spa reads in variables on pressure levels, then interpolates them to the model grid. So any non-bfb change would change them, right? I don't think the issue is specific to omega (since vert interp doesn't care about omega)...

But different omega will lead to changes in SHOC output, which will change Homme forcing, which will change dp... So I think we can expect the change in omega to impact spa output too. At least after 2 timesteps.

**Comment by PeterCaldwell** [comment]
> But different omega will lead to changes in SHOC output, which will change Homme forcing, which will change dp... So I think we can expect the change in omega to impact spa output too. At least after 2 timesteps.

Yeah, I totally agree. That's what I was trying to say...

**Comment by PeterCaldwell** [comment]
> @bartgol , I'm confused why this didn't fail the mappy tests with DIFF in the SCREAMv1 tests. Doesn't adding the SCREAMv1 label cause the CIME tests to be run?

I agree with Aaron - I think we didn't expect this to be BFB but it was because we didn't pass the CIME flag. This is a bit weird...

**Pull request merged**
