### PR TITLE
RRM glue and test

### PR DESCRIPTION
**Pull request by ambrad**
EAMxx build glue and settings for a test RRM compset.

### CODE REVIEW

**Comment by ambrad** [comment]
Upstream PR https://github.com/E3SM-Project/E3SM/pull/5426 is further glue.

**Review by bartgol — DISMISSED** [review]
This PR is surprisingly small. Almost a free lunch.

**Comment by ambrad** [comment]
> This PR is surprisingly small. Almost a free lunch.

Nom nom. But most of the work was in https://github.com/E3SM-Project/E3SM/pull/5395. Fortunately, our guess was correct that the EAMxx AD was almost, and now is, entirely indifferent to the grid type.

**Comment by ambrad** [comment]
@bartgol would you re-approve? I added a nightly ERP test. It runs on one node of Chrys in a few minutes, so it should be a good addition to the midres_v1 set and protect the RRM capability.

**Comment by AaronDonahue** [comment]
@bartgol , pinging you to re-approve

**Review by bartgol — APPROVED** [review]

**Comment by bartgol** [comment]
Sorry, I missed this last week...

**Pull request merged**
