### PR TITLE
Allow to pass a Comm to field utils, to perform global operations

### PR DESCRIPTION
**Pull request by bartgol**
This allows to get global checks on field entries.

### CODE REVIEW

**Comment by AaronDonahue** [comment]
@bartgol , does this just need a merge of master and a retest?  It looks like a pretty straightforward PR that could go in sooner than later.

**Comment by bartgol** [comment]
> @bartgol , does this just need a merge of master and a retest? It looks like a pretty straightforward PR that could go in sooner than later.

No, the fails are likely unrelated to master mods. The master merge performed by the test scripts is going through, so it must be a legit fail.

**Comment by AaronDonahue** [comment]
@brhillman , when you get a chance can you review this PR, it looks like it passed the AT so it should be ready to go in.

**Review by brhillman — APPROVED** [review]
Looks good to me.

**Pull request merged**
