### PR TITLE
update ekat 

### PR DESCRIPTION
**Pull request by tcclevenger**
Update ekat so that `ekat::erf()` can be used.

### CODE REVIEW

**Comment by bartgol** [comment]
Can we wait a few hrs so that we might get in also E3SM-Project/EKAT#70 ?

**Comment by tcclevenger** [comment]
@bartgol Absolutely. There is no time crunch on my end.

**Comment by tcclevenger** [comment]
Will wait for https://github.com/E3SM-Project/EKAT/pull/70 to be merged, then I will update this PR and run tests.

**Comment by bartgol** [comment]
@tcclevenger the pr I mentioned just went in. You can amend+force-push if you want (or if you don't like the dark side of the force push, make it a new commit), and then we can test/merge.

**Review by bartgol — APPROVED** [review]

**Pull request merged**
