### PR TITLE
Add configuration for ne256np4_oRRS18to6v3 v0 grid

### PR DESCRIPTION
**Pull request by brhillman**
Add configuration for ne256np4 bigrid with oRRS16to6v3 ocean/ice grid for SCREAMv0. Note that this currently needs an increase on the tolerance of `EPS_AGRID=1e-9`.

[B4B]

### CODE REVIEW

**Comment by PeterCaldwell** [comment]
What is the physical meaning of eps_agrid?

**Comment by brhillman** [comment]
> What is the physical meaning of eps_agrid?

It’s the tolerance on the atm grid coordinate check. I think the check is to see if the coordinates from the initial condition match the coordinates from the domain file mapped back to the atmosphere grid? I’m not 100% sure. @wlin7 probably knows more.

**Comment by brhillman** [comment]
I think the need for larger eps_agrid is due to a known issue: https://github.com/E3SM-Project/E3SM/issues/4437

**Review by ndkeen — APPROVED** [review]
Would need to test to make comment

**Pull request merged**
