### PR TITLE
Fast forwarding EKAT to latest version (Kokkos 3.6).

### PR DESCRIPTION
**Pull request by jeff-cohere**
This PR fast-forwards EKAT once again to provide Kokkos v3.6 (bumped from v3.5). @sarats is curious to see whether this new Kokkos version improves performance on AMD GPUs.

### CODE REVIEW

**Comment by sarats** [comment]
Thanks, I can run some tests on a Frontier testbed.

**Comment by PeterCaldwell** [comment]
@sarats and @jgfouca - should we integrate this? Just asking so we don't have PRs sitting around forever.

**Comment by sarats** [comment]
I need some time to test this out, haven't had a chance given other things that cropped up.

**Comment by sarats** [comment]
And you most probably shouldn't merge this into master until we get all INCITE benchmarking is done.

**Comment by sarats** [comment]
On a related note, this branch should be tested on Summit along with recent compiler + CUDA combinations so that we can move away from the old modules we are currently stuck with. Of course, not needed for INCITE but an independent task for someone with spare cycles.

**Comment by oksanaguba** [comment]
You guys told me to test new ekat a few days ago, results are below, but someone needs to redo them eventually:
```
FROZE in atn init
gcc/9.3.0 cuda/11.5.2

RAN
cuda/10.1.243  gcc/7.5.0

RAN
gcc-9.1.0  cuda/11.0.3
```

**Comment by jeff-cohere** [comment]
@ndkeen has asked me to provide these changes in a branch with the latest changes from `master`. I could just rebase this branch against the latest changes. Anyone opposed to this? @sarats @PeterCaldwell

**Comment by sarats** [comment]
I'm fine with rebasing from current master.

Before merging into master, someone needs to test this on Summit with either the known good modules (old) or some combination of new compiler+CUDA. Just making sure we have a working configuration on Summit with master at all times.

**Comment by jeff-cohere** [comment]
Noel is concerned about the recent upstream merge and how it might interact with Kokkos. I suppose that's one reason to rebase against `master` before merging--if something were to fail after the rebase, we could address it in this branch.

**Comment by jeff-cohere** [comment]
Okay, I'll rebase. Stand by.

**Comment by jeff-cohere** [comment]
Mappy is not happy. @jgfouca , would you mind taking a look at Mappy's logs to see whether this is an actual test failure or just an AT burp?

**Comment by jgfouca** [comment]
@jeff-cohere , no mappy tests failed, just a couple of DIFFs that are known (change in fields). Merging.

**Pull request merged**
