### PR TITLE
Add default IC for ne120 with 128 vertical levels

### PR DESCRIPTION
**Pull request by brhillman**
Add default initial condition for ne120 with 128 vertical levels. This can be ran the same way as ne30 L128 by using the testmod scream-L128, which changes SCREAM_NUM_VERTICAL_LEV.

[B4B]

### CODE REVIEW

**Comment by ndkeen** [comment]
Why can't 128 levels be the default?

**Comment by brhillman** [comment]
It can be, and then we could make exceptions for the cases we want L72 (i.e., I think we use ne4pg2 L72 for testing). I don't really feel strongly either way, but can easily add that to this PR.

**Review by ndkeen — APPROVED** [review]
I tested ne120pg2_ne120pg2 using 128 levels and the current default 72 levels. Both completed 1 month on pm-gpu. With 32 nodes, the SYPD was 6.5 for 72 levels and 4.5 with 128 levels.

**Comment by brhillman** [comment]
I'm going to let this merge as-is and we can make a separate PR to change the default for all resolutions to use L128.

**Comment by ndkeen** [comment]
Fixes #2173

**Pull request merged**
