### PR TITLE
Jgfouca/upstream merge 2023 04 11

### PR DESCRIPTION
**Pull request by jgfouca**
No conflicts!

This PR brings in the Adios stuff that I think some of us were waiting for in scream.

### CODE REVIEW

**Comment by AaronDonahue** [comment]
just as a sanity check, there won't be any issue merging this at the same time we have https://github.com/E3SM-Project/E3SM/pull/5582 open on the E3SM side right?

**Review by AaronDonahue — APPROVED** [review]

**Comment by jgfouca** [comment]
@AaronDonahue , nope. Git is really good at doing merges.

**Comment by jgfouca** [comment]
@brhillman , @AaronDonahue , the CIME tests have some DIFFs and NLFAILs (namelist diffs), which I'm not really worried about. One thing I noticed when testing this by hand is that the test `ERS_Ln90.ne30pg2_ne30pg2.F2010-SCREAMv1.mappy_gnu9.scream-small_kernels` FAILs during base/rest internal comparison. In other words, the ERS test failed to produce the same results when doing a restart. I'm getting deja vu that we've seen this issue before but I can't remember the details. I was hoping one of you would remember. I checked out the parent commit and confirmed that this PR does cause the problem.

If you guys have no idea, I can try doing a bisection on E3SM to see when this problem was introduced.

**Comment by brhillman** [comment]
Is that the only test that fails base/rest compare?

**Comment by jgfouca** [comment]
@brhillman , yes, out of the tests in e3sm_scream_v1 which has several ERS and ERP tests.

**Comment by jgfouca** [comment]
I doubled checked this PR and the ERS/PEM issues I saw are identical to what we are seeing on master.

```
FAIL ERS_Ln22.ne30_ne30.F2010-SCREAMv1.mappy_gnu9 (phase COMPARE_base_rest)
    Case dir: /ascldap/users/jgfouca/acme/scratch/ERS_Ln22.ne30_ne30.F2010-SCREAMv1.mappy_gnu9.20230420_091618_o89rnb
PASS ERS_Ln90.ne30pg2_ne30pg2.F2010-SCREAMv1.mappy_gnu9.scream-small_kernels RUN
    Case dir: /ascldap/users/jgfouca/acme/scratch/ERS_Ln90.ne30pg2_ne30pg2.F2010-SCREAMv1.mappy_gnu9.scream-small_kernels.20230420_091618_o89rnb
PASS PEM_Ln90.ne30pg2_ne30pg2.F2010-SCREAMv1.mappy_gnu9 RUN
    Case dir: /ascldap/users/jgfouca/acme/scratch/PEM_Ln90.ne30pg2_ne30pg2.F2010-SCREAMv1.mappy_gnu9.20230420_091618_o89rnb
```

Rerun:
```
PASS ERS_Ln22.ne30_ne30.F2010-SCREAMv1.mappy_gnu9 RUN
    Case dir: /ascldap/users/jgfouca/acme/scratch/ERS_Ln22.ne30_ne30.F2010-SCREAMv1.mappy_gnu9.20230420_101925_g0gu3v
```

**Pull request merged**
