### PR TITLE
port diag_third_shoc_moments

### PR DESCRIPTION
**Pull request by tcclevenger**
Port `diag_third_shoc_moments`.

`qw_sec`, `qwthl_sec`and `wthv_sec` are unused variables.

### CODE REVIEW

**Comment by tcclevenger** [comment]
@bartgol Mappy here is failing, and the tests which fail are different each time. E.g., `shoc_tests_ut_np1_omp7/8/11/15` failed and then `shoc_tests_ut_np1_omp6/7/9/14` fail on a retest with no code changes. Have you been seeing this?

**Comment by bartgol** [comment]
> @bartgol Mappy here is failing, and the tests which fail are different each time. E.g., `shoc_tests_ut_np1_omp7/8/11/15` failed and then `shoc_tests_ut_np1_omp6/7/9/14` fail on a retest with no code changes. Have you been seeing this?

No, I haven't. The best thing to do is to manually get on mappy and run tests, until the issue is found. Do you have access to mappy? If not, contact @jgfouca .

**Review by jeff-cohere — APPROVED** [review]
Looks good! I assume the barriers you put in there are needed?

**Comment by tcclevenger** [comment]
> Looks good! I assume the barriers you put in there are needed?

@jeff-cohere Yes, not having the 2nd barrier was the cause of of one specific mappy test not passing.

**Pull request merged**
