### PR TITLE
Remove host copy of uninitialized device memory

### PR DESCRIPTION
**Pull request by tcclevenger**
Should fix [scream_unit_tests_compute_santizer_initcheck](https://my.cdash.org/build/2347016) fails. Two issue:
1. We were requesting host copy of uninitialized device array in YAKL. We only need the host object, that we read values into from netcdf file, and then we deep copy back to device.
2. `rrtmgp_standalone_unit` test allocated an array that was unset. Uninitialized memory read occurred when copying to new array.

### CODE REVIEW

**Review by jgfouca — APPROVED** [review]
Nice! Does this change actually fix a bug or does it just make compute-sanitizer happy?

**Comment by tcclevenger** [comment]
Yeah, I guess its not actually a bug. Just makes compute sanitizer happy. I'll remove the label.

**Comment by tcclevenger** [comment]
@jgfouca Found another initcheck fail. Manually tested the rest so I think this should be the last one.

**Comment by jgfouca** [comment]
@tcclevenger , my previous comment was not so much about the label; i'm trying to figure out if the things sanitizer is catching are useful.

**Review by jgfouca — APPROVED** [review]

**Pull request merged**
