### PR TITLE
Jgfouca/upstream merge 2021 01 15

### PR DESCRIPTION
**Pull request by jgfouca**
This was a rough one and I will need help. First are the conflicts I was confident enough to solve, here is a log of those:

```
both modified: components/eam/bld/namelist_files/namelist_defaults_cam.xml

Soln: take both, adds a bunch of hypervis_scaling dyn_target="preqx" settings around line 1743

both modified: components/eam/cime_config/config_component.xml

Soln: take upstream, CAM_TARGET default is always theta-l, that's what we were using for SCREAM anyway

both modified: components/eam/src/physics/rrtmg/radiation.F90

Soln: take usptream, looks like whitespace change and addition of flag_xyfill at line 607

both modified: components/eam/src/physics/rrtmgp/radiation.F90

Soln: take usptream, looks like whitespace changes and addition of flag_xyfill for a few calls lines 694-710

both modified: components/elm/src/cpl/lnd_comp_mct.F90

Soln: take upstream, removes iop mode and changes 'clm' to 'elm', lines 45-50 and 230

both modified: components/elm/src/main/elm_varctl.F90

Soln: take upstream, removes iop mode and changes 'clm' to 'elm', lines 449-450

both modified: components/elm/src/main/ncdio_pio.F90.in

Soln: take upstream, removes iop mode, changes 'clm' to 'elm', and some whitespace cleanups, lines 20-23, 1470, 1746-1748, 1987

both modified: components/homme/CMakeLists.txt

Soln: take scream HEAD, just whitespace cleanup

both modified: components/homme/src/share/cxx/prim_cxx_driver_base.F90

Soln: take upstream, minor whitespace adjustment lines 17-18

both modified: components/homme/src/theta-l_kokkos/cxx/cxx_f90_interface_theta.cpp

Soln: take scream HEAD, removes duplicated set_elem_data call, lines 375
```

I was not 100% confident for many of those, so they will need to be reviewed by the SCREAM developer who touched those files.

Here are the conflicts that I had no confidence in fixing, so I just left them in the PR:

```
both modified: components/eam/src/control/forecast.F90
both modified: components/eam/src/dynamics/se/inidat.F90
both modified: components/eam/src/dynamics/se/se_single_column_mod.F90
both modified: components/homme/src/preqx_kokkos/CMakeLists.txt
both modified: components/homme/src/preqx_kokkos/prim_driver_mod.F90
both modified: components/homme/src/share/cxx/ElementsGeometry.hpp
both modified: components/homme/src/share/cxx/Hommexx_Session.cpp
both modified: components/homme/src/share/prim_driver_base.F90
both modified: components/homme/src/theta-l_kokkos/CMakeLists.txt
both modified: components/homme/src/theta-l_kokkos/prim_driver_mod.F90
```

The SCREAM developer who has touched those files should checkout out this branch, resolve the conflicts on their file, and push.

### CODE REVIEW

**Review by brhillman — APPROVED** [review]
Wow, huge merge! Thanks for doing this @jgfouca. Your handling of the radiation changes looks great to me.

**Comment by bogensch** [comment]
Thanks so much for doing this, @jgfouca!  I have resolved conflicts in forecast.F90, inidat.F90, and se_single_column_mod.F90; which should complete the conflicts caused by me.

**Comment by bartgol** [comment]
@jgfouca I'll get to this in the early afternoon today. Thanks for doing the (very large) bulk of the work!

**Comment by AaronDonahue** [comment]
@jgfouca , have you run the 10 CIME based tests that we run in the nightlies with this upstreamed merge branch to make sure those tests pass?

Other question: I see that a few sub-modules will be changed, including SCORPIO.  I would want to make sure that the submodule changes don't impact our SCREAM cmake directives or any other weirdness that can happen when sub-modules get changed.

**Comment by jgfouca** [comment]
@AaronDonahue , I have not. The PR does not build as it is now because I had to leave some of the conflicts in so they can be fixed by people who know those parts of the code better. Once Luca has fixed-up homme conflicts, I will run those CIME tests.

I assume that tests will fail if the Cmake in our submodules is no longer compatible with scream's Cmake.

**Comment by bartgol** [comment]
I fixed the conflicts in HOMME. When all tests pass, it's a go for me.

**Review by bartgol — APPROVED** [review]

**Comment by AaronDonahue** [comment]
> @AaronDonahue , I have not. The PR does not build as it is now because I had to leave some of the conflicts in so they can be fixed by people who know those parts of the code better. Once Luca has fixed-up homme conflicts, I will run those CIME tests.
> 
> I assume that tests will fail if the Cmake in our submodules is no longer compatible with scream's Cmake.

@jgfouca , great.  Once the CIME tests are verified to pass it is an approval from me.

**Review by AaronDonahue — APPROVED** [review]
Thanks for putting this together @jgfouca!

**Comment by oksanaguba** [comment]
I have a question about namelist_defaults:
in the PR
```
<hypervis_scaling> 0 </hypervis_scaling>
<hypervis_scaling dyn_target="theta-l"  hgrid="ne45np4"> 3.0 </hypervis_scaling>
<hypervis_scaling  hgrid="ne0np4_arm_x8v3_lowcon"  > 3.2 </hypervis_scaling>
<hypervis_scaling  hgrid="ne0np4_conus_x4v1_lowcon"  > 3.2 </hypervis_scaling>
<hypervis_scaling  hgrid="ne0np4_northamericax4v1"  > 3.2 </hypervis_scaling>
<hypervis_scaling dyn_target="theta-l" hgrid="ne0np4_northamericax4v1"  > 3.0 </hypervis_scaling>
<hypervis_scaling  hgrid="ne0np4_antarcticax4v1"  > 3.2 </hypervis_scaling>
<hypervis_scaling dyn_target="theta-l" hgrid="ne0np4_antarcticax4v1"  > 3.0 </hypervis_scaling>
<hypervis_scaling  hgrid="ne0np4_svalbard_x8v1_lowcon"  > 3.2 </hypervis_scaling>
<hypervis_scaling  hgrid="ne0np4_sooberingoa_x4x8v1_lowcon"  > 3.2 </hypervis_scaling>
<hypervis_scaling  hgrid="ne0np4_enax4v1">3.2</hypervis_scaling>
<hypervis_scaling  hgrid="ne0np4_twpx4v1" > 3.2 </hypervis_scaling>

<hypervis_scaling dyn_target="preqx" > 0 </hypervis_scaling>
<hypervis_scaling dyn_target="preqx" hgrid="ne0np4_arm_x8v3_lowcon"  > 3.2 </hypervis_scaling>
<hypervis_scaling dyn_target="preqx" hgrid="ne0np4_conus_x4v1_lowcon"  > 3.2 </hypervis_scaling>
<hypervis_scaling dyn_target="preqx" hgrid="ne0np4_northamericax4v1"  > 3.2 </hypervis_scaling>
<hypervis_scaling dyn_target="preqx" hgrid="ne0np4_antarcticax4v1"  > 3.2 </hypervis_scaling>
<hypervis_scaling dyn_target="preqx" hgrid="ne0np4_svalbard_x8v1_lowcon"  > 3.2 </hypervis_scaling>
<hypervis_scaling dyn_target="preqx" hgrid="ne0np4_sooberingoa_x4x8v1_lowcon"  > 3.2 </hypervis_scaling>
<hypervis_scaling dyn_target="preqx" hgrid="ne0np4_enax4v1">3.2</hypervis_scaling>
<hypervis_scaling dyn_target="preqx" hgrid="ne0np4_twpx4v1" > 3.2 </hypervis_scaling>
```
while in e3sm master
```
<hypervis_scaling dyn_target="preqx" > 0 </hypervis_scaling>
<hypervis_scaling dyn_target="preqx" hgrid="ne0np4_arm_x8v3_lowcon"  > 3.2 </hypervis_scaling>
<hypervis_scaling dyn_target="preqx" hgrid="ne0np4_conus_x4v1_lowcon"  > 3.2 </hypervis_scaling>
<hypervis_scaling dyn_target="preqx" hgrid="ne0np4_northamericax4v1"  > 3.2 </hypervis_scaling>
<hypervis_scaling dyn_target="preqx" hgrid="ne0np4_antarcticax4v1"  > 3.2 </hypervis_scaling>
<hypervis_scaling dyn_target="preqx" hgrid="ne0np4_svalbard_x8v1_lowcon"  > 3.2 </hypervis_scaling>
<hypervis_scaling dyn_target="preqx" hgrid="ne0np4_sooberingoa_x4x8v1_lowcon"  > 3.2 </hypervis_scaling>
<hypervis_scaling dyn_target="preqx" hgrid="ne0np4_enax4v1">3.2</hypervis_scaling>
<hypervis_scaling dyn_target="preqx" hgrid="ne0np4_twpx4v1" > 3.2 </hypervis_scaling>
```

Should I clean this up?

Also, the settings in master at some point switched HV to tensor HV, making cdash tests diff in most cases.
This PR I believe will cause the same for scream.

**Review by bogensch — APPROVED** [review]

**Comment by jgfouca** [comment]
@oksanaguba , feel free to cleanup anything you think is wrong in this branch.

**Comment by jgfouca** [comment]
@AaronDonahue , @oksanaguba , I got things building and test-all-scream is passing, but the CIME tests are DIFF:

example for ERS.ne4pg2_ne4pg2.F2010-SCREAM-LR:
```
SUMMARY of cprnc:
 A total number of    420 fields were compared
          of which    155 had non-zero differences
               and     40 had differences in fill patterns
               and      0 had different dimension sizes
```

The fill patterns diffs are expected from the CIME update.

The real diffs:
```
RMS x2a_Sx_avsdr                     1.8003E-02            NORMALIZED  3.1722E-02
 RMS x2a_Sx_anidr                     8.0317E-03            NORMALIZED  1.4306E-02
 RMS x2a_Sx_avsdf                     1.6062E-02            NORMALIZED  2.9296E-02
 RMS x2a_Sx_anidf                     9.2037E-03            NORMALIZED  1.6938E-02
 RMS x2a_Sx_tref                      1.5652E+00            NORMALIZED  5.4915E-03
 RMS x2a_Sx_qref                      1.0238E-03            NORMALIZED  1.1328E-01
 RMS x2a_Sx_t                         1.2372E+00            NORMALIZED  4.3308E-03
 RMS x2a_Sl_fv                        1.3239E-01            NORMALIZED  6.1091E-01
 RMS x2a_Sl_ram1                      1.2028E+02            NORMALIZED  1.5648E+00
 RMS x2a_Sl_snowh                     1.1936E-03            NORMALIZED  2.1072E-02
 RMS x2a_Si_snowh                     4.8221E-03            NORMALIZED  3.6189E-02
 RMS x2a_So_ssq                       8.0459E-05            NORMALIZED  6.4409E-03
 RMS x2a_So_re                        2.4950E-03            NORMALIZED  7.3797E-02
 RMS x2a_Sx_u10                       2.0798E+00            NORMALIZED  3.8345E-01
 RMS x2a_So_ustar                     7.3435E-02            NORMALIZED  4.3362E-01
 RMS x2a_Sl_dd001                     5.5471E-02            NORMALIZED  4.7257E-01
 RMS x2a_Sl_dd002                     2.9692E-01            NORMALIZED  5.6590E-01
 RMS x2a_Sl_dd003                     2.2602E-01            NORMALIZED  1.1431E+00
 RMS x2a_Faxx_taux                    6.9027E-02            NORMALIZED  9.9426E-01
 RMS x2a_Faxx_tauy                    7.9347E-02            NORMALIZED  1.4765E+00
 RMS x2a_Faxx_lat                     5.2051E+01            NORMALIZED  6.9401E-01
 RMS x2a_Faxx_sen                     2.2612E+01            NORMALIZED  8.8670E-01
 RMS x2a_Faxx_lwup                    5.4841E+00            NORMALIZED  1.4231E-02
 RMS x2a_Faxx_evap                    2.0812E-05            NORMALIZED  6.9414E-01
 RMS x2a_Fall_flxdst1                 2.9010E-10            NORMALIZED  5.4484E+00
 RMS x2a_Fall_flxdst2                 1.5572E-09            NORMALIZED  5.4484E+00
 RMS x2a_Fall_flxdst3                 3.6515E-09            NORMALIZED  5.4484E+00
 RMS x2a_Fall_flxdst4                 3.4396E-09            NORMALIZED  5.4484E+00
 RMS a2x_Sa_z                         7.5496E-02            NORMALIZED  5.9747E-03
 RMS a2x_Sa_u                         2.8897E+00            NORMALIZED  7.3244E-01
 RMS a2x_Sa_v                         3.5817E+00            NORMALIZED  1.1667E+00
 RMS a2x_Sa_tbot                      1.6147E+00            NORMALIZED  5.6634E-03
 RMS a2x_Sa_ptem                      1.6154E+00            NORMALIZED  5.6634E-03
 RMS a2x_Sa_shum                      1.0640E-03            NORMALIZED  1.2264E-01
 RMS a2x_Sa_pbot                      4.0190E+02            NORMALIZED  4.0831E-03
 RMS a2x_Sa_dens                      1.0758E-02            NORMALIZED  8.9232E-03
 RMS a2x_Sa_pslv                      4.1246E+02            NORMALIZED  4.0707E-03
 RMS a2x_Faxa_rainc                   4.6299E-05            NORMALIZED  2.0181E+00
 RMS a2x_Faxa_rainl                   2.0484E-05            NORMALIZED  4.8273E+00
 RMS a2x_Faxa_snowc                   2.1617E-06            NORMALIZED  5.7324E+00
 RMS a2x_Faxa_snowl                   4.4899E-06            NORMALIZED  2.3864E+00
 RMS a2x_Faxa_lwdn                    2.1758E+01            NORMALIZED  6.6335E-02
 RMS a2x_Faxa_swndr                   6.5097E+01            NORMALIZED  9.5898E-01
 RMS a2x_Faxa_swvdr                   6.1447E+01            NORMALIZED  1.0442E+00
 RMS a2x_Faxa_swndf                   2.7965E+01            NORMALIZED  1.1351E+00
 RMS a2x_Faxa_swvdf                   3.0627E+01            NORMALIZED  7.2386E-01
 RMS a2x_Faxa_swnet                   7.9919E+01            NORMALIZED  4.7097E-01
 RMS l2x_Sl_avsdr                     2.9607E-02            NORMALIZED  3.9686E-02
 RMS l2x_Sl_anidr                     1.3905E-02            NORMALIZED  1.8505E-02
 RMS l2x_Sl_avsdf                     2.7020E-02            NORMALIZED  3.6250E-02
 RMS l2x_Sl_anidf                     1.5530E-02            NORMALIZED  2.0472E-02
 RMS l2x_Sl_tref                      1.9224E+00            NORMALIZED  6.8732E-03
 RMS l2x_Sl_qref                      8.3740E-04            NORMALIZED  1.2090E-01
 RMS l2x_Sl_t                         2.2650E+00            NORMALIZED  8.1188E-03
 RMS l2x_Sl_fv                        1.7860E-01            NORMALIZED  4.5285E-01
 RMS l2x_Sl_ram1                      1.6226E+02            NORMALIZED  1.1599E+00
 RMS l2x_Sl_snowh                     1.6102E-03            NORMALIZED  1.5620E-02
 RMS l2x_Sl_u10                       1.5368E+00            NORMALIZED  3.3726E-01
 RMS l2x_Sl_dd001                     7.4833E-02            NORMALIZED  3.5030E-01
 RMS l2x_Sl_dd002                     4.0056E-01            NORMALIZED  4.1948E-01
 RMS l2x_Sl_dd003                     3.0491E-01            NORMALIZED  8.4731E-01
 RMS l2x_Fall_swnet                   6.0113E+01            NORMALIZED  6.3986E-01
 RMS l2x_Fall_taux                    2.7653E-01            NORMALIZED  1.1781E+00
 RMS l2x_Fall_tauy                    3.7656E-01            NORMALIZED  2.1633E+00
 RMS l2x_Fall_lat                     2.5197E+01            NORMALIZED  8.2067E-01
 RMS l2x_Fall_sen                     4.4105E+01            NORMALIZED  6.8759E-01
 RMS l2x_Fall_lwup                    1.0991E+01            NORMALIZED  3.1035E-02
 RMS l2x_Fall_evap                    1.0097E-05            NORMALIZED  8.2410E-01
 RMS l2x_Fall_flxdst1                 1.2672E-09            NORMALIZED  6.6137E+00
 RMS l2x_Fall_flxdst2                 6.8019E-09            NORMALIZED  6.6137E+00
 RMS l2x_Fall_flxdst3                 1.5950E-08            NORMALIZED  6.6137E+00
 RMS l2x_Fall_flxdst4                 1.5024E-08            NORMALIZED  6.6137E+00
 RMS l2x_Flrl_rofsur                  1.6650E-06            NORMALIZED  2.3065E+00
 RMS l2x_Flrl_rofgwl                  1.9655E-05            NORMALIZED  1.1029E+01
 RMS l2x_Flrl_rofsub                  1.2700E-10            NORMALIZED  1.3445E-02
 RMS l2x_Flrl_rofi                    1.4444E-06            NORMALIZED  3.0183E+00
 RMS l2x_Flrl_Tqsur                   1.5108E+00            NORMALIZED  5.4120E-03
 RMS l2x_Flrl_Tqsub                   3.0575E-03            NORMALIZED  1.1246E-05
 RMS x2l_Sa_z                         8.3764E-02            NORMALIZED  6.7509E-03
 RMS x2l_Sa_u                         1.9902E+00            NORMALIZED  5.7939E-01
 RMS x2l_Sa_v                         2.5009E+00            NORMALIZED  9.2381E-01
 RMS x2l_Sa_tbot                      1.8539E+00            NORMALIZED  6.6140E-03
 RMS x2l_Sa_ptem                      1.8547E+00            NORMALIZED  6.6140E-03
 RMS x2l_Sa_shum                      8.0972E-04            NORMALIZED  1.1992E-01
 RMS x2l_Sa_pbot                      3.4403E+02            NORMALIZED  3.5607E-03
 RMS x2l_Faxa_rainc                   3.4925E-05            NORMALIZED  2.5665E+00
 RMS x2l_Faxa_rainl                   1.7420E-05            NORMALIZED  5.2000E+00
 RMS x2l_Faxa_snowc                   2.6142E-06            NORMALIZED  5.9769E+00
 RMS x2l_Faxa_snowl                   3.9218E-06            NORMALIZED  1.4470E+00
 RMS x2l_Faxa_lwdn                    2.1551E+01            NORMALIZED  7.2679E-02
 RMS x2l_Faxa_swndr                   6.7445E+01            NORMALIZED  1.3822E+00
 RMS x2l_Faxa_swvdr                   5.5487E+01            NORMALIZED  1.3622E+00
 RMS x2l_Faxa_swndf                   3.0597E+01            NORMALIZED  1.9447E+00
 RMS x2l_Faxa_swvdf                   3.0183E+01            NORMALIZED  1.0862E+00
 RMS xaoo_So_tref                     1.4111E+00            NORMALIZED  5.6200E-03
 RMS xaoo_So_qref                     9.9728E-04            NORMALIZED  1.1512E-01
 RMS xaoo_So_ssq                      8.0459E-05            NORMALIZED  6.4409E-03
 RMS xaoo_So_re                       2.4950E-03            NORMALIZED  7.3797E-02
 RMS xaoo_So_u10                      2.0789E+00            NORMALIZED  4.1354E-01
 RMS xaoo_So_duu10n                   3.0752E+01            NORMALIZED  8.8661E-01
 RMS xaoo_So_ustar                    7.3435E-02            NORMALIZED  4.3362E-01
 RMS xaoo_Faox_taux                   4.6856E-02            NORMALIZED  1.3531E+00
 RMS xaoo_Faox_tauy                   5.2728E-02            NORMALIZED  1.8836E+00
 RMS xaoo_Faox_lat                    5.3826E+01            NORMALIZED  5.8001E-01
 RMS xaoo_Faox_sen                    2.5830E+01            NORMALIZED  6.7409E-01
 RMS xaoo_Faox_evap                   2.1522E-05            NORMALIZED  5.8001E-01
 RMS xaoo_Faox_swdn                   8.6188E+01            NORMALIZED  4.4914E-01
 RMS xaoo_Faox_swup                   5.1693E+00            NORMALIZED  4.9377E-01
 RMS xaoa_So_tref                     1.4111E+00            NORMALIZED  5.6200E-03
 RMS xaoa_So_qref                     9.9728E-04            NORMALIZED  1.1512E-01
 RMS xaoa_So_ssq                      8.0459E-05            NORMALIZED  6.4409E-03
 RMS xaoa_So_re                       2.4950E-03            NORMALIZED  7.3797E-02
 RMS xaoa_So_u10                      2.0789E+00            NORMALIZED  4.1354E-01
 RMS xaoa_So_duu10n                   3.0752E+01            NORMALIZED  8.8661E-01
 RMS xaoa_So_ustar                    7.3435E-02            NORMALIZED  4.3362E-01
 RMS xaoa_Faox_taux                   4.6856E-02            NORMALIZED  1.3531E+00
 RMS xaoa_Faox_tauy                   5.2728E-02            NORMALIZED  1.8836E+00
 RMS xaoa_Faox_lat                    5.3826E+01            NORMALIZED  5.8001E-01
 RMS xaoa_Faox_sen                    2.5830E+01            NORMALIZED  6.7409E-01
 RMS xaoa_Faox_evap                   2.1522E-05            NORMALIZED  5.8001E-01
 RMS xaoa_Faox_swdn                   8.6188E+01            NORMALIZED  4.4914E-01
 RMS xaoa_Faox_swup                   5.1693E+00            NORMALIZED  4.9377E-01
 RMS i2x_Si_avsdr                     7.8269E-03            NORMALIZED  1.8118E-02
 RMS i2x_Si_anidr                     1.6931E-02            NORMALIZED  5.2490E-02
 RMS i2x_Si_avsdf                     1.4076E-02            NORMALIZED  3.3111E-02
 RMS i2x_Si_anidf                     2.2476E-02            NORMALIZED  7.6404E-02
 RMS i2x_Si_tref                      2.5533E+00            NORMALIZED  1.0070E-02
 RMS i2x_Si_qref                      1.9081E-04            NORMALIZED  1.7157E-01
 RMS i2x_Si_t                         2.9459E+00            NORMALIZED  1.1678E-02
 RMS i2x_Si_snowh                     4.8221E-03            NORMALIZED  3.6189E-02
 RMS i2x_Si_u10                       1.3776E+00            NORMALIZED  3.4359E-01
 RMS i2x_Faii_swnet                   4.9718E+00            NORMALIZED  1.8657E-01
 RMS i2x_Fioi_swpen                   3.2830E-01            NORMALIZED  3.1950E-01
 RMS i2x_Faii_taux                    1.9688E-02            NORMALIZED  6.6673E-01
 RMS i2x_Faii_tauy                    1.7500E-02            NORMALIZED  6.8453E-01
 RMS i2x_Faii_lat                     2.5999E+00            NORMALIZED  6.1777E-01
 RMS i2x_Faii_sen                     5.8678E+00            NORMALIZED  3.3850E-01
 RMS i2x_Faii_lwup                    1.0028E+01            NORMALIZED  4.3484E-02
 RMS i2x_Faii_evap                    9.1428E-07            NORMALIZED  6.1889E-01
 RMS i2x_Fioi_meltw                   3.8037E-06            NORMALIZED  1.7536E+00
 RMS x2i_Sa_z                         7.5660E-02            NORMALIZED  5.9695E-03
 RMS x2i_Sa_u                         3.0313E+00            NORMALIZED  7.6381E-01
 RMS x2i_Sa_v                         3.7963E+00            NORMALIZED  1.2082E+00
 RMS x2i_Sa_tbot                      1.6041E+00            NORMALIZED  5.6100E-03
 RMS x2i_Sa_ptem                      1.6048E+00            NORMALIZED  5.6100E-03
 RMS x2i_Sa_shum                      1.1587E-03            NORMALIZED  1.2803E-01
 RMS x2i_Sa_pbot                      4.1974E+02            NORMALIZED  4.2477E-03
 RMS x2i_Sa_dens                      1.0964E-02            NORMALIZED  9.0841E-03
 RMS x2i_Faxa_rain                    5.9109E-05            NORMALIZED  2.0035E+00
 RMS x2i_Faxa_snow                    4.9150E-06            NORMALIZED  2.1633E+00
 RMS x2i_Faxa_lwdn                    2.3091E+01            NORMALIZED  6.9305E-02
 RMS x2i_Faxa_swndr                   7.8072E+01            NORMALIZED  1.1541E+00
 RMS x2i_Faxa_swvdr                   6.9290E+01            NORMALIZED  1.1633E+00
 RMS x2i_Faxa_swndf                   3.5113E+01            NORMALIZED  1.2341E+00
 RMS x2i_Faxa_swvdf                   3.4486E+01            NORMALIZED  7.4175E-01
```

Please advise.

**Comment by oksanaguba** [comment]
There are multiple definitions in namelist_defaults file. Depending on which definition was picked up, there may be differences.
I will try to clean the file.

Changes that you picked up from e3sm master include switching to tensor HV. 
This will cause diffs in tests with dycore on.
I assume that tensor HV should be default in scream just like in e3sm, but it is probably better to not to have diffs due to this PR.
So I will try to clean tehe file but leave HV unchanged.

**Review by bartgol — APPROVED** [review]

**Pull request merged**
