### PR TITLE
Jgfouca/upstream merge 2021 08 12

### PR DESCRIPTION
**Pull request by jgfouca**
### FILE: components/CMakeLists.txt

```
<<<<<<< HEAD

  if (DEBUG)
    set(E3SM_DEFAULT_BUILD_TYPE "DEBUG" CACHE STRING "Default build type, inferred from ${DEBUG}")
  else()
    set(E3SM_DEFAULT_BUILD_TYPE "RELEASE" CACHE STRING "Default build type, inferred from ${DEBUG}")
  endif()

=======
  # USE_CUDA is set through Macros.cmake / config_compilers.xml
  # If it exists, then set parent's scope to true; otherwise to false
>>>>>>> upstream/master
```
SOLN: Take both

### FILE: components/eam/cime_config/config_component.xml

```
<<<<<<< HEAD
    <desc compset="_EAM.*SCREAM-LR-DYAMOND1">Fortran version of SCREAM with SHOC, P3, RRTMGP, and prescribed aerosol. Initialized for DYAMOND1 (2016-08-01).</desc>
    <desc compset="_EAM.*SCREAM-HR-DYAMOND1">Fortran version of SCREAM with NH dycore, SHOC, P3, RRTMGP, prescribed aerosol, and no deep convection. Initialized for DYAMOND1 (2016-08-01).</desc>
    <desc compset="_EAM.*SCREAM-LR-DYAMOND2">Fortran version of SCREAM with SHOC, P3, RRTMGP, and prescribed aerosol. Initialized for DYAMOND2 (2020-01-20).</desc>
    <desc compset="_EAM.*SCREAM-HR-DYAMOND2">Fortran version of SCREAM with NH dycore, SHOC, P3, RRTMGP, prescribed aerosol, and no deep convection. Initialized for DYAMOND2 (2020-01-20).</desc>
    <desc compset="_EAM.*SCREAM-LR_">Fortran version of SCREAM with SHOC, P3, RRTMGP, and prescribed aerosol.</desc>
    <desc compset="_EAM.*SCREAM-HR_">Fortran version of SCREAM with NH dycore, SHOC, P3, RRTMGP, prescribed aerosol, and no deep convection.</desc>
    <!-- old MMF / Super-Parameterization -->
    <desc compset="_EAM%SP1V1_"    >SP-E3SM with 64x1km CRM, RRTMG radiation, 1-mom micro, prescribed aerosol</desc>
    <desc compset="_EAM%SP2V1_"    >SP-E3SM with 64x1km CRM, RRTMG radiation, 2-mom micro, prognostic aerosol</desc>
    <desc compset="_EAM%SP2V1-ECPP">SP-E3SM with 64x1km CRM, RRTMG radiation, 2-mom micro, prognostic aerosol, ECPP</desc>
    <!-- new MMF / Super-Parameterization -->
=======
    <!-- MMF / Super-Parameterization -->
>>>>>>> upstream/master
```
SOLN: Keep SCREAM compsets, remove old MMF compsets

### FILE: components/eam/src/control/runtime_opts.F90

```
<<<<<<< HEAD (LINE 338)
                         scm_observed_aero,swrad_off,lwrad_off, precip_off, &
                         iop_perturb_high, dp_crm
=======
                         scm_observed_aero, precip_off
>>>>>>> upstream/master
```
SOLN: Remove swrad_off,lwrad_off from HEAD, they aren't used. iop_perturb_high and dp_crm are used later, so I kept them. I'm not 100% confident in this soln.

### FILE: components/eam/src/control/scamMod.F90

```
subroutine scam_default_opts( scmlat_out,scmlon_out,iopfile_out, &
<<<<<<< HEAD (LINE 215)
        single_column_out,scm_iop_srf_prop_out, iop_dosubsidence_out,  &
        iop_nudge_tq_out, iop_nudge_uv_out, iop_nudge_tq_low_out, &
        iop_nudge_tq_high_out, iop_nudge_tscale_out, &
        scm_diurnal_avg_out, scm_crm_mode_out, scm_observed_aero_out, &
        swrad_off_out, lwrad_off_out, precip_off_out, scm_clubb_iop_name_out,&
        scm_multcols_out, dp_crm_out, iop_perturb_high_out)
=======
        single_column_out,scm_iop_srf_prop_out, scm_relaxation_out, &
        scm_relaxation_low_out, scm_relaxation_high_out, &
        scm_diurnal_avg_out, scm_crm_mode_out, scm_observed_aero_out, &
        precip_off_out, scm_clubb_iop_name_out)
>>>>>>> upstream/master
```
SOLN: Add iop_dosubsidence_out, iop_nudge_tq_out, iop_nudge_uv_out, iop_nudge_tq_low_out, iop_nudge_tq_high_out, iop_nudge_tscale_out, scm_multcols_out, dp_crm_out, iop_perturb_high_out to upstream
Remove scm_relaxation*

```
subroutine scam_setopts( scmlat_in, scmlon_in,iopfile_in,single_column_in, &
<<<<<<< HEAD (LINE 271)
                         scm_iop_srf_prop_in, iop_dosubsidence_in, &
                         iop_nudge_tq_in, iop_nudge_uv_in, iop_nudge_tq_low_in, &
                         iop_nudge_tq_high_in, iop_nudge_tscale_in, &
                         scm_diurnal_avg_in, scm_crm_mode_in, scm_observed_aero_in, &
                         swrad_off_in, lwrad_off_in, precip_off_in, scm_clubb_iop_name_in,&
                         scm_multcols_in, dp_crm_in, iop_perturb_high_in)
=======
                         scm_iop_srf_prop_in, scm_relaxation_in, &
                         scm_relaxation_low_in, scm_relaxation_high_in, &
                         scm_diurnal_avg_in, scm_crm_mode_in, scm_observed_aero_in, &
                         precip_off_in, scm_clubb_iop_name_in)
>>>>>>> upstream/master
```
SOLN: Similar to above

### FILE: components/eam/src/physics/rrtmgp/radiation.F90

```
<<<<<<< HEAD (LINE 423)
      do while (.not. dosw)
         nstep = nstep + 1
         offset = offset + dtime
         if (radiation_do('sw', nstep)) then
            radiation_nextsw_cday = get_curr_calday(offset=offset)
            dosw = .true.
         end if
      end do
      if(radiation_nextsw_cday == -1._r8) then
         call endrun('error in radiation_nextsw_cday')
      end if
=======
      if (iradsw/=0) then
         do while (.not. dosw)
            nstep = nstep + 1
            offset = offset + dtime
            if (radiation_do('sw', nstep)) then
               radiation_nextsw_cday = get_curr_calday(offset=offset)
               dosw = .true.
            end if
         end do
      end if

   end function radiation_nextsw_cday
>>>>>>> upstream/master
```
SOLN: Take upstream?

```
<<<<<<< HEAD (LINE 1355)
         ! If the swrad_off flag is set, meaning we should not do SW radiation, then
         ! we just set coszrs to zero everywhere. TODO: why not just set dosw false
         ! and skip the loop?
         if (swrad_off) coszrs(:) = 0._r8
=======
>>>>>>> upstream/master
```
SOLN: Take upstream

### FILE: components/homme/src/share/cxx/FunctorsBuffersManager.cpp

```
<<<<<<< HEAD
#ifdef HOMMEXX_BFB_TESTING
  generate_random_data();
#endif
=======
  generate_random_data();
>>>>>>> upstream/master

<<<<<<< HEAD
#ifdef HOMMEXX_BFB_TESTING
  generate_random_data();
#endif
=======
  generate_random_data();
>>>>>>> upstream/master

<<<<<<< HEAD
void generate_random_data ()
=======
void FunctorsBuffersManager::generate_random_data ()
>>>>>>> upstream/master
```
SOLN: Take upstream for all

### FILE: components/homme/src/share/namelist_mod.F90

```
<<<<<<< HEAD
!   Set as default to be used if no test case
    Sx = 0.0D0
    Sy = 0.0D0
    if (test_case == "planar_dbl_vrtx") then
      Lx = 5000.0D0 * 1000.0D0
      Ly = 5000.0D0 * 1000.0D0
      Sx = 0.0D0
      Sy = 0.0D0
    else if (test_case == "planar_hydro_gravity_wave") then
       Lx = 6000.0D0 * 1000.0D0
       Ly = 6000.0D0 * 1000.0D0
       Sx = -3000.0D0 * 1000.0D0
       Sy = -3000.0D0 * 1000.0D0
    else if (test_case == "planar_nonhydro_gravity_wave") then
       Lx = 300.0D0 * 1000.0D0
       Ly = 300.0D0 * 1000.0D0
       Sx = -150.0D0 * 1000.0D0
       Sy = -150.0D0 * 1000.0D0
    else if (test_case == "planar_hydro_mtn_wave") then
       Lx = 240.0D0 * 1000.0D0
       Ly = 240.0D0 * 1000.0D0
       Sx = 0.0D0 * 1000.0D0
       Sy = 0.0D0 * 1000.0D0
    else if (test_case == "planar_nonhydro_mtn_wave") then
       Lx = 144.0D0 * 1000.0D0
       Ly = 144.0D0 * 1000.0D0
       Sx = 0.0D0 * 1000.0D0
       Sy = 0.0D0 * 1000.0D0
    else if (test_case == "planar_schar_mtn_wave") then
       Lx = 100.0D0 * 1000.0D0
       Ly = 100.0D0 * 1000.0D0
       Sx = 0.0D0 * 1000.0D0
       Sy = 0.0D0 * 1000.0D0
    else if (test_case == "planar_density_current" .OR. test_case == "planar_moist_density_current") then
       Lx = 51.2D0 * 1000.0D0
       Ly = 51.2D0 * 1000.0D0
       Sx = -25.6D0 * 1000.0D0
       Sy = -25.6D0 * 1000.0D0
    else if (test_case == "planar_rising_bubble" .OR. test_case == "planar_moist_rising_bubble") then
       Lx = 1.0D0 * 1000.0D0
       Ly = 1.0D0 * 1000.0D0
       Sx = 0.0D0
       Sy = 0.0D0
! THESE ARE WRONG AND NEED TO BE FIXED WHEN THESE CASES ARE ACTUALLY IMPLEMENTED....
!else if (test_case == "planar_baroclinic_instab" .OR. test_case == "planar_moist_baroclinic_instab") then
!       Lx = 5000.0D0 * 1000.0D0
!       Ly = 5000.0D0 * 1000.0D0
!       Sx = 0.0D0
!       Sy = 0.0D0
!    else if (test_case == "planar_tropical_cyclone") then
!       Lx = 5000.0D0 * 1000.0D0
!       Ly = 5000.0D0 * 1000.0D0
!       Sx = 0.0D0
!       Sy = 0.0D0
!    else if (test_case == "planar_supercell") then
!       Lx = 5000.0D0 * 1000.0D0
!       Ly = 5000.0D0 * 1000.0D0
!       Sx = 0.0D0
!       Sy = 0.0D0
    end if
=======
>>>>>>> upstream/master
```
SOLN: Keep:
    Sx = 0.0D0
    Sy = 0.0D0

```
<<<<<<< HEAD
    if (Lx==0.0 .or. Ly==0.0) then
      print *, 'For planar homme Lx and Ly cannot be zero'
        call abortmp("Error Lx or Ly = 0")
    endif

  else if (geometry == "sphere") then
=======
    else if (geometry == "sphere") then
>>>>>>> upstream/master
```
SOLN: Keep both with correct indenting

### FILE: components/homme/src/theta-l_kokkos/cxx/HyperviscosityFunctorImpl.cpp

```
<<<<<<< HEAD
 : m_num_elems(state.num_elems())
 , m_data (params.hypervis_subcycle,params.nu_ratio1,params.nu_ratio2,params.nu_top,params.nu,params.nu_p,params.nu_s,params.hypervis_scaling)
=======
 : m_data (params.hypervis_subcycle,params.nu_ratio1,params.nu_ratio2,params.nu_top,params.nu,params.nu_p,params.nu_s,params.hypervis_scaling)
 , m_num_elems(state.num_elems())
>>>>>>> upstream/master

<<<<<<< HEAD
  : m_num_elems(num_elems)
  , m_data (params.hypervis_subcycle,params.nu_ratio1,params.nu_ratio2,params.nu_top,params.nu,params.nu_p,params.nu_s,params.hypervis_scaling)
=======
  : m_data (params.hypervis_subcycle,params.nu_ratio1,params.nu_ratio2,params.nu_top,params.nu,params.nu_p,params.nu_s,params.hypervis_scaling)
  , m_num_elems(num_elems)
>>>>>>> upstream/master
```

SOLN: Keep HEAD, it should remove out-of-order init warnings

### CODE REVIEW

**Review by bogensch — APPROVED** [review]
Focused mostly on the conflict resolutions you were unsure about in runtime_opts.F90 and ScamMod.F90 and they are correct.

**Review by bartgol — APPROVED** [review]
I think the homme side is fine.

**Comment by jgfouca** [comment]
I checked our cime tests (create_test e3sm_scream), and this PR looks good. ERS_R_Ln10.ne4_ne4.FDPSCREAMA97.mappy_gnu is failing, but it is failing on master too and has been for some time. I did see one new DIFF in the test SMS_R_Ln10.ne4_ne4.FDPSCREAMA97 and confirmed that it is caused by this PR. This diffs are:

```
 ANRAIN   (ncol,lev,time)  t_index =      2     2
        454    16200  (    73,    63,     1) (     1,     1,     1) (   189,    67,     1) (     1,    69,     1)
               16200   2.517236083984375E+03   0.000000000000000E+00 1.4E+02  1.726883056107908E-04 1.8E-02  1.777721627149731E-04
               16200   2.517236083984375E+03   0.000000000000000E+00          1.352860412597656E+02          0.000000000000000E+00
               16200  (    73,    63,     1) (     1,     1,     1)
          avg abs field values:    7.489581704139709E-01    rms diff: 1.3E+00   avg rel diff(npos):  1.8E-02
                                   7.766961455345154E-01                        avg decimal digits(ndif):  0.4 worst:  0.0
 RMS ANRAIN                           1.2583E+00            NORMALIZED  1.6496E+00


 AQRAIN   (ncol,lev,time)  t_index =      2     2
        454    16200  (     0,    64,     1) (     1,     1,     1) (   178,    67,     1) (     1,    69,     1)
               16200   1.505385682776250E-08   0.000000000000000E+00 2.7E-09  3.859606523270998E-10 1.4E-02  1.089370052498317E-10
               16200   1.505385682776250E-08   0.000000000000000E+00          3.039480223065993E-09          0.000000000000000E+00
               16200  (     0,    64,     1) (     1,     1,     1)
          avg abs field values:    2.290133534199601E-11    rms diff: 5.0E-11   avg rel diff(npos):  1.4E-02
                                   2.790541756003684E-11                        avg decimal digits(ndif):  0.4 worst:  0.0
 RMS AQRAIN                           5.0398E-11            NORMALIZED  1.9839E+00


 FREQR   (ncol,lev,time)  t_index =      2     2
        454    16200  (    73,    64,     1) (     1,     1,     1) (     0,    68,     1) (     1,    69,     1)
               16200   4.007213574368507E-04   0.000000000000000E+00 1.1E-03  1.857089519035071E-04 2.5E-02  9.999999747378752E-06
               16200   1.255708979442716E-03   0.000000000000000E+00          1.255708979442716E-03          0.000000000000000E+00
               16200  (     0,    68,     1) (     1,     1,     1)
          avg abs field values:    8.834124855638947E-06    rms diff: 2.0E-05   avg rel diff(npos):  2.5E-02
                                   1.146209160651779E-05                        avg decimal digits(ndif):  0.0 worst:  0.0
 RMS FREQR                            1.9964E-05            NORMALIZED  1.9673E+00


 A total number of    439 fields were compared
          of which      3 had non-zero differences
```

**Comment by brhillman** [comment]
Take upstream for the RRTMGP radiation diffs. Looks like you figured it out. Sorry about that.

**Review by brhillman — APPROVED** [review]

**Pull request merged**
