### PR TITLE
Revert dry to wet mass mixing ratio conversion commits in P3 

### PR DESCRIPTION
**Pull request by crterai**
Until a new fix goes in, this PR reverts PR #1395 and #1288 to revert the dry to wet mass mixing ratio conversion in P3, since we found it to be a source of a water leak. 

NBFB

### CODE REVIEW

**Review by bartgol — APPROVED** [review]

**Review by singhbalwinder — APPROVED** [review]
Looks good to me!

**Comment by bartgol** [comment]
FYI, when you see something like
```
Build type full_debug failed. Here's a list of failed tests:
Build type full_sp_debug failed. Here's a list of failed tests:
Build type debug_nopack_fpe failed. Here's a list of failed tests:
Build type release failed. Here's a list of failed tests:
```
which is puzzling cause one thinks "so no tests failed?", the reason is that ctest failed at build time. This is another thing that could maybe be made clearer in our testing scripts.

**Comment by PeterCaldwell** [comment]
Now that @AaronDonahue is back, let's not integrate this PR for a day or so in hopes that he can fix the actual issue: https://github.com/E3SM-Project/scream/pull/1776.

**Comment by AaronDonahue** [comment]
addressed by #1792

**Pull request closed without merging**
