### PR TITLE
Update EKAT

### PR DESCRIPTION
**Pull request by jgfouca**

### CODE REVIEW

**Review by ndkeen — APPROVED** [review]
I approve the change we made regarding the CMake logic that allowed us to build the non-defalt compilers where it was getting confused about the compiler/MPI version.

**Review by bartgol — APPROVED** [review]
What do we need this for? Is it for the cray fix related to MPI?

**Comment by jgfouca** [comment]
@bartgol , yes

**Comment by AaronDonahue** [comment]
I'm guessing this will be safe to merge once the AT runs again, now that we have created baselines for the wet scavenging tests.  I'll add the RETEST label.

**Review by bartgol — APPROVED** [review]
@jgfouca I took the liberty of fixing the failing test. The other one is simply not finding the baseline, since I think we did not bless it correctly yet. Feel free to merge, or RETEST to get a shiny green button.

**Comment by jgfouca** [comment]
Thanks, @bartgol

**Pull request merged**
