### PR TITLE
Change machine names for Perlmutter

### PR DESCRIPTION
**Pull request by ndkeen**
perlmutter -> pm-gpu
and now we have a new machine: pm-cpu

### CODE REVIEW

**Comment by ndkeen** [comment]
Not sure why this failed

**Comment by AaronDonahue** [comment]
For the fail on `blake` I'm going to guess you hit one of those random seeds that actually cause a fail.  I would retest and see what happens.  As for `mappy` it looks like that one just went off the rails.

**Comment by ndkeen** [comment]
OK thanks.  I also just realized I neglected to `git add` the pm-cpu.cmake file.  I just did that -- does AT automatically detect and retest?

**Comment by bartgol** [comment]
> OK thanks. I also just realized I neglected to `git add` the pm-cpu.cmake file. I just did that -- does AT automatically detect and retest?

Yes. Every time the sha of the branch changes, the AT tests the PR (regardless of whether it already passed or not).

**Comment by bartgol** [comment]
> For the fail on `blake` I'm going to guess you hit one of those random seeds that actually cause a fail. I would retest and see what happens. As for `mappy` it looks like that one just went off the rails.

Aren't "those random seeds" becoming a bit more frequent lately?

**Comment by AaronDonahue** [comment]
@bartgol , yes.  I've been keeping track of them in issue #1506 .  I think we will want to figure out what is going on there sooner or later.

**Review by bartgol — APPROVED** [review]

**Pull request merged**
