### PR TITLE
In jenkins scripts, run memcheck/coverage tests only if requested (via env vars)

### PR DESCRIPTION
**Pull request by bartgol**
This PR will hopefully allow our nightly testing on weaver to complete. Occasionally, it has timed out, due to tests taking a long time to complete. This PR aims to speedup our individual jenkins jobs, by running memcheck/coverage jobs separately. On weaver, each compute sanitizer test is run separately, so that we can (hopefully) use more nodes, and run more of the long tests concurrently.

If/when we merge this, we must create new jenkins jobs for the memcheck/coverage builds on mappy/weaver. Notice that, since the memcheck/coverage tests don't require baselines, we can run the new jobs concurrently with each other (and with the main standalone testing job) if needed.

@jgfouca I want to test this in `scripts-tests`, but I'm not sure what's the most reliable way to set env vars so that jenkins reads them. E.g., in this test
```
    def test_mem_check_details(self):
        """
        Test the mem (default mem-check build) in test-all-scream. It should set certain CMake values
        """
        if not self._jenkins:
            options = "-b HEAD -k -t mem --config-only"
            cmd = self.get_cmd("./test-all-scream -m $machine {}".format(options),
                                self._machine, dry_run=False)
            run_cmd_assert_result(self, cmd, from_dir=TEST_DIR)
            builddir = "compute_sanitizer_memcheck" if is_cuda_machine(self._machine) else "valgrind"
            test_cmake_cache_contents(self, builddir, "CMAKE_BUILD_TYPE", "Debug")
            test_cmake_cache_contents(self, builddir, "SCREAM_TEST_SIZE", "SHORT")
            if is_cuda_machine(self._machine):
                test_cmake_cache_contents(self, builddir, "EKAT_ENABLE_COMPUTE_SANITIZER", "TRUE")
                test_cmake_cache_contents(self, builddir, "EKAT_COMPUTE_SANITIZER_OPTIONS", "--tool=memcheck")
            else:
                test_cmake_cache_contents(self, builddir, "EKAT_ENABLE_VALGRIND", "TRUE")
        else:
            self.skipTest("Skipping config-only run for jenkins test")
```
is it ok to just do `os.environ['SCREAM_TEST_SANITIZER_MEMCHECK'] = 1` right before the `run_cmd_assert_result` line? Will that ensure the subprocess inherits it?

### CODE REVIEW

**Review by jgfouca — APPROVED** [review]

**Comment by jgfouca** [comment]
@bartgol , the trick is that you don't want to do anything that could impact other tests, so you don't want to change os.environ, which is global. You can add env settings to the shell command:

```
self.get_cmd("SCREAM_TEST_SANITIZER_MEMCHECK=1 ./test-all-scream -m ...
```

**Comment by bartgol** [comment]
@jgfouca what about
```
os.environ['SCREAM_TEST_SANITIZER_MEMCHECK'] = 1
run_cmd_assert_result(...)
os.environ['SCREAM_TEST_SANITIZER_MEMCHECK'] = 0
```
?

**Comment by jgfouca** [comment]
@bartgol , you're still changing the environment if you do that approach. Why not just add it to the shell command like I described?

**Comment by bartgol** [comment]
> @bartgol , you're still changing the environment if you do that approach. Why not just add it to the shell command like I described?

Yeah, I can just do that.

**Comment by AaronDonahue** [comment]
@bartgol and @jgfouca is this still WIP?

**Comment by bartgol** [comment]
@AaronDonahue Yes, sorry. I got sidetracked, and haven't added the unit tests for the scripts yet. I'll do it ahorita ;-)

**Comment by bartgol** [comment]
Closing for now. We haven't experienced weaver time outs recently. Weaver maintenance is working on improving the slow FS issue, which hopefully will make this kind of fix no longer needed anyways.

**Pull request closed without merging**
