### PR TITLE
Bartgol/upstream merge 2020 10 12

### PR DESCRIPTION
**Pull request by bartgol**
This brings in the kokkos version of theta-l in Homme. It also brings in the recent change cam->eam.

The conflicts were a few, but mostly due to cam->eam renaming, so they seemed fairly straightforward to me.

The biggest impacts this may have for scream devs/users are:
- scream v0 physics files are now relocated in components/eam/...
- scream compsets long names have EAM instead of CAM5 in them.

I added reviewers who I think may have knowledge of cime and/or scream compsets and/or v0 stuff. Could you please check that the merge of e3sm master did not mess up scream compsets and/or v0 stuff?

### CODE REVIEW

**Comment by AaronDonahue** [comment]
@bartgol , rather than look through the 2000+ file changes I figure it is easier to ask.  Did you copy/move all of the scream physics from the cam subfolder to the eam subfolder?

**Comment by AaronDonahue** [comment]
@bartgol , I am running the F-Compset tests on this branch now to see if there are any issues that pop up.  Additionally I found a few missing references to `cam` instead of `eam` when running the unit tests.  I'll push a fix for those after I've checked the F-Compset tests and made fixes as appropriate.

**Comment by AaronDonahue** [comment]
Yes, good point.  I believe the changes are consistent.  Most of them touch scream code and the few that are in the eam sub-directory are either a) a scream change (namely add shoc_sgs as an option) or b) a change to point to the eam directory instead of the cam directory. 

I'm almost ready to push these changes.  Just checking on a fix after two of the 10 scream tests failed.  It takes awhile to rebuild and re-submit.

**Comment by crterai** [comment]
Hi all, Peter asked me to test out the PR branch for the ne256 DYAMOND2 case for v0 SCREAM. And I got the following error while configuring the model. I suspect, this is something @AaronDonahue  found, but pasting it here for reference:
`Creating component namelists
  2020-10-13 08:22:38 atm 
   Calling /global/u1/t/terai/SCREAM/scream/master/components/eam/cime_config/buildnml
ERROR: Command: '/global/u1/t/terai/SCREAM/scream/master/components/eam/bld/configure -s -ccsm_seq -ice none -ocn docn -caseroot /global/cscratch1/sd/terai/E3SM_simulation/master.ne256pg2_r0125_oRRS18to6v3.F2010-SCREAM-HR-DYAMOND2.cori-knl_intel.128x64x2.DY2_NCPL144_debug.20201013-08 -comp_intf mct  -spmd -spmd -smp -smp -dyn se -dyn_target theta-l -res ne256np4.pg2   -mach cori-knl -phys cam5 -phys cam5 -shoc_sgs -microphys p3 -chem none -nlev 128 -rad rrtmgp ' failed with error 'Unknown option: shoc_sgs`

**Comment by AaronDonahue** [comment]
> Hi all, Peter asked me to test out the PR branch for the ne256 DYAMOND2 case for v0 SCREAM. And I got the following error while configuring the model. I suspect, this is something @AaronDonahue found, but pasting it here for reference:
> `Creating component namelists 2020-10-13 08:22:38 atm Calling /global/u1/t/terai/SCREAM/scream/master/components/eam/cime_config/buildnml`
> `ERROR: Command: '/global/u1/t/terai/SCREAM/scream/master/components/eam/bld/configure -s -ccsm_seq -ice none -ocn docn -caseroot /global/cscratch1/sd/terai/E3SM_simulation/master.ne256pg2_r0125_oRRS18to6v3.F2010-SCREAM-HR-DYAMOND2.cori-knl_intel.128x64x2.DY2_NCPL144_debug.20201013-08 -comp_intf mct -spmd -spmd -smp -smp -dyn se -dyn_target theta-l -res ne256np4.pg2 -mach cori-knl -phys cam5 -phys cam5 -shoc_sgs -microphys p3 -chem none -nlev 128 -rad rrtmgp ' failed with error 'Unknown option: shoc_sgs`

@crterai , yes.  My fix will address this.  It should be coming shortly and then I'll ping you so you can try again.

**Comment by bartgol** [comment]
@crterai @AaronDonahue thanks for finding/fixing my mistakes!

**Comment by AaronDonahue** [comment]
ok, those have been fixed.  It builds and passes all tests on Lassen now.

**Comment by crterai** [comment]
I updated the my local branch to 44d44d4e9 and tried running again. It passed the namelist configuration phase (thanks, @AaronDonahue !) but it failed in the build on cori with the following error. (details: compset: 2010-SCREAM-HR-DYAMOND2 resolution: ne256pg2  machine: cori)
I don't know what the exact issue is though. 
```
/usr/bin/ld: attempted static link of dynamic object `/usr/lib64/libdl.so'
gmake[2]: *** [cmake/cpl/CMakeFiles/e3sm.exe.dir/build.make:534: /global/cscratch1/sd/terai/e3sm_scratch/cori-knl/master.ne256pg2_r0125_oRRS18to6v3.F2010-SCREAM-HR-DYAMOND2.cori-knl_intel.128x64x2.DY2_test2newmaster_Oct13.20201013-10/bld/e3sm.exe] Error 1
gmake[2]: Leaving directory '/global/cscratch1/sd/terai/e3sm_scratch/cori-knl/master.ne256pg2_r0125_oRRS18to6v3.F2010-SCREAM-HR-DYAMOND2.cori-knl_intel.128x64x2.DY2_test2newmaster_Oct13.20201013-10/bld/cmake-bld'
gmake[1]: *** [CMakeFiles/Makefile2:630: cmake/cpl/CMakeFiles/e3sm.exe.dir/all] Error 2
gmake[1]: Leaving directory '/global/cscratch1/sd/terai/e3sm_scratch/cori-knl/master.ne256pg2_r0125_oRRS18to6v3.F2010-SCREAM-HR-DYAMOND2.cori-knl_intel.128x64x2.DY2_test2newmaster_Oct13.20201013-10/bld/cmake-bld'
gmake: *** [Makefile:87: all] Error 2
```

**Comment by xyuan** [comment]
It looks like the environment variables are not right, please check the LD_LIBRARY_PATH to get what you have on Cori machine.

**Comment by crterai** [comment]
Thanks for the reply, @xyuan. How can I check what's the LD_LIBRARY_PATH when I'm building the model?

**Comment by xyuan** [comment]
Please try “env |grep LD_LIBRARY_PATH”

**Comment by xyuan** [comment]
The only difference from what I used on Nersc is that I am using openmpi, and you are using mpich, what is your actually linked to when you link the obj files to exe?

**Comment by bartgol** [comment]
The error
```
/usr/bin/ld: attempted static link of dynamic object `/usr/lib64/libdl.so'
```
appears when you use the `-static` flag for the linker, but, instead of passing `-ldl` (which the `-static` flag can then force to be resolved to the static lib `/some/path/libdl.a`), the full path to a non-static lib is used.

I think kokkos links against the dl library. I'm not sure why it is hardcoded with the path, rather than just appearing as `-ldl`. Perhaps there's some Kokkos switch that we can use to force `-ldl` type linking.

Another solution could be to tell the linker to resort to dynamic linking for libdl.so, via `-Bdynamic`. But that seems quite a hack, and I'm not sure how to do it.

**Comment by xyuan** [comment]
Why it needs static link?

**Comment by bartgol** [comment]
I'm not a cime expert, but I thought that was the default behavior on Cori...

**Review by jgfouca — APPROVED** [review]
`create_test e3sm_scream` needs to be checked on mappy. If that works, I approve.

**Review by AaronDonahue — APPROVED** [review]
Passed for stand-alone tests on syrah and lassen.
Passed for F-Compset test suite on syrah

**Comment by mikaelwitte** [comment]
@crterai did you end up solving this issue? I am also unable to compile on Cori, getting the same fail without the "attempted static link..." error.

**Comment by crterai** [comment]
> @crterai did you end up solving this issue? I am also unable to compile on Cori, getting the same fail without the "attempted static link..." error.

No, I haven't resolved it yet. I've re-created the same build failure when I run a test with `./create_test SMS_D.ne30pg2_ne30pg2.F2010-SCREAM-HR.cori-knl_intel` . 
I'm currently testing whether updating cime to most recent master helps resolve the issue... 

@mikaelwitte - in what context do you encounter your error?

**Comment by mikaelwitte** [comment]
@crterai I've been trying to compile an SCM case with compset F_SCAM5 (so maybe @bogensch should also be aware of this). I also updated to the latest CIME version to no avail.

**Comment by PeterCaldwell** [comment]
@mikaelwitte - I'm confused why you're trying to use an unmerged branch for your runs instead of scream master. My (admittedly vague) understanding is that the problem you're having is related to this particular PR and if you used scream master your troubles would evaporate. I'm sure you have a good reason, I just don't know it...

**Comment by PeterCaldwell** [comment]
FYI instead of reviewing all 2617 files changed by this PR, I asked Chris T to make sure DYAMOND2 configs still run after this PR. I'm not planning on reviewing it so don't wait on me ;-).

**Comment by mikaelwitte** [comment]
@PeterCaldwell - fair question. I'm not using this branch. I have a separate unmerged development branch I'm working on that I just rebased to master, and I've never touched the land model so I thought I'd come here first to see if Chris had a quick fix.

**Comment by PeterCaldwell** [comment]
@mikaelwitte - my understanding is that this static link problem is due to e3sm switching to a newer version of Kokkos which is used by semi-Lagrangian advection. I'm not sure why the SCM would need that. @bartgol is working on a fix. I'm not sure if any of this info helps you but just keeping you in the loop.

**Comment by bartgol** [comment]
@PeterCaldwell I looked into this, and sadly, I realized I have no easy way to fix it. At least not that I can think of.

Big picture: kokkos creates a cmake imported target for its tpls (a nice cmake way of handling tpls). That requires to specify the exact location of the lib (path+filename), so that cmake can later link it. For the dl lib, this causes a line like `/some/path/libdl.so` on the link line.

I see two potential solutions (potential cause I have no idea if they can be done):

1) somehow, force cmake to find static libs _before_ dynamic ones if cime builds with `-static`. I don't know if cmake offers this capability, I don't think so though. If not, the only way of achieving it would be to hack kokkos' cmake machinery, to set the lib name to `libdl.a` on cori, but that's way too invasive and impossible to maintain.
2) remove the `-static` flag on cori. But that would require to force cmake to pick up static libs for the ones that are giving troubles. This is kind of like 1), but at least it doesn't involve messing with an external submodule build system.

**Comment by PeterCaldwell** [comment]
Hmm. This is a bummer and also totally outside my wheelhouse. We definitely can't merge this PR until it quits breaking our DYAMOND simulations but having this PR stuck is bad for v1 development. Does @jgfouca have any ideas?

**Comment by mikaelwitte** [comment]
Thanks @PeterCaldwell. My issue was that some submodules needed to be updated, I've resolved it now - sorry for raising a red herring.

**Comment by ambrad** [comment]
This is actually causing an issue in E3SM. For context, this Kokkos update is to support Hommexx.

**Comment by bartgol** [comment]
Update: this _might_ solve the libdl problem:

```
 -D Kokkos_ENABLE_PROFILING:BOOL=OFF \
 -D Kokkos_ENABLE_LIBDL:BOOL=OFF
```
Of course, you can't do kokkos profiling though. I am trying to verify this.

**Comment by bartgol** [comment]
Putting this PR on hold. The issue with libdl has been addressed in E3SM (see E3SM-Project/E3SM#3893).

The fix will likely need to be propagated to EKAT's kokkos submodule (since scream relies on that for kokkos).

**Review by AaronDonahue — APPROVED** [review]

**Pull request merged**
