### PR TITLE
Hot-fix to the set of output fields.

### PR DESCRIPTION
**Pull request by AaronDonahue**
Removes phi_int from the default set of outputs.  This was removed
as a variable in a previoud PR.

### CODE REVIEW

**Comment by AaronDonahue** [comment]
@brhillman or @bartgol either one of you can review this PR.  It is just a hotfix in response to the two v1 fails on mappy this morning.

**Review by bartgol — APPROVED** [review]

**Comment by PeterCaldwell** [comment]
Can I suggest that screamv1_output.yaml gets renamed to scream_output.yaml for consistency with scream_input.yaml?

**Comment by AaronDonahue** [comment]
@PeterCaldwell , for sure.  I can add that to this PR

**Comment by AaronDonahue** [comment]
@PeterCaldwell , done.  the PR will probably need to be re-approved.

**Review by PeterCaldwell — APPROVED** [review]
thanks!

**Comment by bartgol** [comment]
@jgfouca This might conflict with the upstream merge PR.

**Comment by AaronDonahue** [comment]
> @jgfouca This might conflict with the upstream merge PR.

If that's the case then we can revert to just the main hot-fix.  I don't want to hold up the upstream merge.  But I do want this to get in today so tomorrows CDash can be clean tests.

**Comment by bartgol** [comment]
Also the hot fix will likely clash with the upstream merge. But it's ok. Unless the upstream merge is going to merge very soon, it's ok to get this fix in, and deal with conflicts in the upstream merge. Unless @jgfouca wants to incorporate these changes in the upstream merge, in which case we can close this.

**Comment by jgfouca** [comment]
@bartgol , @AaronDonahue , I am willing to merge the upstream without a fresh round of AT testing. I requested a RETEST about 3 hours ago and it's still waiting. There have been only minor changes since the last AT which had only one expected fail.

**Comment by bartgol** [comment]
The upstream fixed the `phi_int` error. @AaronDonahue this PR now needs to be rebased on master, and would just consist of the `screamv1_output.yaml` -> `scream_output.yaml` change. Do you want to keep the PR, or simply attach that change to any other PR?

**Comment by AaronDonahue** [comment]
I guess we could keep the PR, since the work is there and it would be a quick turnaround.

**Comment by bartgol** [comment]
@jgfouca This PR fails despite being ahead of master. I think the upstream merge might require to create and rebless baselines, right?

**Comment by AaronDonahue** [comment]
oh right, I would expect that.  Do we want to manually merge.  The 2 changes are very minor and I think we can be confident they won't impact the solution.

**Comment by bartgol** [comment]
Yeah, we can force merge this, I think.

**Pull request merged**
