### PR TITLE
Jgfouca/upstream merge 2023 06 14

### PR DESCRIPTION
**Pull request by jgfouca**

### CODE REVIEW

**Comment by jgfouca** [comment]
@AaronDonahue , @bogensch , I was a bit over eager to merge and I merged #2382 before it was ready. I have reset master and re-issued this new PR.

There appears to be a real problem with this branch, specifically the v0 test `ERP_R_Ln10.ne4_ne4.FDPSCREAM-ARM97.mappy_gnu`. The test fails during the run of case2 (ERP is a 2-case test) with this error:

```
 ERROR timeaddmonths():  MM out of range
 ERROR: CHKRC
#0  0x13964ca in ???
#1  0x139668d in ???
#2  0x53f4d4 in ???
#3  0x5409a6 in ???
#4  0x511bfd in ???
#5  0x7ce3a4 in ???
#6  0x4caa98 in ???
#7  0x4c6387 in ???
#8  0x430d84 in ???
#9  0x424857 in ???
#10  0x411ae1 in ???
#11  0x7fc476230554 in ???
#12  0x4123b8 in ???
#13  0xffffffffffffffff in ???
```

I will run it in debug to see if I can get a better stacktrace.

As a reminder, an ERP test does the following:
```
ERP    pes counts hybrid (open-MP/MPI) restart bfb test from startup, default 6 days + 5 days (previousy PER)                                                                                                                   
       initial pes set up out of the box                                                                                                                                                                                        
       do an 11 day initial test - write a restart at day 6     (suffix base)                                                                                                                                                   
       half the number of tasks and threads for each component                                                                                                                                                                  
       do a  5  day restart test starting from restart at day 6 (suffix rest)                                                                                                                                                   
       this is just like an ERS test but the pe-counts/threading count are modified on retart 
```

For this test on mappy, NTASKS=1 and NTHRDS=1 for all components, so this is not really any different than an ERS test.

@bogensch , thoughts on this? Are you able to reproduce this error on one of your machines?

**Comment by jgfouca** [comment]
As a side note, the "R" test modifier forces NTASKS=1 and NTHRDS=1 for all platforms:

```
                elif opt.startswith("R"):
                    # R option is for testing in PTS_MODE or Single Column Model                                                                                                                                                
                    #  (SCM) mode                                                                                                                                                                                               
                    envtest.set_test_parameter("PTS_MODE", "TRUE")

                    # For PTS_MODE, set all tasks and threads to 1                                                                                                                                                              
                    comps = ["ATM", "LND", "ICE", "OCN", "CPL", "GLC", "ROF", "WAV"]

                    for comp in comps:
                        envtest.set_test_parameter("NTASKS_" + comp, "1")
			envtest.set_test_parameter("NTHRDS_" + comp, "1")
                        envtest.set_test_parameter("ROOTPE_" + comp, "0")
                        envtest.set_test_parameter("PIO_TYPENAME", "netcdf")
```

So it really makes no sense to even have an ERP_R test. This should probably be an ERS_R test.

**Comment by jgfouca** [comment]
Same error from a debug case, way better info:

```
At line 569 of file /home/jgfouca/scream-extra/components/eam/src/control/iop_data_mod.F90
Fortran runtime error: Index '1' of dimension 1 of array 'tsec' above upper bound of 0

Error termination. Backtrace:
#0  0x7365e5 in __iop_data_mod_MOD_setiopupdate
        at /home/jgfouca/scream-extra/components/eam/src/control/iop_data_mod.F90:569
#1  0x1145232 in __stepon_MOD_stepon_run1
        at /home/jgfouca/scream-extra/components/eam/src/dynamics/se/stepon.F90:219
#2  0x62c9a2 in __cam_comp_MOD_cam_run1
        at /home/jgfouca/scream-extra/components/eam/src/control/cam_comp.F90:251
#3  0x61c0fc in __atm_comp_mct_MOD_atm_init_mct
        at /home/jgfouca/scream-extra/components/eam/src/cpl/atm_comp_mct.F90:425
#4  0x445772 in __component_mod_MOD_component_init_cc
        at /home/jgfouca/scream-extra/driver-mct/main/component_mod.F90:248
#5  0x436876 in __cime_comp_mod_MOD_cime_init
        at /home/jgfouca/scream-extra/driver-mct/main/cime_comp_mod.F90:2320
#6  0x43e4d4 in cime_driver
        at /home/jgfouca/scream-extra/driver-mct/main/cime_driver.F90:122
#7  0x43e614 in main
        at /home/jgfouca/scream-extra/driver-mct/main/cime_driver.F90:23

```

**Comment by jgfouca** [comment]
OK, `ERS_R_Ln10.ne4_ne4.FDPSCREAM-ARM97` passes, so I think we should probably just change the test, right?

**Comment by jgfouca** [comment]
I pushed the test change because I think we are all going to agree on that.

**Comment by jgfouca** [comment]
@bogensch , @AaronDonahue , thoughts?

**Comment by bogensch** [comment]
Thanks @jgfouca .  I agree that the ERP test should be removed and replaced by ERS.  Though, you stated that you pushed this change but I don't see this in the commit log.... did you or am I missing something?

**Comment by jgfouca** [comment]
@bogensch , good catch. I must have confused myself with all the churn on this branch/PR.

**Comment by jgfouca** [comment]
@bogensch , I think I know what happened. I pushed the test change and tested that modified test case in the wrong repo, whoops! It looks like the test `ERS_R_Ln10.ne4_ne4.FDPSCREAM-ARM97` fails on this branch just like the ERP one did, so there may actually be a real problem. Would you be able to look into this?

**Comment by jgfouca** [comment]
When I run the case in debug, I get a callstack that looks useful:

```
At line 569 of file /home/jgfouca/scream-extra/components/eam/src/control/iop_data_mod.F90
Fortran runtime error: Index '1' of dimension 1 of array 'tsec' above upper bound of 0

Error termination. Backtrace:
#0  0x7350cc in __iop_data_mod_MOD_setiopupdate
        at /home/jgfouca/scream-extra/components/eam/src/control/iop_data_mod.F90:569
#1  0x113df87 in __stepon_MOD_stepon_run1
        at /home/jgfouca/scream-extra/components/eam/src/dynamics/se/stepon.F90:219
#2  0x62b77d in __cam_comp_MOD_cam_run1
        at /home/jgfouca/scream-extra/components/eam/src/control/cam_comp.F90:251
#3  0x61aed7 in __atm_comp_mct_MOD_atm_init_mct
        at /home/jgfouca/scream-extra/components/eam/src/cpl/atm_comp_mct.F90:425
#4  0x444ab2 in __component_mod_MOD_component_init_cc
        at /home/jgfouca/scream-extra/driver-mct/main/component_mod.F90:248
#5  0x435bb6 in __cime_comp_mod_MOD_cime_init
        at /home/jgfouca/scream-extra/driver-mct/main/cime_comp_mod.F90:2320
#6  0x43d814 in cime_driver
        at /home/jgfouca/scream-extra/driver-mct/main/cime_driver.F90:122
#7  0x43d954 in main
        at /home/jgfouca/scream-extra/driver-mct/main/cime_driver.F90:23
```

**Comment by bogensch** [comment]
Bummer, thanks for pointing out.  Yes, I will look into this.

**Comment by bogensch** [comment]
@jgfouca fix has been pushed to repair broken restarts for DP mode.

**Review by bogensch — APPROVED** [review]

**Comment by jgfouca** [comment]
I think having this branch be the same name as the previous branch is causing problems with AT. I can tell from the error output, specifically that `ERP_R_Ln10.ne4_ne4.FDPSCREAM-ARM97.mappy_gnu` is being tested (the test we replaced with an ERS test), that it is not testing the right commit. I'm going to rename the branch and reopen a new PR.

**Pull request closed without merging**
