### PR TITLE
Add hooks to GPTL to get EAMxx timings

### PR DESCRIPTION
**Pull request by bartgol**
Simple PR, to add wrappers to GPTL calls, and have scream generate a timing file. I have tested it in standalone mode, but I need to check that the logic is correct in CIME coupled runs (I suspect/know that I have to do a micro-change).

The timing already added produce the following "extra" timers (on top of what Homme and PIO already have):
```
EAMxx::init                                    -          4        4 2.400000e+01   2.121428e+01     5.777 (     0      0)     5.014 (     1      0)
EAMxx::create_atm_processes                    -          4        4 4.000000e+00   8.440000e-04     0.000 (     0      0)     0.000 (     3      0)
EAMxx::create_grids                            -          4        4 4.000000e+00   9.650480e-01     0.241 (     2      0)     0.241 (     0      0)
EAMxx::create_fields                           -          4        4 4.000000e+00   4.532200e-02     0.012 (     0      0)     0.011 (     2      0)
EAMxx::initialize_fields                       -          4        4 4.000000e+00   5.394096e+00     1.349 (     2      0)     1.347 (     0      0)
EAMxx::initialize_output_managers              -          4        4 4.000000e+00   1.560600e-02     0.004 (     0      0)     0.004 (     1      0)
EAMxx::initialize_atm_procs                    -          4        4 4.000000e+00   1.479325e+01     4.172 (     0      0)     3.409 (     1      0)
EAMxx::Dynamics::init                          -          4        4 4.000000e+00   8.691970e-01     0.218 (     1      0)     0.217 (     2      0)
EAMxx::Macrophysics::init                      -          4        4 4.000000e+00   1.092000e-03     0.000 (     0      0)     0.000 (     3      0)
EAMxx::CldFraction::init                       -          4        4 4.000000e+00   9.100000e-05     0.000 (     0      0)     0.000 (     2      0)
EAMxx::Simple Prescribed Aerosols (SPA)::init  -          4        4 4.000000e+00   1.278254e+01     3.667 (     0      0)     2.946 (     1      0)
EAMxx::Microphysics::init                      -          4        4 4.000000e+00   7.670880e-01     0.206 (     3      0)     0.167 (     1      0)
EAMxx::Radiation::init                         -          4        4 4.000000e+00   3.633020e-01     0.104 (     3      0)     0.076 (     1      0)
EAMxx::run                                     -          4        4 1.600000e+01   1.554241e+02    39.143 (     1      0)    38.390 (     0      0)
EAMxx::Dynamics::run                           -          4        4 8.000000e+00   1.015257e+02    27.714 (     1      0)    21.694 (     0      0)
EAMxx::Macrophysics::run                       -          4        4 8.000000e+00   8.943130e-01     0.297 (     0      0)     0.195 (     2      0)
EAMxx::CldFraction::run                        -          4        4 8.000000e+00   1.259200e-02     0.004 (     0      0)     0.003 (     2      0)
EAMxx::Simple Prescribed Aerosols (SPA)::run   -          4        4 8.000000e+00   1.293605e+00     0.389 (     0      0)     0.251 (     2      0)
EAMxx::Microphysics::run                       -          4        4 8.000000e+00   1.631595e+01     4.328 (     3      0)     3.808 (     0      0)
EAMxx::Radiation::run                          -          4        4 8.000000e+00   2.801017e+01    11.834 (     0      0)     4.083 (     1      0)
```

### CODE REVIEW

**Comment by PeterCaldwell** [comment]
This is really great. I like how it automatically times each process. I remember a problem with old E3SM timers was that they overlapped each other which made it really hard to figure out what the total timing was. I like how setting up the timing at a high level ensures all pieces get timed and they don't overlap. 

My one dumb request is: could there be a header line printed just before the timings dump saying what each column means? I can never keep them straight...

**Comment by bartgol** [comment]
> My one dumb request is: could there be a header line printed just before the timings dump saying what each column means? I can never keep them straight...

Well, I cat-ed the file and grepped for `EAMxx`, so the first lines didn't show:
```
$ cat scream_timing.txt
$Id: gptl.c,v 1.157 2011-03-28 20:55:18 rosinski Exp $
'count' is cumulative. All other stats are max/min
'on' indicates whether the timer was active during output, and so stats are lower or upper bounds.

name                                          on  processes  threads        count      walltotal   wallmax (proc   thrd  )   wallmin (proc   thrd  )
EAMxx::init                                    -          4        4 2.400000e+01   2.121428e+01     5.777 (     0      0)     5.014 (     1      0)
EAMxx::create_atm_processes                    -          4        4 4.000000e+00   8.440000e-04     0.000 (     0      0)     0.000 (     3      0)
...
```

**Comment by PeterCaldwell** [comment]
Oh man, I would have wished for something more exotic if I knew the header was already there!

**Review by tcclevenger — APPROVED** [review]

**Review by AaronDonahue — APPROVED** [review]
This is great Luca!  Thanks.  Quick sanity question.  Do we know if the scream timers will have the same behavior as the implementation in EAM?  I suspect yes, because we are simply wrapping the same core code right?

In particular.  For EAM runs, the timing files will also produce hierarchical chart of timings "per core".  For example, in a typical run we might see the following:

File: ` model_timing_00010101_00000_stats`

```
name                                     on  processes  threads        count      walltotal   wallmax (proc   thrd  )   wallmin (proc   thrd  )
"CPL:INIT"                                -         24       24 2.400000e+01   1.944641e+02     8.103 (     9      0)     8.103 (    22      0)
"CPL:cime_pre_init1"                      -         24       24 2.400000e+01   1.042356e+01     0.435 (     0      0)     0.434 (    14      0)
"CPL:mpi_init"                            -         24       24 2.400000e+01   4.494100e+00     0.187 (     0      0)     0.187 (    12      0)
"CPL:ESMF_Initialize"                     -         24       24 2.400000e+01   8.750429e-02     0.004 (     2      0)     0.003 (     0      0)
"CPL:cime_pre_init2"                      -         24       24 2.400000e+01   3.847335e+00     0.160 (    21      0)     0.160 (     2      0)
"CPL:seq_infodata_init"                   -         24       24 2.400000e+01   5.958390e-01     0.025 (     1      0)     0.024 (    12      0)
``` 

and File: `model_timing_00010101_00000.00`

```
  "CPL:INIT"                                                            -       1    -       8.102728     8.102728     8.102728         0.000000
    "CPL:cime_pre_init1"                                                -       1    -       0.434609     0.434609     0.434609         0.000000
      "CPL:mpi_init"                                                    -       1    -       0.187300     0.187300     0.187300         0.000000
    "CPL:ESMF_Initialize"                                               -       1    -       0.003400     0.003400     0.003400         0.000000
    "CPL:cime_pre_init2"                                                -       1    -       0.160340     0.160340     0.160340         0.000000
      "CPL:seq_infodata_init"                                           -       1    -       0.024723     0.024723     0.024723         0.000000
```

Notice the indentation for the second file.

**Comment by bartgol** [comment]
> This is great Luca! Thanks. Quick sanity question. Do we know if the scream timers will have the same behavior as the implementation in EAM? I suspect yes, because we are simply wrapping the same core code right?
> 
> In particular. For EAM runs, the timing files will also produce hierarchical chart of timings "per core". For example, in a typical run we might see the following:
> 
> File: ` model_timing_00010101_00000_stats`
> 
> ```
> name                                     on  processes  threads        count      walltotal   wallmax (proc   thrd  )   wallmin (proc   thrd  )
> "CPL:INIT"                                -         24       24 2.400000e+01   1.944641e+02     8.103 (     9      0)     8.103 (    22      0)
> "CPL:cime_pre_init1"                      -         24       24 2.400000e+01   1.042356e+01     0.435 (     0      0)     0.434 (    14      0)
> "CPL:mpi_init"                            -         24       24 2.400000e+01   4.494100e+00     0.187 (     0      0)     0.187 (    12      0)
> "CPL:ESMF_Initialize"                     -         24       24 2.400000e+01   8.750429e-02     0.004 (     2      0)     0.003 (     0      0)
> "CPL:cime_pre_init2"                      -         24       24 2.400000e+01   3.847335e+00     0.160 (    21      0)     0.160 (     2      0)
> "CPL:seq_infodata_init"                   -         24       24 2.400000e+01   5.958390e-01     0.025 (     1      0)     0.024 (    12      0)
> ```
> 
> and File: `model_timing_00010101_00000.00`
> 
> ```
>                                                                        On  Called Recurse   Wallclock          max          min     UTR Overhead
> 
>   "CPL:INIT"                                                            -       1    -       8.102728     8.102728     8.102728         0.000000
>     "CPL:cime_pre_init1"                                                -       1    -       0.434609     0.434609     0.434609         0.000000
>       "CPL:mpi_init"                                                    -       1    -       0.187300     0.187300     0.187300         0.000000
>     "CPL:ESMF_Initialize"                                               -       1    -       0.003400     0.003400     0.003400         0.000000
>     "CPL:cime_pre_init2"                                                -       1    -       0.160340     0.160340     0.160340         0.000000
>       "CPL:seq_infodata_init"                                           -       1    -       0.024723     0.024723     0.024723         0.000000
> ```
> 
> Notice the indentation for the second file.

I don't know if that's true. But I suspect it might?

**Comment by AaronDonahue** [comment]
I'm sure we will see once we put in a CIME based test and check out the ATM contributions.

**Pull request merged**
