### PR TITLE
Switch to new ne30L128 IC with hydrometeors clipped

### PR DESCRIPTION
**Pull request by brhillman**
Switch to new ne30L128 initial condition file with qc, qi, qr, nc, ni, and nr clipped to prevent negative values.

### CODE REVIEW

**Comment by brhillman** [comment]
New input file has been uploaded to blues and permissions should be correct, so file should auto-download at case run.

**Review by ambrad — APPROVED** [review]
5 days and running on Chrys. The issue was in the first step, so this IC file clearly fixes that. Thanks!

**Review by ndkeen — APPROVED** [review]
I was going to test on PM, but it's down. I see Andrew has verified it works on Chrys, so I'm sure it's ok.

**Comment by brhillman** [comment]
@ndkeen I actually tested on perlmutter yesterday before it went down and it worked for me.

**Pull request merged**
