### PR TITLE
Move YAKL init and finalize

### PR DESCRIPTION
**Pull request by tcclevenger**
Move `yakl::init` and `yakl::finalize` into the rrtmgp interface (calling `init()` only if it has not been initialized previously).

### CODE REVIEW

**Comment by tcclevenger** [comment]
@brhillman @bartgol Maybe move finalizing yakl into `rrtmgp::rrtmgp_finalize`? The issue is that customers may want to use yakl after they use rrtmgp.

So maybe the solution should just be to leave the AD the same as it was, and for mct-coupling, add it to `finalize_scream_session`?

**Comment by tcclevenger** [comment]
> If there is a chance that someone else uses yakl in e3sm, that might still be a problem. To be fair, though, the same could be said for kokkos. So at this point I would say let's move it in `finalize_scream_session`. At some point we need to think about the fact that kokkos initialization _might_ have to be handled directly by e3sm.

What about the same for `initialize_scream_session`?

**Comment by bartgol** [comment]
> > If there is a chance that someone else uses yakl in e3sm, that might still be a problem. To be fair, though, the same could be said for kokkos. So at this point I would say let's move it in `finalize_scream_session`. At some point we need to think about the fact that kokkos initialization _might_ have to be handled directly by e3sm.
> 
> What about the same for `initialize_scream_session`?

You mean move yakl init inside `initialize_scream_session`? I'm ok with that.

**Comment by PeterCaldwell** [comment]
I'm not sure if this is relevant or too late to make a difference, but I'm unclear whether YAKL will ever be used for anything outside of RRTMGP. I think it would be worth asking Matt Norman and Ben directly before getting wrapped around the spindle about how to support it outside RRTMGP... I can ping them via slack if you want, but it might make more sense for one of you to do it since you have a more detailed understanding of the situation...

**Comment by tcclevenger** [comment]
> I'm not sure if this is relevant or too late to make a difference, but I'm unclear whether YAKL will ever be used for anything outside of RRTMGP. I think it would be worth asking Matt Norman and Ben directly before getting wrapped around the spindle about how to support it outside RRTMGP... I can ping them via slack if you want, but it might make more sense for one of you to do it since you have a more detailed understanding of the situation...

Definitely not too late. I'll ping in slack.

**Comment by tcclevenger** [comment]
To summarize, for now Ben and Matt are OK with this being added to the radiation interface.

**Review by bartgol — APPROVED** [review]

**Pull request merged**
