### PR TITLE
Verify input file has same dimensions as populated fields

### LINKED ISSUE #1329: IO input silently continues when the nc file has the wrong dimensions
You can read an IC file with N columns while running a grid with M columns, and IO never complains. We need to figure out why the code does not crash, and then make it crash if the dimensions of a file in the nc file do not match the dimensions of the scream field.

### PR DESCRIPTION
**Pull request by AaronDonahue**
This commit introduces a check to scorpio_input.h/cpp that checks the dimension lengths in the input file against the dimension lengths of individual fields to be populated.  If they don't match then it throws an error.

This should remove the hacky/buggy feature that allowed some tests to use an initial condition file with number of columns = X but declare the problem size to have number of columns = Y, where X != Y.

It also stops a user from accidentally using an initial condition file that does not match the problem they are running.

Lastly, this commit updates the input.yaml control files for all of the standalone tests that were doing exactly that.

Fixes #1329

### CODE REVIEW

**Comment by AaronDonahue** [comment]
@bartgol , this PR bought up a point about our stand alone testing.  We have been psuedo running ne2 by specifying the grid size to be 218 but using the ne4 init condition file.  Currently I've bumped the tests up to 866 columns matching the init but we should probably keep the 218 and just generate a new init condition file with an ne2 configuration.

I'm pinging you to get some feedback on that thought.

**Comment by bartgol** [comment]
> @bartgol , this PR bought up a point about our stand alone testing. We have been psuedo running ne2 by specifying the grid size to be 218 but using the ne4 init condition file. Currently I've bumped the tests up to 866 columns matching the init but we should probably keep the 218 and just generate a new init condition file with an ne2 configuration.
> 
> I'm pinging you to get some feedback on that thought.

To be honest, I've been thinking for a while that we should instead init our fields on the fly for our standalone tests. I don't think there's _a ton_ of conditions that the inputs need to verify, in order to avoid nonsense calculations. Some of these can be handled by using a proper pdf (e.g., non-negative values, or use perturbations from a constant value), some others are slightly more complex, but not too bad (e.g., pressure increasing is simply the column scan of a non-negative quantity).

That way we would stress test a bit more our physics (e.g., what if one of the if statements in p3 is never triggered in standalone system tests?), and we could also change the number of cols (for physics-only tests) to whatever we want (e.g., run physics only tests with a specific set of values for ncols, to study perf dependence on workload).

**Comment by AaronDonahue** [comment]
>That way we would stress test a bit more our physics (e.g., what if one of the if statements in p3 is never triggered in standalone system tests?), and we could also change the number of cols (for physics-only tests) to whatever we want (e.g., run physics only tests with a specific set of values for ncols, to study perf dependence on workload).

Yes, that would probably be much better for all of the physics based tests, especially since we don't have to worry about consistency across adjacent columns.  

It's a bit different for any of the tests w/ dynamics.  Maybe the right thing to do would be to focus on those tests for now since they will need a valid initial condition file (right?) and then create a git-issue to improve the physics-only stand-alone tests to have in-house values.  Thoughts?

**Comment by bartgol** [comment]
Yeah, we don't need to do that now. Feel free to choose the approach you think it's best for this PR.

**Comment by AaronDonahue** [comment]
Fixes #1851

**Comment by bartgol** [comment]
@AaronDonahue This PR fell behind quite a bit. #2361 will take care of checking dimensions though, so maybe we can close this and push for that one to complete?

**Pull request closed without merging**
