### PR TITLE
Make mpassi default for SCREAM F-compsets

### PR DESCRIPTION
**Pull request by wlin7**
The following compsets are changed to use MPASSI for prescribed data
ice mode.

. F2010-SCREAM-LR and F2010-SCREAM-HR
. F2010-SCREAM-LR-DYAMOND1 and F2010-SCREAM-HR-DYAMOND1
. F2010-SCREAM-LR-DYAMOND2 and F2010-SCREAM-HR-DYAMOND2

The aliases for the corresponding compsets that use CICE prescribed
data ice mode need to be explicitly appended with '-CICE'.

The tests that previously using F2010-SCREAM-HR or F2010-SCREAM-LR
change to use grid ne4pg2_oQU480. The tests using ne4pg2_ne4pg2 need
to use F2010-SCREAM-HR-CICE and F2010-SCREAM-LR-CICE after this PR.

[BFB] when matching compsets are used. Reports would show diffs due
      to test name changes in grid or compset.

### CODE REVIEW

**Comment by wlin7** [comment]
Hi @PeterCaldwell , the following tests are currently replaced, with the grid ne4pg2_oQU480 to go with mpassi.
Should we still maintain the tests for the legacy "*-CICE" compsets?

```
            "SMS_D.ne4pg2_ne4pg2.F2010-SCREAM-HR",
            "SMS_D.ne4pg2_ne4pg2.F2010-SCREAM-LR",
            "ERS.ne4pg2_ne4pg2.F2010-SCREAM-HR",
            "ERS.ne4pg2_ne4pg2.F2010-SCREAM-LR",
            "ERP.ne4pg2_ne4pg2.F2010-SCREAM-HR.eam-double_memleak_tol",
            "ERP.ne4pg2_ne4pg2.F2010-SCREAM-LR.eam-double_memleak_tol",
            "REP.ne4pg2_ne4pg2.F2010-SCREAM-HR",
            "REP.ne4pg2_ne4pg2.F2010-SCREAM-LR",
            "PEM.ne4pg2_ne4pg2.F2010-SCREAM-HR",
            "PEM.ne4pg2_ne4pg2.F2010-SCREAM-LR",
```

**Comment by PeterCaldwell** [comment]
> Hi @PeterCaldwell , the following tests are currently replaced, with the grid ne4pg2_oQU480 to go with mpassi. Should we still maintain the tests for the legacy "*-CICE" compsets?

We should definitely do all the tests you listed above for MPASSI instead of CICE. In addition (and I think what you were actually asking), we should include some tests for the CICE configurations because "if you don't test it, you shouldn't keep it around". I don't think we need to do all these tests though - just enough to catch if something egregious goes wrong. Perhaps just an SMS_D for HR and LR? Or an ERS instead? Does anyone have a stronger opinion for the minimum set of tests we should do?

**Review by PeterCaldwell — APPROVED** [review]
Looks good. Nice that you also added F2010 compsets which were missing.

**Comment by wlin7** [comment]
>  Perhaps just an SMS_D for HR and LR? Or an ERS instead? Does anyone have a stronger opinion for the minimum set of tests we should do?

Totally agreed, @PeterCaldwell . We only need the minimum tests for the -CICE compsets, as all the other type of tests are  equivalently covered by the ones with mpassi. The SMS_D for HR- and LR-ICE are added back to the test suite.

**Review by PeterCaldwell — APPROVED** [review]

**Comment by bartgol** [comment]
The standalone testing on mappy failed due to a known issue regarding new sub-submodules (Jim and I decided to not spend time on fixing our scripts for this corner case, since it happens once a year or less). Since the PR only touches CIME stuff, I added the label to skip standalone testing.

v1 tests failed for the same reason of the standalone tests, but since the PR simply adds v0 tests, I removed the CIME label (which implies v0 + v1) and added just tge v0 one.

Finally, I think v0 tests are expected to fail, due to lack of baselines, right? So tests failing with reason 'BASELINE' can prob be ignored. But there are 4 RUN fails:
```
FAIL ERP.ne4pg2_oQU480.F2010-SCREAM-HR.mappy_gnu.eam-double_memleak_tol (phase RUN)
FAIL ERP.ne4pg2_oQU480.F2010-SCREAM-LR.mappy_gnu.eam-double_memleak_tol (phase RUN)
FAIL PEM.ne4pg2_oQU480.F2010-SCREAM-HR.mappy_gnu (phase RUN)
FAIL PEM.ne4pg2_oQU480.F2010-SCREAM-LR.mappy_gnu (phase RUN)
```
Any idea why these fail? If you guys don't have access to mappy, we can retrieve logs, so you can debug.

**Comment by AaronDonahue** [comment]
@PeterCaldwell and @wlin7 , this PR seems to have stalled but I think it could be technically ready to merge.  Can you take another look and determine if it can be manually merged?

**Review by ndkeen — APPROVED** [review]

**Comment by wlin7** [comment]
Please note that this PR was intended for SCREAMv0. Probably not useful to merge now. With SCREAMv0 and without this PR, we can still use MPASSI for sea ice, simply by adding '-MPASSI' to the compset.

The branch to make mpassi default along with mosart for river model is for v1 is  wlin/atm/fcase_with_mosart_mpassi.

**Comment by PeterCaldwell** [comment]
This PR is the SCREAMv0 version of #1861, right @wlin7 ?

**Comment by wlin7** [comment]
Yes, Peter. Do we want to make it default as well? SCREAMv0 can run with mpassi without this PR, just need to attach '-MPSSAI' to the compset.

**Comment by PeterCaldwell** [comment]
Hmm. I guess I don't really care what we do for v0 since we're trying to transition to v1. Maybe we should just close this PR? Though I guess we need v0 for RRM and DP still and it would probably be good to have v0 and v1 as close to each other as possible. So - I don't have a strong preference but I guess we might as well integrate this before we forget?

**Comment by wlin7** [comment]
I thought I closed the PR with that comment a few days ago. Sounds good to have v0 and v1 close to each other, @PeterCaldwell . I am going to resolve the conflict in tests.py first and revisit if the tests are all ok. Following your suggestion for v1, we will also retain one compset for CICE, with '-CICE' in the compset name.

**Review by brhillman — APPROVED** [review]

**Comment by AaronDonahue** [comment]
This is a few months old without any movement.  @PeterCaldwell and/or @wlin7 .  Should we rebase this off of master and keep it alive?  Or go ahead and close it?

**Comment by PeterCaldwell** [comment]
I think we can just give up on this PR. v0 is dead to us ;-)

**Pull request closed without merging**
