### PR TITLE
Test scripts upgrades

### PR DESCRIPTION
**Pull request by bartgol**
Small mod and upgrade to test-all-scream: 

 - mod: the different tests are built in different subdirectories, so that different build types can run concurrently, without trashing each other's results

 - -p flag: the user can now pass the -p flag, so that the required tests (so far only 'dbg', 'fpe', and 'sp') are run concurrently.
 - --baseline-dir: the user can specify a directory where the baseline are. If so, the -b/--baseline option (for the git ref of baselines to be built) will be ignored, and the baseline build stage will be skipped
 - --no-tests: the test stage will be skipped. This allows to only build baselines.

Timings on my workstation (10x2 cores), with CTEST_PARALLEL_LEVEL=19:

```
master:
  real  8m27.587s
  user  63m1.411s
  sys 3m59.974s

branch (with -p flag):
  real  6m58.880s
  user  63m30.425s
  sys 4m1.720s

```
Not a 'huge' speedup, but still quite noticeable. I still have to test it on other platforms.

Bonus feature: in case of failed tests, we cat the LastTestsFailed*.log file generated by ctest. This helps getting info from the AT output inside a PR, since the AT only reports the last 100 lines of output (and if the test failing was among the first ones, you don't even see what test failed). We could even think of re-running the failed tests, to make sure we also get an output to from the failing tests in the last 100 lines of output.

Note: unfortunately, although the build phase is perfectly parallelized over the available processors, the run phase (for both baselines and testing) seems to overlap the execs from different builds on the same cores. This does not happen for all the executables, but I see it happening quite a few times (while I don't see any two ccplus1 running on the same cores).

I suspect this is due to rum_cmd executing in a subshell, causing loss of processor binding (although this does not explain

### CODE REVIEW

**Comment by jgfouca** [comment]
Looks like you're adding a new feature, lmk when done and I'll re-review.

**Comment by bartgol** [comment]
Timings on my workstation:

```serial:

real  5m18.783s
user  37m43.389s
sys 2m7.448s

parallel with taskset:

real  3m49.093s
user  35m15.515s
sys 3m24.028s
```

This is for a run that does _not_ create baselines, i.e., it uses the new `--baseline-dir` option, and only builds/runs the tests.

**Comment by bartgol** [comment]
Unfortunately, the AT keeps failing due to bowman being continuously filled by kokkos jobs (I have contacted our IT staff to see if we can increase capacity for bowman jenkins jobs), which cause the AT to timeout and fail.

Meanwhile, travis seems to show tests passing.

I manually launched a test-all-scream job on bowman, to see what the timing would be with the -p flag. My run time was 25m, compared to the average 55m that the nightlies have been taking. So I think this could really speed up our CI process.

I will merge as soon as I verify things work on all our testbeds.

**Comment by bartgol** [comment]
Manual test on blake

```
serial:
real	13m46.170s
user	167m38.192s
sys	6m49.633s

parallel:
real	7m42.338s
user	179m1.275s
sys	6m42.616s
```

**Pull request merged**
