### PR TITLE
Remove a pointless test.

### PR DESCRIPTION
**Pull request by ambrad**
Remove test_p3_main. It was used early in development to keep things
stable. It's superseded by test_p3_ic.

test_p3_main gives an FPE for a trivial reason that is essentially b/c this was
a build test, not a run one. test_p3_ic does not have an FPE b/c it gets the
proper data to run p3_main.

### CODE REVIEW

**Comment by ambrad** [comment]
I'm going to fix a few other little things, so don't merge this until I've removed the "[WIP]" tag.

**Comment by ambrad** [comment]
At this point, GPU build is working and ctests pass. I'm not convinced everything is perfect, but I'm going to move on to KNL now.

**Comment by ambrad** [comment]
@jgfouca @bartgol this PR is ready to be merged into Jim's PR.

I recommend merging before you do anything more in that PR, is this PR cleans up several issues in the Cuda and KNL builds and tests.

Luca, fields_ut is broken right now b/c of the compiler error; there is a pragma message to bring attention to it.

**Comment by bartgol** [comment]
I already fixed the issue related to field emplacing in the repo on jim's branch. Is that what the compiler errors were in field_ut?

**Comment by ambrad** [comment]
@bartgol, great. I merged that PR and rm'ed the pragma message.

**Pull request merged**
