### PR TITLE
Fix issues with GLL output for PG2 CIME cases

### PR DESCRIPTION
**Pull request by tcclevenger**
- Update output manager to deal with conflicting `ncol` lengths (PG2 and GLL).
- Add homme states to internal fields so they can be int output
- Add GLL output of homme states to test/default output

### CODE REVIEW

**Comment by bartgol** [comment]
Yes, this will cause some diffs for v1 tests. The standalone fails are another issue though.

**Comment by tcclevenger** [comment]
@bartgol All fails as expects (CIME tests have 0 DIFFS, just additional fields in output)

**Review by bartgol — APPROVED** [review]

**Review by AaronDonahue — APPROVED** [review]

**Comment by tcclevenger** [comment]
I'm currently attempting to plot some field data to verify GLL output matches what we expect. I'll update when we can force merge (also will let the AT run again).

**Comment by tcclevenger** [comment]
@AaronDonahue Verified `_dyn` output is as expected for both np4 and pg2 case. Blake passes, mappy fails with expected diffs, weaver passed before the AT issues (not changes to the code since). I'm ok to merge this.

**Comment by bartgol** [comment]
Looks like we need to fix conflicts, so we may as well get another AT round when you push.

**Comment by AaronDonahue** [comment]
@tcclevenger , Looks like the fails are all DIFFs on mappy.  Are these expected.  Can this PR be merged?

**Pull request merged**
