### PR TITLE
Micro optimization to the Mask structure utilities.

### PR DESCRIPTION
**Pull request by bartgol**
Two micro opts.

- When creating a mask as a result of comparison of two pack-type inputs,
  there's no need to use if statements. Simply stuff the output mask
  with the comparison result for all entries.
- As a consequence to the above, we now write all entries in the for loop,
  so the mask can be created with the default c-tor (saves one for loop).

### CODE REVIEW

**Comment by ambrad** [comment]
Here: https://github.com/E3SM-Project/scream/blob/140d9dbfcc51775239f46d3f0cbb5339b8ea6e52/components/scream/ekat/src/ekat/scream_pack.hpp#L117
can also remove the value-initializing ctor.

**Comment by bartgol** [comment]
> can also remove the value-initializing ctor.

I ketp that ctor, in case someone is in need of creating a mask that defaults to true.

**Comment by bartgol** [comment]
@jgfouca I fixed a couple of bugs, no major changes. But since it's been a long time, I thought I'd ping one of the reviewers again.

**Comment by bartgol** [comment]
Merging, since only minor fixes happened after @jgfouca positive review.

**Pull request merged**
