### PR TITLE
Add scream machine files for the LC machine: Lassen

### PR DESCRIPTION
**Pull request by AaronDonahue**
Add machine files for the Livermore Computing machine Lassen.

    In order to build scream on Lassen the user needs the following setup,
    
    module purge && module load gcc cuda cmake spectrum-mpi netcdf && export LLNL_USE_OMPI_VARS='y'
    export OMPI_CXX=PATH_TO_SCREAM/externals/kokkos/bin/nvcc_wrapper
    cmake -DCMAKE_CXX_COMPILER=$(which mpicxx) -C PATH_TO_SCREAM/components/scream/cmake/machine-files/lassen.cmake PATH_TO_SCREAM/components/scream
    make -j8

### CODE REVIEW

**Comment by AaronDonahue** [comment]
for sure! I would be happy to do that, and it would be cleaner.  I'll let you know if I need help.

**Comment by AaronDonahue** [comment]
I've pushed new commits which I think address your requested changes @jgfouca .  Let me know if you want me to change anything else.

**Comment by jgfouca** [comment]
This looks better. Did you test it with test-all-scream?

Also, I'd like to understand why we had to tell CMake to add c++11 manually.

**Comment by AaronDonahue** [comment]
@jgfouca , this version of the branch builds and passes test-all-scream.

**Comment by jgfouca** [comment]
Nice!

**Pull request merged**
