### PR TITLE
Scream/new quartz mach files for gcc-specific flags

### PR DESCRIPTION
**Pull request by mtaylo12**
This PR adds two quartz machine files and updates the original to support SCREAM standalone testing under both gcc and intel builds, as opposed to previous support for solely intel. The gcc build at this point has only been tested within the E3SM Spack package (under development).

### CODE REVIEW

**Comment by AaronDonahue** [comment]
Looks good, I'm going to manually test this on quartz then I can approve the PR

**Review by AaronDonahue — APPROVED** [review]

**Comment by oksanaguba** [comment]
Not sure i read this PR correctly, is it coming from scream branch to e3sm master?

**Comment by bartgol** [comment]
> Not sure i read this PR correctly, is it coming from scream branch to e3sm master?

Unfortunately github is not very clear when there is a PR across forks. In particular, github uses `$org:$branch` and `$user:$branch`, while it would be cleaner to use `$org/$repo:$branch` and $user/$repo:$branch`. But if you hover over the branch name, the link shows the correct repo.

**Comment by oksanaguba** [comment]
thanks @bartgol ! i was wondering why file diff was actually showing correct files from scream.

**Comment by AaronDonahue** [comment]
@bartgol , is there a reason this hasn't been automerged yet?  I approved it and have it set to integrate without testing.  Is it because it is a branch from a fork?

**Comment by bartgol** [comment]
Yes. It comes from a fork, so it needs pre-test inspection by label. The AT message above explains it. I'll add the label.

**Comment by AaronDonahue** [comment]
ahhhh, good to know.  Thanks!

**Comment by AaronDonahue** [comment]
Sadly I often ignore what the AT has to say :-) unless it tells me everything has PASSED

**Pull request merged**
