### PR TITLE
EAMxx: Modify microphysics interface to include sethet (washout rates)

### PR DESCRIPTION
**Pull request by odiazib**
An existing EAMxx interface (`eamxx_mam_microphysics_process_interface.cpp`) is modified to include the invocation of the washout rates for gases. 

Since the CMake option, `SCREAM_ENABLE_MAM`, is always `ON`, these codes are always compiled with the EAMxx codebase, but this interface can be turned off/on using the namelist flags. 

### Output variables
This process computes `het_rates` that are used in gas phase chemistry

### Testing
We have existing tests for this interface, so we didn't add any new tests. We have a suite of validation tests in the MAM4xx repo to validate `sethet` process

The `atmchange` command to invoke this process in a CIME simulation is:

`./atmchange physics::atm_procs_list="mac_aero_mic,rrtmgp,mam4_aero_microphys`

To set up a test with the above configuration, use the following commands:
```
cd cime/scripts
./create_test SMS_D_P32x1_Ln5.ne4pg2_oQU480.F2010-SCREAMv1-MPASSI.<machine>_<compiler>.scream-mam4xx-aero_microphysics -t <test id> -p <project id>
```
Where,
`<machine>` is the machine name
`<compiler>` is the compiler to use on the machine
`<test id >` is a unique string test identifier
`<project id>` is the allocation project to charge

`scream-mam4xx-aero_microphysics` is the test modifier that adds `mam4_aero_microphys` to the `atm_procs_list` process list and increases the number of tracers to 41.

For `ne30pg2` grid, use the following command:
```
./create_test SMS_D_P32x1.ne30pg2_oECv.F2010-SCREAMv1-MPASSI.<machine>_<compiler>.scream-mam4xx-aero_microphysics -t <test id> -p <project id> 
```

### New input data
No new input data

## Figures from model analysis
We ran a simulation using ne30 grid with only microphysics process turned on. Here are the gas and aerosol species burden with (labeled `sethet`) and without (labeled `ctl`) the sethet process:
image

image

### Standalone Test Timings (Compy):
We will upload the timings once the PR is reviewed and approved

### CODE REVIEW

**Review by singhbalwinder — APPROVED** [review]

**Comment by singhbalwinder** [comment]
@odiazib has moved this PR from E3SM to Scream as E3SM is missing a PR that this PR depends upon. Hopefully, we can merge it before we merge the repos (E3SM and Scream).

**Comment by rljacob** [comment]
Which PR exactly do you need?

**Comment by singhbalwinder** [comment]
>Which PR exactly do you need?

We need PR #3108

**Review by singhbalwinder — DISMISSED** [review]

**Review by singhbalwinder — APPROVED** [review]

**Review by kaizhangpnl — APPROVED** [review]
Most of relevant changes (and the original code development) were made in the mamxx (external) repo (https://github.com/eagles-project/mam4xx/blob/fdbb0816c5c0c541265ec17f544908da935d8af6/src/mam4xx/mo_sethet.hpp). Therefore, there are only minor code changes in this repo. The EALGES team has performed simulations to test the new feature (w. vs. w/o) and the result (see above: to be posted) suggests the feature works as expected, at least qualitatively. On the other hand, we need more detailed evaluation of the aerosol/chemistry budget to make sure the sulfur chemistry and sulfate formation are reasonably simulated. This will need additional code implementation (for process rates output at multiple places) and significant effort for diagnostic tool development/adjustment, which is out of scope for this PR.

**Comment by singhbalwinder** [comment]
Thanks, Kai! I have uploaded the figures in the PR description.

The PR Is failing the expected tests. CUDA tests are not running on AT. I have manually run a CUDA test on PM-GPU, and the standalone test (in single precision mode) ran fine without emitting any new warnings.

**Pull request merged**
