### PR TITLE
Add PEM test to med res suite

### PR DESCRIPTION
**Pull request by jgfouca**
We want a test to catch the non-BFB-when-PES-changes problem
that we have been struggling with.

### CODE REVIEW

**Comment by jgfouca** [comment]
I am a bit hesitant to merge this since it would be a failing test that would show up on the dashboard (not too bad) and block PRs due to AT fails (very bad).

**Comment by PeterCaldwell** [comment]
Great point, Jim. Perhaps we should add it to a suite that is used for nightlies but not for AT?

**Comment by jgfouca** [comment]
@PeterCaldwell , we do run the medres suite on perlmutter. We could put it there but it would not get much visibility.

**Comment by PeterCaldwell** [comment]
Maybe this task is a bit contrived - I think if we distill down to the essence of what we're looking for, it's that we don't want to forget PEM exists. We definitely want to add PEM to our test suite, but only once we actually start passing tests. I think adding PEM to medres now is fine as a reminder that we want to put it somewhere more visible later but don't want to totally forget about it now...

**Comment by jgfouca** [comment]
@PeterCaldwell , OK I moved it to medres and increased the grid to ne30.

**Review by PeterCaldwell — APPROVED** [review]

**Pull request merged**
