### PR TITLE
Port 2 shoc_length functions

### PR DESCRIPTION
**Pull request by tcclevenger**
Port `compute_brunt_shoc_length` and `check_length_scale_shoc_length` to C++

### CODE REVIEW

**Comment by ambrad** [comment]
Reminder in case this was forgotten: this PR still requires the shoc.F90 C++ code-path calls.

**Comment by tcclevenger** [comment]
> Reminder in case this was forgotten: this PR still requires the shoc.F90 C++ code-path calls.

Yes, good call.

**Comment by tcclevenger** [comment]
Forgot about non-bfb change (`bfb_sqrt()` in shoc.F90, see PR: https://github.com/E3SM-Project/scream/pull/647). I will request reviews once that is merged.

**Comment by tcclevenger** [comment]
All necessary PRs have been merged and all tests pass.

**Review by ambrad — APPROVED** [review]

**Review by jeff-cohere — APPROVED** [review]

**Review by jeff-cohere — APPROVED** [review]

**Pull request merged**
