### PR TITLE
Travis Continuous Integration with Clang

### PR DESCRIPTION
**Pull request by mfdeakin-sandia**
Enables continuous integration testing with clang, and with address sanitizer.

### CODE REVIEW

**Comment by mfdeakin-sandia** [comment]
This isn't ready yet due to this bug: https://stackoverflow.com/questions/50024731/ld-unrecognized-option-push-state-no-as-needed

**Comment by bartgol** [comment]
Should we close this outstanding PR? I don't think anyone is taking up this challenge anytime soon...

**Comment by jgfouca** [comment]
I'm OK to close it.

**Comment by bartgol** [comment]
Closing because stale and probably very out of sync with master.

**Pull request closed without merging**
