### PR TITLE
Suppress warnings from Kokkos

### PR DESCRIPTION
**Pull request by jgfouca**

### CODE REVIEW

**Comment by jgfouca** [comment]
This is more of a discussion topic for now.

In a personal project, in which I followed my usual pattern of aggressively turning on compiler warnings, I recent integrated some kokkos capabilities. I was upset to see that, whenever one of my files included a kokkos header, I got blasted with thousands of warnings coming from Kokkos. The approach in this PR solved the problem.

Issues that we will have to deal with is that we support additional compilers other than GCC and also this approach does not seem to work with CUDA, even if GCC is the serial compiler.

**Comment by bartgol** [comment]
Does this suppress a warning if, say, I use a deprecated function from Kokkos?

**Comment by bartgol** [comment]
What about including kokkos include dir as a system include, like

`target_include_directories(targetName SYSTEM ${KOKKOS_INCLUDE_DIR})`

Does this solve the problem? If so, I'd use that, which is more portable.

More generally, all `SCREAM_TPL_INCLUDE_DIRS` should be included as system directories, precisely cause we don't want warning from them.

**Comment by jgfouca** [comment]
@bartgol , 

From the docs:
>  All warnings, other than those generated by ‘#warning’ (see Diagnostics), are suppressed while GCC is processing a system header.

So, it depends on how kokkos deprecated functions are implemented.

**Comment by jgfouca** [comment]
> target_include_directories(targetName SYSTEM ${KOKKOS_INCLUDE_DIR})

That was the first thing I tried and it didn't seem to have any effect.

**Comment by bartgol** [comment]
> @bartgol ,
> 
> From the docs:
> 
> > All warnings, other than those generated by ‘#warning’ (see Diagnostics), are suppressed while GCC is processing a system header.
> 
> So, it depends on how kokkos deprecated functions are implemented.

I think they use the `__deprecated__` attribute (with whatever variant the compiler uses). I don't think they use the `#warning` syntax.

**Comment by bartgol** [comment]
Sorry, I accidentally clicked on close and comment.

**Comment by ambrad** [comment]
Is anyone waiting for my review on this? If so, sorry for the delay. I removed myself as a reviewer. I'm fine with whatever you and Luca decided.

**Pull request merged**
