### PR TITLE
Fix initialization of accumulated fields

### LINKED ISSUE #2396: Error! Month out of bounds with a set of new yaml outputs
I'm trying to test some new outputs from Chris T -- and rather than wait for the Q to try on 2048 nodes with ne1024, I'm trying with ne30.

Here is an error using these 4:
```
    ./atmchange output_yaml_files="/lustre/orion/cli115/proj-shared/terai/Cess/v1_output/scream_output.Cess.23hourly_QcQiNcNi.yaml" #aa
    ./atmchange output_yaml_files+="/lustre/orion/cli115/proj-shared/terai/Cess/v1_output/scream_output.Cess.23hourly_QrNrQmBm.yaml" #bb
    ./atmchange output_yaml_files+="/lustre/orion/cli115/proj-shared/terai/Cess/v1_output/scream_output.Cess.3hourlyAVG_noremap.yaml" #cc
    ./atmchange output_yaml_files+="/lustre/orion/cli115/proj-shared/terai/Cess/v1_output/scream_output.Cess.3hourlyINST_noremap.yaml" #dd
```
And with trial-n-error, I see it's the last one `scream_output.Cess.3hourlyINST_noremap.yaml` that causes the trouble.

```
7:   what():  /global/cfs/cdirs/e3sm/ndk/repos/maf-jun20/components/eamxx/src/share/util/scream_time_stamp.cpp:20: FAIL:
7: mm>=1 && mm<=12
7: Error! Month out of bounds. Did you call `days_in_month` with yy and mm swapped?
```

In `scream_output.Cess.3hourlyINST_noremap.yaml`

```
Averaging Type: Instant
Fields:
  Physics PG2:
    Field Names:
    - SeaLevelPressure
    - horiz_winds_at_model_bot
    - wind_speed_10m
    - horiz_winds_at_925hPa
    - horiz_winds_at_850hPa
    - horiz_winds_at_700hPa
    - horiz_winds_at_500hPa
    - horiz_winds_at_300hPa
    - ZonalVapFlux
    - MeridionalVapFlux
    - T_2m
    - qv_2m
    - T_mid_at_925hPa
    - T_mid_at_850hPa
    - T_mid_at_700hPa
    - T_mid_at_500hPa
    - T_mid_at_300hPa
    - RelativeHumidity_at_925hPa
    - RelativeHumidity_at_850hPa
    - RelativeHumidity_at_700hPa
    - RelativeHumidity_at_500hPa
    - RelativeHumidity_at_300hPa
    - z_mid_at_925hPa
    - z_mid_at_850hPa
    - z_mid_at_700hPa
    - z_mid_at_500hPa
    - z_mid_at_300hPa
    - SW_clrsky_flux_up_at_model_top
    - SW_flux_up_at_model_top
    - SW_flux_dn_at_model_top
    - LiqWaterPath
    - PrecipLiqSurfMassFlux
    - PrecipIceSurfMassFlux
    - IceWaterPath
    - nc
    - qc
    - qi
    - cldfrac_tot_for_analysis
    - cldfrac_liq
    - omega_at_500hPa
    - omega_at_700hPa
    - PotentialTemperature_at_700hPa
    - PotentialTemperature_at_1000hPa
Max Snapshots Per File: 240
filename_prefix: output.scream.Cess.3hourlyINST_noremap
output_control:
  Frequency: 3
  MPI Ranks in Filename: false
  frequency_units: nhours
```

```
#0  0x00007fffe6dd3cbb in raise () from /lib64/libc.so.6
#1  0x00007fffe6dd5355 in abort () from /lib64/libc.so.6
#2  0x00007fffe895d5b9 in __gnu_cxx::__verbose_terminate_handler () at ../../../../cpe-gcc-12.2.0-202211182106.97b1815c41a72/libstdc++-v3/libsupc++/vterminate.cc:95
#3  0x00007fffe8968bea in __cxxabiv1::__terminate (handler=<optimized out>) at ../../../../cpe-gcc-12.2.0-202211182106.97b1815c41a72/libstdc++-v3/libsupc++/eh_terminate.cc:48
#4  0x00007fffe8968c55 in std::terminate () at ../../../../cpe-gcc-12.2.0-202211182106.97b1815c41a72/libstdc++-v3/libsupc++/eh_terminate.cc:58
#5  0x00007fffe8968ef8 in __cxxabiv1::__cxa_rethrow () at ../../../../cpe-gcc-12.2.0-202211182106.97b1815c41a72/libstdc++-v3/libsupc++/eh_throw.cc:136
#6  0x0000000000619799 in scream_init_atm ()
#7  0x000000000061472a in atm_init_mct$atm_comp_mct_ ()
#8  0x000000000046af20 in component_init_cc$component_mod_ ()
#9  0x0000000000437cde in cime_init$cime_comp_mod_ ()
#10 0x0000000000468aa3 in main ()
```

`/lustre/orion/cli115/proj-shared/noel/e3sm_scratch/maf-jun19/t.maf-jun19.F2010-SCREAMv1.ne30pg2_ne30pg2.frontier-scream-gpu.n011t8x6.vth200.co-aabbccdd`

I also verified the same error happens with ne1024.

### PR DESCRIPTION
**Pull request by bartgol**
We were having issues when using instant output with accumulated fields because:

1. AD resets accumulation start time at top of run method
2. during t=0 output (inside init), accum start time was invalid, causing a bad calculation of dt: `dt=t-t_start`

The fix is to reset accumulated fields after fields are created, as well as at the _end_ of the run method.

Fixes #2396

### CODE REVIEW

**Review by ndkeen — COMMENTED** [review]
Are you changing the name of an output variable here?  

      - precip_liq_surf_mass
     to
      - PrecipLiqSurfMassFlux
    ?

**Comment by bartgol** [comment]
> Are you changing the name of an output variable here?
> 
> ```
>   - precip_liq_surf_mass
>  to
>   - PrecipLiqSurfMassFlux
> ?
> ```

No, I added one. The former one is the total mass, while the latter is the mass flux (mass / rho*dt). Although they are very much related, the former is a model variable (computed by I think P3), while the latter is a diagnostic variable, which was triggering some additional problems.

**Review by AaronDonahue — DISMISSED** [review]
looks good to me, although I will defer to other reviewers who may want to test that this works.

**Review by tcclevenger — APPROVED** [review]

**Comment by bartgol** [comment]
@tcclevenger I was adding a mod to the precip fluxes diag classes, when I realized they are pretty much the same diag, so I went ahead and unified them. Since you worked on the total diag, perhaps you would like to give a look to the last part of this PR...

**Review by tcclevenger — DISMISSED** [review]
Looks good. I think the `VerticalLayer` diag could be made to match more of the layout you have (never liked setting a param "diag_name"). Maybe I'll do that in the future.

**Review by tcclevenger — APPROVED** [review]

**Pull request merged**
