### PR TITLE
Clean up summit machines

### PR DESCRIPTION
**Pull request by jgfouca**
Merge summit-gpu and summit-cpu. Use gpu substring in compiler names to identify GPU builds.

### CODE REVIEW

**Comment by jgfouca** [comment]
Tested via `create_test e3sm_scream_v1 --compiler=gnugpu`. Just occurred to me that I should probably test `--compiler=gnu` too so I will do that now.

**Comment by jgfouca** [comment]
Adding @bartgol because I touched some homme stuff.

**Comment by ambrad** [comment]
I think a lot of this -- at least the mods in the Homme directory -- should go in the upstream repo.

**Comment by jgfouca** [comment]
@ambrad , the changes to cime_config in this PR are basically undoing changes that were made in SCREAM that were never made upstream so this PR should bring us into closer alignment with upstream E3SM.

I'm less familiar with how `summit-gpu` spread through homme. I was thinking it must have happened in SCREAM since there never was a `summit-gpu` in upstream e3sm.

**Comment by ambrad** [comment]
I might be missing something, but I spot-checked a few Homme changes, and to me it looks like the mods you're making are in places that are identical to the upstream.

**Comment by jgfouca** [comment]
@ambrad , ah ok. I can maybe throw out the homme mods if homme is managing its own machine names and not getting them from CIME or SCREAM. @bartgol ?

**Comment by jgfouca** [comment]
Summit+gnu (no gpu) was 100% PASS for e3sm_scream_v1

**Comment by bartgol** [comment]
I agree with @ambrad : all mods in `cime_config` and `components/homme` should come from upstream.

**Comment by jgfouca** [comment]
@bartgol , I'm going to need a bit more info. Does homme manage it's own it own machine names? Where did summit-gpu come from?

The changes to cime_config cannot go into upstream master because this PR is undoing changes that were made on the SCREAM side that were never made upstream.

**Comment by ambrad** [comment]
The standalone Homme build does. Looks like summit-gpu came into the standalone Homme build system in this commit: https://github.com/E3SM-Project/E3SM/commit/d3483227ee015d7d9a13fe6e076f67a998f70ca1

**Comment by bartgol** [comment]
> The changes to cime_config cannot go into upstream master because this PR is undoing changes that were made on the SCREAM side that were never made upstream.

Ah, I understand.

**Comment by jgfouca** [comment]
Can all the homme changes just be tossed, then? @bartgol ?

**Comment by bartgol** [comment]
> Can all the homme changes just be tossed, then? @bartgol ? Is there any connection between CIME machine names and homme machine names?

I think you can toss them, yes. The macros/files you touched should only be used in Homme standalone testing, which scream doesn't do.

**Comment by jgfouca** [comment]
OK, squashed out the homme changes so they are gone and no longer in the history.

**Pull request merged**
