### PR TITLE
Fix pioc/piof interface libraries in CIME builds

### PR DESCRIPTION
**Pull request by bartgol**
The interface libraries were linking against the netcdf imported libraries, but were not adding the corresponding include directories. This was ok so long as we were not including pioc headers in scream. As soon as pio.h started to be included in scream, it caused issues with finding netcdf headers (included indirectly via pio.h).

I verified that this fix does indeed allow e3sm.exe to compile on Chrysalis.

### CODE REVIEW

**Review by jgfouca — APPROVED** [review]

**Comment by AaronDonahue** [comment]
I'm testing this branch on `quartz` now to see if it will solve the issues there.

**Comment by bartgol** [comment]
I have no clue why this PR has diffs in two tests. The only possibility is if somehow this changed what netcdf gets linked/included. But I ran on mappy, and looked at the generated cmake files, and they looked the same. Even a pre-processed cpp.i file in the scream_io lib looked the same.

**Comment by ambrad** [comment]
@bartgol aren't these the same diffs @tcclevenger mentioned in the context of another PR?

**Comment by tcclevenger** [comment]
Yes, these are the same ones.

**Comment by AaronDonahue** [comment]
could be pointing to the DIFFs in the horiz remap not being simply baseline diffs.

**Comment by AaronDonahue** [comment]
I've confirmed this fixes the issue on quartz with building

**Comment by bartgol** [comment]
For the curious: mystery solved. If you're curious, the last non-bfb PR was merged yesterday, but its last AT run was days old (before _other_ non-bfb prs got merged). So when I blessed its AT run results, I blessed something that did not include stuff that was already in master, causing diffs. In fact, the same two diffs appear in the nightlies. I'm reblessing/retesting, and we should be good to go.

**Pull request merged**
