### PR TITLE
Add endrun command when SHOC diagnoses a negative temperature

### PR DESCRIPTION
**Pull request by crterai**
Inserted an endscreamrun command when a negative temperature is diagnosed in one of the temperature Gaussians in SHOC. This prevents NaNs from being produced when negative temperatures are fed into esatw.

### CODE REVIEW

**Comment by crterai** [comment]
@bogensch - Sorry, I should have pinged you beforehand. Peter asked me to put it in since he knew you were busy with other tasks. Good to know that you were thinking of the same changes though.

**Comment by crterai** [comment]
@ndk @bogensch I needed to change the location of the error message based on the newly refactored shoc code, so requesting a quick review again.

**Comment by PeterCaldwell** [comment]
I agree that the C.ne.C line should be removed too. Also I'm seeing some obvious bugs in the AT compiler log. And I think Chris is on vacation today so this PR won't move until Monday...

**Comment by crterai** [comment]
Thanks for catching the C .ne. C line @bogensch. I'll remove that line and also look into why the build is failing in AT.

**Comment by crterai** [comment]
The C .ne. C line has been removed and the line that caused the compile errors was removed.

**Comment by PeterCaldwell** [comment]
I'm getting this error when compiling on quartz (intel CPU):
```
/g/g11/caldwep/gitwork/scream_2/components/cam/src/physics/cam/shoc.F90(16): error #7002: Error in opening the compiled module file.  Check INCLUDE paths.   [SCREAM_ABORTUTILS]
  use scream_abortutils, only: endscreamrun
------^
/g/g11/caldwep/gitwork/scream_2/components/cam/src/physics/cam/shoc.F90(16): error #6580: Name in only-list does not exist or is not accessible.   [ENDSCREAMRUN]
  use scream_abortutils, only: endscreamrun
-------------------------------^
```

**Comment by singhbalwinder** [comment]
I have added scream_abortutils to physics/common/CMakeList.txt so that it works with both P3 and SHOC. Earlier it was in p3/CMakeList.txt, so SHOC testing infrastructure was missing this module. I hope it should pass the tests now (removing WIP so that AT can run to verify the fix).

**Pull request merged**
