### PR TITLE
p3 c++ and fortran variables rename

### PR DESCRIPTION
**Pull request by xyuan**
p3 c++ and fortran variables rename

BFB

### CODE REVIEW

**Comment by jeff-cohere** [comment]
Hi @xyuan . Would you mind adding a link to the p3 variable renaming Confluence page in your description? That lets us know the content of the PR.

**Comment by xyuan** [comment]
> Hi @xyuan . Would you mind adding a link to the p3 variable renaming Confluence page in your description? That lets us know the content of the PR.

Yes, the confluence page is here,
 https://acme-climate.atlassian.net/wiki/spaces/NGDNA/pages/1610647026/P3-C+Variable+Function+Renaming

**Comment by jeff-cohere** [comment]
This is quite a large set of changes. They're pretty simple search/replace kinds of changes, but I wonder if maybe we shouldn't try to divide and conquer in our code reviews. Maybe we could each assume responsibility for slightly-overlapping subsets of renamed variables, making sure they've been properly renamed?

Or do we feel that eyeballing these changes and leaning on the testing system is more appropriate?

**Comment by xyuan** [comment]
I use ‘sed’ for the text replacement, it should be able to do alignment, but I have never try it. Let me figure it out how to do it automatically.

**Comment by xyuan** [comment]
> This is quite a large set of changes. They're pretty simple search/replace kinds of changes, but I wonder if maybe we shouldn't try to divide and conquer in our code reviews. Maybe we could each assume responsibility for slightly-overlapping subsets of renamed variables, making sure they've been properly renamed?
> 
> Or do we feel that eyeballing these changes and leaning on the testing system is more appropriate?

correct! please just fast scan the code style to make sure you do like the changes. there is little chance to make mistake.

**Comment by xyuan** [comment]
Please approve this PR so it can be merged

**Pull request merged**
