### PR TITLE
SCREAM: first stab at using new AT feature

### PR DESCRIPTION
**Pull request by bartgol**
As a test, we decide that 'AT: SKIP TESTING' can be used to bypass tests.

### CODE REVIEW

**Comment by bartgol** [comment]
It seems that the new AT feature of pulling in the github labels is working.

This PR modifies the `jenkins-common.sh` script, and checks the PR labels. If `AT: SKIP TESTING` is found, then the jenkins job is not run. This causes the AT check to "pass", since the script immediately returns 0.

@jgfouca @PeterCaldwell I used this PR as a stunt to test that the new AT feature indeed worked. However, do you think something like this could be useful? Namely, a tag to skip all testing? I can see this to be used for instance for PRs only touching the documentation, or maybe only touching CIME stuff, for which we currently have no CI test.

Note: the label name `AT: SKIP TESTING` can be changed (I'd only have to change the jenkins-common script), or even split into separate labels (e.g., `AT: DOCS ONLY`, `AT: CIME ONLY`, ...), all doing the same thing (skip tests).

**Comment by PeterCaldwell** [comment]
Yeah, I think it would be totally useful to have a label that allows tests to be automatically integrated without running the tests. I don't think people will abuse it because skipping testing and screwing up nightlies will obviously cause lots of frowny faces from friends. We should make sure this label doesn't integrate until reviewers approve the PR though.

How about "AT:INTEGRATE_WITHOUT_TESTING" as the label name. I think it's important that the label is totally clear about what it's doing since it could be dangerous. "SKIP_TESTING" may make people think that you're just not ready to test yet - like a WIP.

**Comment by bartgol** [comment]
Good point on the similarity with WIP.

**Comment by bartgol** [comment]
I changed the label to `CI: Integrate Without Testing`. I changed the prefix (CI) and the casing (not all uppercase) to help understand that these labels are not features 'built-in' in the Autotester, but instead they are labels tha trigger specific behaviors in our CI scripts.

**Pull request merged**
