### PR TITLE
Jgfouca/upstream merge 2023 06 14

### PR DESCRIPTION
**Pull request by jgfouca**
Conflicts were much milder than I thought.

Conflicts:

### File: cime_config/allactive/config_pesall.xml

Conflicts were trivial and easy to resolve

### File: cime_config/machines/cmake_macros/crayclang_frontier.cmake

```
<<<<<<< HEAD
if (compile_threaded)
  #string(APPEND CFLAGS " -fopenmp")
  string(APPEND FFLAGS " -fopenmp")
  string(APPEND CXXFLAGS " -fopenmp")
  string(APPEND LDFLAGS " -fopenmp")
endif()
if (COMP_NAME STREQUAL elm)
  string(APPEND FFLAGS " -hfp0")
endif()
string(APPEND FFLAGS " -hipa0 -hzero")
string(APPEND FFLAGS " -em -ef")

string(APPEND SLIBS " -L$ENV{PNETCDF_PATH}/lib -lpnetcdf")
set(NETCDF_PATH "$ENV{NETCDF_DIR}")
set(PNETCDF_PATH "$ENV{PNETCDF_DIR}")
set(PIO_FILESYSTEM_HINTS "gpfs")
=======
if (COMP_NAME STREQUAL elm)
  # See Land NaNs in conditionals: https://github.com/E3SM-Project/E3SM/issues/4996
  string(APPEND FFLAGS " -hfp0")
endif()
# Disable ipa and zero initialization are for other NaN isues:
# https://github.com/E3SM-Project/E3SM/pull/5208
string(APPEND FFLAGS " -hipa0 -hzero")
# -em -ef generates modulename.mod (lowercase files) to support
# Scorpio installs
string(APPEND FFLAGS " -em -ef")

string(APPEND SLIBS " -L$ENV{PNETCDF_PATH}/lib -lpnetcdf")
if (NOT MPILIB STREQUAL mpi-serial)
  string(APPEND SLIBS " -L$ENV{ADIOS2_DIR}/lib64 -ladios2_c_mpi -ladios2_c -ladios2_core_mpi -ladios2_core -ladios2_evpath -ladios2_ffs -ladios2_dill -ladios2_atl -ladios2_enet")
endif()
set(NETCDF_PATH "$ENV{NETCDF_DIR}")
set(PNETCDF_PATH "$ENV{PNETCDF_DIR}")
>>>>>>> upstream/master
```

Resolution: Nearly entire file was a conflict. For the most part, I took the upstream changes but kept our (HEAD) fopenmp settings and PIO_FILESYSTEM_HINTS.

### File: cime_config/machines/config_machines.xml

In both crusher machine definitions:

```
<<<<<<< HEAD
    <BASELINE_ROOT>/lustre/orion/cli133/world-shared/e3sm/baselines/$COMPILER</BASELINE_ROOT>
    <CCSM_CPRNC>/lustre/orion/cli133/world-shared/e3sm/tools/cprnc/cprnc</CCSM_CPRNC>
=======
    <CCSM_CPRNC>/lustre/orion/cli115/world-shared/e3sm/tools/cprnc/cprnc</CCSM_CPRNC>
>>>>>>> upstream/master
```

Resolution: I kept our (HEAD) changes.

### File: components/eam/src/physics/cam/shoc_intr.F90

```
<<<<<<< HEAD
    use scamMod,        only: single_column, dp_crm
=======
    use iop_data_mod,   only: single_column, dp_crm
    use physics_utils,  only: calculate_drymmr_from_wetmmr, calculate_wetmmr_from_drymmr
>>>>>>> upstream/master
```

Resolution: The physics_utils imports were not being used so I went with HEAD except changing scamMod to iop_data_mod.

### CODE REVIEW

**Review by bogensch — DISMISSED** [review]
Thanks @jgfouca .  Yes, the conflicts did not live up to the hype I claimed they would be because I neglected to remember the downstream merge of SCREAM into E3SM a few months ago where the codes were well integrated.

**Comment by ambrad** [comment]
@jgfouca would you mind remerging upstream? I just got the Hommexx hasher (to complement the EAMxx AD one) into E3SM master. Thanks.

**Comment by jgfouca** [comment]
@ambrad , done

**Comment by jgfouca** [comment]
Mappy fails were due to failure to get the kokkos submodule. This should be fixed now in Jenkins. Will wait for retest.

**Review by bogensch — APPROVED** [review]

**Comment by AaronDonahue** [comment]
The `mappy` fail looks like NL fails and one FAIL in the DP test for the CIME based runs.  Are these expected?  @jgfouca?

**Comment by jgfouca** [comment]
NLFAILs in the CIME tests are not a problem, merging.

**Comment by jgfouca** [comment]
@AaronDonahue , I just noticed your comment and the one test that actually is a real FAIL. I'm looking into it now.

**Pull request merged**
