### PR TITLE
Fix crusher cpu build

### PR DESCRIPTION
**Pull request by oksanaguba**
One of commits cleaning cmake introduced an issue for cpu builds on crusher:

https://github.com/E3SM-Project/scream/pull/1797/commits/89114f48fbcfc96673fba7435e998e49667f1655

This is the fix.

### CODE REVIEW

**Review by ambrad — APPROVED** [review]
This is fine and appropriately specific to NOT clang.

**Comment by AaronDonahue** [comment]
@ambrad and @oksanaguba , just doing some git cleanup.  This is 3 weeks old and I think we have the crusher build working.  Is this PR still relevant?

**Comment by ambrad** [comment]
The CPU build on Crusher is Oksana's task, so we'll wait for her response. My understanding is it doesn't work, but I haven't tried it, as it's irrelevant to the science configuration.

**Comment by oksanaguba** [comment]
Sorry, completely forgot that it is not merged! Not sure why Andrew is saying it does not work. When i was doing this work, i made sure cpu and gpu configs worked (except obv i did not merge this). I will have to find the latest cpu build to see which commit it had.

**Comment by ambrad** [comment]
@oksanaguba I just meant that master I think doesn't have a working CPU config. But perhaps I'm wrong.

**Comment by oksanaguba** [comment]
I merged this to the today's master and ran successfully. I am not sure why it says here that there is a conflict.

**Comment by oksanaguba** [comment]
I can merge it thru the command line if needed -- i am not familiar with AT and what to do here.

**Comment by ambrad** [comment]
@oksanaguba one way to handle this and still go through the AT is to merge master into your branch, resolve any conflicts (if any actually exist), then push to this PR. Then let the AT run as usual.

**Comment by bartgol** [comment]
> I merged this to the today's master and ran successfully. I am not sure why it says here that there is a conflict.

This issue happens sometimes on github. I think it happens when there were different modification paths (in source and target branches), even though they both led to the same final version of the file. I suspect it has to do with the merge style/options. If you ever figure out why, let me know, cause I too am puzzled by this.

**Comment by oksanaguba** [comment]
@ambrad  please, approve this again; after master merge the approval is erased, thanks!

**Review by ambrad — APPROVED** [review]

**Comment by ambrad** [comment]
@oksanaguba I approved. You should put the label AT:AUTOMERGE on this PR when you're ready for it to be merged to master.

**Pull request merged**
