### PR TITLE
Jgfouca/upstream merge 2021 06 03

### PR DESCRIPTION
**Pull request by jgfouca**
###         both modified:   .gitmodules

```
[submodule "sbetr"]
<<<<<<< HEAD
        path = components/elm/src/external_models/sbetr
        url = git@github.com:BeTR-biogeochemistry-modeling/sbetr.git
[submodule "components/mpas-source"]
        path = components/mpas-source
        url = git@github.com:MPAS-Dev/MPAS-Model.git
=======
        path = components/elm/src/external_models/sbetr
        url = git@github.com:BeTR-biogeochemistry-modeling/sbetr.git
>>>>>>> upstream/master
```

Resolution: keep upstream. Not sure why this is a conflict since no one on scream has touched these subs

###             both modified:   components/eam/bld/build-namelist

```
<<<<<<< HEAD
add_default($nl,'linoz_psc_t');
=======
add_default($nl,'linoz_psc_T');
>>>>>>> upstream/master
```

Resolution: It looks like aaron changed this to T, so keeping upstream

###             both modified:   components/eam/bld/config_files/definition.xml

```
<<<<<<< HEAD
<entry id="microphys" valid_values="rk,mg1,mg1.5,mg2,p3" value="">
Microphysics package: rk (Rasch and Kristjansson), mg1 (Morrison and Gettelman two moment scheme CAM5.1), mg1.5 (Morrison and Gettelman second version development), mg2 (Morrison and Gettelman second version), p3 (Morrison and Milbrandt (2015\
) two moment scheme).
</entry>
<entry id="macrophys" valid_values="rk,park,clubb_sgs,shoc_sgs,none" value="">
Macrophysics package: RK, Park, CLUBB_SGS, SHOC_SGS.
=======
<entry id="microphys" valid_values="rk,mg1,mg1.5,mg2,none" value="">
Microphysics package: rk (Rasch and Kristjansson), mg1 (Morrison and Gettelman two moment scheme CAM5.1), mg1.5 (Morrison and Gettelman second version development), mg2 ((Morrison and Gettelman second version).
A value of "none" indicates no microphysics parameterization is used.
</entry>
<entry id="macrophys" valid_values="rk,park,clubb_sgs,none" value="">
Macrophysics package: RK, Park, CLUBB_SGS.
A value of "none" indicates no microphysics parameterization is used.
>>>>>>> upstream/master
```

Resolution: keep upstream but add p3 to microphys and shoc_sgs to macrophys

```
<<<<<<< HEAD
<entry id="pbl" valid_values="uw,hb,hbr,clubb_sgs,shoc_sgs" value="">
PBL package: uw (University of Washington), hb (Holtslag and Boville), hbr
 (Holtslag, Boville, and Rasch), clubb_sgs, shoc_sgs.
=======
<entry id="pbl" valid_values="uw,hb,hbr,clubb_sgs,none" value="">
PBL package: uw (University of Washington), hb (Holtslag and Boville), hbr
 (Holtslag, Boville, and Rasch), clubb_sgs.
 A value of "none" indicates no PBL parameterization is used.
 For the MMF a "none" is set by default, but a separate version of
 the HB scheme is used for stability.
>>>>>>> upstream/master
```

Resolution: keep upstream but add shoc_sgs to pbl

###             both modified:   components/eam/bld/namelist_files/namelist_defaults_eam.xml

```
<<<<<<< HEAD
<microp_scheme microphys="p3">   P3</microp_scheme>
=======
<microp_scheme use_MMF="1">     off</microp_scheme>
>>>>>>> upstream/master
```

Resolution: keep both

```
<<<<<<< HEAD
<!-- P3 specific namelist variables -->
<micro_p3_lookup_dir        > atm/cam/physprops </micro_p3_lookup_dir>
<micro_p3_tableversion                > 4       </micro_p3_tableversion>
<micro_aerosolactivation              > .true.  </micro_aerosolactivation>
<micro_subgrid_cloud                  > .true.  </micro_subgrid_cloud>
<micro_tend_output                    > .true.  </micro_tend_output>
<p3_qc_autoCon_Expon                          >  2.47   </p3_qc_autoCon_Expon>
<p3_qc_accret_Expon                   >  1.15   </p3_qc_accret_Expon>
<do_prescribed_CCN                    > .false. </do_prescribed_CCN>
=======
<!-- special defaults for MMF, which now sets all other physics scheme options to "off" -->
<micro_mincdnc        use_MMF="1">  -999.       </micro_mincdnc>
>>>>>>> upstream/master
```

Resolution: keep both

```
<<<<<<< HEAD
<macrop_scheme macrophys="shoc_sgs"  >SHOC_SGS</macrop_scheme>
=======
<macrop_scheme use_MMF="1"           >off</macrop_scheme>
>>>>>>> upstream/master
```

Resoltion: keep both

```
<<<<<<< HEAD
<eddy_scheme pbl="shoc_sgs"       >SHOC_SGS</eddy_scheme>
=======
<eddy_scheme use_MMF="1"          >off      </eddy_scheme>
>>>>>>> upstream/master
```

Resolution: keep both

```
<<<<<<< HEAD
<shallow_scheme pbl="shoc_sgs"    >SHOC_SGS</shallow_scheme>

<!-- Surface flux averaging -->
<srf_flux_avg eddy_scheme="HB"       >0</srf_flux_avg>
<srf_flux_avg eddy_scheme="HBR"      >0</srf_flux_avg>
<srf_flux_avg eddy_scheme="diag_TKE" >0</srf_flux_avg>
<srf_flux_avg eddy_scheme="CLUBB_SGS">0</srf_flux_avg>
<srf_flux_avg eddy_scheme="SHOC_SGS" >0</srf_flux_avg>
<srf_flux_avg use_MMF="1"            >0</srf_flux_avg>
=======
<shallow_scheme use_MMF="1"       >off      </shallow_scheme>

<!-- Surface flux averaging -->
<srf_flux_avg             >0</srf_flux_avg>
<srf_flux_avg use_MMF="1" >1</srf_flux_avg>
>>>>>>> upstream/master
```

Resolution: keep upstream except add SHOC_SGS

###             both modified:   components/eam/bld/namelist_files/namelist_definition.xml

```
<<<<<<< HEAD
       group="phys_ctl_nl" valid_values="RK,MG,P3" >
=======
       group="phys_ctl_nl" valid_values="RK,MG,off" >
>>>>>>> upstream/master
```

Resolution: keep both (P3 and offf)

```
<<<<<<< HEAD
<entry id="use_MAML" type="logical"  category="conv"
       group="phys_ctl_nl" valid_values="" >
Turn on Multiple Atmosphere and Multiple Land option
Default: false
</entry>

=======
>>>>>>> upstream/master
```

Resolution: keep upstream (remove use_MAML)

###             both modified:   components/eam/src/chemistry/mozart/mo_chm_diags.F90

```
<<<<<<< HEAD
    real(r8) :: area(ncol), mass(ncol,pver)
    real(r8) :: mmr_log(ncol,pver), mmr_log2(ncol,pver)
=======
    real(r8) :: area(ncol), mass(ncol,pver), drymass(ncol,pver)
    real(r8) :: wrk1d(ncol)
>>>>>>> upstream/master
```

Resolution: keep upstream but add mmr_log variables

###             both modified:   components/eam/src/physics/cam/microp_driver.F90

```
<<<<<<< HEAD
   case ('P3')
      call micro_p3_readnl(nlfile)
=======
   ! microp_driver doesn't handle these other options
>>>>>>> upstream/master
```

Resolution: keep both

```
<<<<<<< HEAD
   case ('P3')
      call micro_p3_register()
=======
   ! microp_driver doesn't handle these other options
>>>>>>> upstream/master
```

Resolution: keep both

```
<<<<<<< HEAD
   case ('P3')
      microp_driver_implements_cnst = micro_p3_implements_cnst(name)
=======
   ! microp_driver doesn't handle these other options
>>>>>>> upstream/master
```

Resolution: keep both

```
<<<<<<< HEAD
   case ('P3')
      call micro_p3_init_cnst(name, q)
=======
   ! microp_driver doesn't handle these other options
>>>>>>> upstream/master
```

Resolution: keep both

```
<<<<<<< HEAD
   case ('P3')
      call micro_p3_init(pbuf2d)
=======
   ! microp_driver doesn't handle these other options
>>>>>>> upstream/master
```

Resolution: keep both

```
<<<<<<< HEAD
   case ('P3')
      call t_startf('microp_p3_tend')
      call micro_p3_tend(state, ptend, dtime, pbuf)
      call t_stopf('microp_p3_tend')
=======
   ! microp_driver doesn't handle these other options
>>>>>>> upstream/master
```

Resolution: keep both

###             both modified:   components/eam/src/physics/cam/phys_control.F90

```
<<<<<<< HEAD
              eddy_scheme .eq. 'SHOC_SGS' .or. eddy_scheme .eq. 'CLUBB_SGS') ) then
      write(iulog,*)'phys_setopts: illegal value of eddy_scheme:', eddy_scheme
      call endrun('phys_setopts: illegal value of eddy_scheme')
   endif
   if ((microp_scheme /= 'MG' .and. microp_scheme /= 'RK' .and. microp_scheme /= 'P3')) then
=======
              eddy_scheme .eq. 'CLUBB_SGS' .or. eddy_scheme .eq. 'off') ) then
      write(iulog,*)'phys_setopts: illegal value of eddy_scheme:', eddy_scheme
      call endrun('phys_setopts: illegal value of eddy_scheme')
   endif
   if (.not. (microp_scheme .eq. 'MG' .or. microp_scheme .eq. 'RK' .or. microp_scheme .eq. 'off') ) then
>>>>>>> upstream/master
```

Resolution: keep upstream but add SHOC_SGS check to first if and P3 check to second if

### CODE REVIEW

**Review by bogensch — APPROVED** [review]
Thanks for doing this, @jgfouca .  All looks good to me.

**Review by AaronDonahue — APPROVED** [review]
@jgfouca , I took a look just because there were conflicts based on stuff I had done.  Looks good.  Only one comment, mostly for @bogensch , IOP made has changed name.  I'm assuming this won't impact anything in SCREAM since we don't use iop mode.  But worth pinging now just in case.

**Comment by bogensch** [comment]
Yes, I was the one that changed the name of IOP mode.  This will become consistent when DP-SCREAM PR is merged in.

**Comment by jgfouca** [comment]
The NLFAILS are expected. Merging.

**Pull request merged**
