### PR TITLE
More cess-production additions.

### PR DESCRIPTION
**Pull request by tcclevenger**
No conflicts, feel free to merge @crterai.

Also, I can start just cherry-picking individual commits into the branch (instead of PR) if that is preferred.

### CODE REVIEW

**Comment by ndkeen** [comment]
Thanks, this is really nice to have (and so quickly).

**Comment by crterai** [comment]
Thanks, @tcclevenger! This looks great. Merging now...
And yeah, maybe it'll be easier to just ask you to merge commits directly rather than through the PR process in the future. Since the PRs might confuse those thinking that these PRs are related to `master`.

**Comment by tcclevenger** [comment]
@crterai Sounds good, just keep commenting on that first PR with new merges, and I'll merge straight into the branch and let you know when it's complete.

**Comment by ndkeen** [comment]
FYI, using this branch, I was able to run ne30 with new scream-docs on frontier (1month+restart+1month). And for ne256, also worked (5days+restart+5days). Am trying ne1024 as well.

**Pull request merged**
