### PR TITLE
More lassen: trying to get CIME cases to work

### PR DESCRIPTION
**Pull request by jgfouca**
With these changes, we can make it into the RUN phase for a SCREAM CIME case. I'm getting weird seg faults in homme deep in MPI, so I'm not quite sure where to go from here.

The core file shows this:
```
#0  __memcpy_power7 () at ../sysdeps/powerpc/powerpc64/power7/memcpy.S:90
#1  0x000020001ad86f38 in PAMI::Device::Shmem::Packet<PAMI::Fifo::FifoPacket<64u, 4096u> >::writePayload(PAMI::Fifo::FifoPacket<64u, 4096u>&, void*, unsigned long) ()
   from /usr/tce/packages/spectrum-mpi/ibm/spectrum-mpi-rolling-release/container/../lib/pami_port/libpami.so.3
#2  0x000020001ada5ae4 in bool PAMI::Device::Interface::PacketModel<PAMI::Device::Shmem::PacketModel<PAMI::Device::ShmemDevice<PAMI::Fifo::WrapFifo<PAMI::Fifo::FifoPacket<64u, 4096u>, PAMI::Counter::IndirectBounded<PAMI::Atomic::NativeAtomic>, 256u>, PAMI::Counter::Indirect<PAMI::Counter::Native>, PAMI::Device::Shmem::CMAShaddr, 256u, 512u> > >::postMultiPacket<512u>(unsigned char (&) [512u], void (*)(void*, void*, pami_result_t), void*, unsigned long, unsigned long, void*, unsigned long, void*, unsigned long) () from /usr/tce/packages/spectrum-mpi/ibm/spectrum-mpi-rolling-release/container/../lib/pami_port/libpami.so.3
#3  0x000020001adb8e74 in PAMI::Protocol::Send::EagerSimple<PAMI::Device::Shmem::PacketModel<PAMI::Device::ShmemDevice<PAMI::Fifo::WrapFifo<PAMI::Fifo::FifoPacket<64u, 4096u>, PAMI::Counter::IndirectBounded<PAMI::Atomic::NativeAtomic>, 256u>, PAMI::Counter::Indirect<PAMI::Counter::Native>, PAMI::Device::Shmem::CMAShaddr, 256u, 512u> >, (PAMI::Protocol::Send::configuration_t)1>::simple_impl(pami_send_t*) ()
   from /usr/tce/packages/spectrum-mpi/ibm/spectrum-mpi-rolling-release/container/../lib/pami_port/libpami.so.3
#4  0x000020001adb916c in PAMI::Protocol::Send::Eager<PAMI::Device::Shmem::PacketModel<PAMI::Device::ShmemDevice<PAMI::Fifo::WrapFifo<PAMI::Fifo::FifoPacket<64u, 4096u>, PAMI::Counter::IndirectBounded<PAMI::Atomic::NativeAtomic>, 256u>, PAMI::Counter::Indirect<PAMI::Counter::Native>, PAMI::Device::Shmem::CMAShaddr, 256u, 512u> >, PAMI::Device::IBV::GpuPacketModel<PAMI::Device::IBV::Device, false> >::EagerImpl<(PAMI::Protocol::Send::configuration_t)1, true>::simple(pami_send_t*) () from /usr/tce/packages/spectrum-mpi/ibm/spectrum-mpi-rolling-release/container/../lib/pami_port/libpami.so.3
#5  0x000020001ace5758 in PAMI_Send () from /usr/tce/packages/spectrum-mpi/ibm/spectrum-mpi-rolling-release/container/../lib/pami_port/libpami.so.3
#6  0x000020001ab1f618 in pml_pami_send () from /usr/tce/packages/spectrum-mpi/ibm/spectrum-mpi-rolling-release/container/../lib/spectrum_mpi/mca_pml_pami.so
#7  0x000020001ab1e29c in pml_pami_persis_send_start () from /usr/tce/packages/spectrum-mpi/ibm/spectrum-mpi-rolling-release/container/../lib/spectrum_mpi/mca_pml_pami.so
#8  0x000020001ab1e6e0 in mca_pml_pami_start () from /usr/tce/packages/spectrum-mpi/ibm/spectrum-mpi-rolling-release/container/../lib/spectrum_mpi/mca_pml_pami.so
#9  0x0000200016bc3db8 in PMPI_Startall () from /usr/tce/packages/spectrum-mpi/ibm/spectrum-mpi-rolling-release/lib/libmpi_ibm.so.3
#10 0x00000000111625ac in Homme::BoundaryExchange::pack_and_send() ()
#11 0x0000000011162a7c in Homme::BoundaryExchange::exchange(Kokkos::View<double const* [4][4], Kokkos::LayoutRight, Kokkos::CudaSpace, Kokkos::MemoryTraits<9u> > const*) ()
#12 0x0000000010dfea84 in scream::PhysicsDynamicsRemapper::do_remap_fwd() ()
#13 0x00000000117896bc in scream::AbstractRemapper::remap(bool) ()
#14 0x0000000010d683e4 in scream::HommeDynamics::initialize_homme_state() ()
#15 0x0000000010d6bfa8 in scream::HommeDynamics::initialize_impl(scream::RunType) ()
#16 0x0000000011685764 in scream::AtmosphereProcess::initialize(scream::util::TimeStamp const&, scream::RunType) ()
#17 0x00000000116c7af4 in scream::AtmosphereProcessGroup::initialize_impl(scream::RunType) ()
#18 0x0000000011685764 in scream::AtmosphereProcess::initialize(scream::util::TimeStamp const&, scream::RunType) ()
#19 0x0000000010c2a6d8 in scream::control::AtmosphereDriver::initialize_atm_procs() ()
#20 0x0000000010135e8c in scream_init_atm ()
#21 0x00000000101321b0 in __atm_comp_mct_MOD_atm_init_mct ()
#22 0x00000000100a133c in __component_mod_MOD_component_init_cc ()
#23 0x000000001008fcb0 in __cime_comp_mod_MOD_cime_init ()
#24 0x000000001009e108 in main ()
```

My strategy was to copy a lot of the configs from summit/ascent since they are also IBM/jsrun machines and just tweak some of the numbers to match the Lassen hardware description.

### CODE REVIEW

**Comment by PeterCaldwell** [comment]
Is this happening on the first timestep or far into the simulation? I guess its in init from the stack trace... Do the log files say anything interesting? What's the location of this run?

**Comment by ambrad** [comment]
You might try doing MPI with host pointers: SCREAM_MPI_ON_DEVICE=OFF.

**Comment by jgfouca** [comment]
@PeterCaldwell , yes, very early in the run. Case is here: /usr/workspace/foucar1/e3sm_scratch/SMS_Ln22.ne4pg2_ne4pg2.F2010-SCREAMv1.lassen_gnugpu.20230818_142458_9e8l03

Nothing much useful in the e3sm, homme, or cpl logs.

@ambrad , I will try that.

**Comment by jgfouca** [comment]
@ambrad,

`SCREAM_MPI_ON_DEVICE=OFF`

... appears to have made a big difference. It's been running for 30m and I can see in the logs that it's making it much further.

**Comment by ambrad** [comment]
That implies that there's a problem in the MPI with GPU MPI buffers. The likeliest cause is you're missing some (possibly Lassen-specific) environment variable settings to enable GPU buffers in MPI. The second likeliest is that you're missing a jsrun flag. The least likely is that the s/w stack doesn't support GPU MPI buffers. To fix this, one of the LLNL folks might want to reach out to a Lassen admin for help with enabling GPU buffers in MPI.

**Comment by AaronDonahue** [comment]
>To fix this, one of the LLNL folks might want to reach out to a Lassen admin for help with enabling GPU buffers in MPI.
@jgfouca . I'm happy to do this, but I think that as a lassen user you should also be able to write to LC support and get assistance.  It might work best if you are at least in the conversation so you can add context for support.  Let me know if you would like me to open the ticket, or you want to take the lead.

**Review by bartgol — DISMISSED** [review]

**Comment by ambrad** [comment]
@AaronDonahue you might consider running with
```cmake
set(SCREAM_MPI_ON_DEVICE OFF CACHE STRING "")
```
in the gnugpu_lassen.cmake file for now and then working with the LC folks as you or others have time, depending on task priorities.

**Comment by jgfouca** [comment]
`export PGI_ACC_POOL_ALLOC=0` had no effect. I guess that's not surprising since we're using gcc. I've had enough of fighting with Lassen for now, so let's just move forward with MPI on device OFF.

**Comment by jgfouca** [comment]
I found this googling for spectrum MPI GPU support:

```
For Power Systems servers, IBM Spectrum MPI supports running GPU-accelerated
applications over CUDA-aware MPI. For x86 servers, IBM Spectrum MPI also
supports running GPU-accelerated applications with NVIDIA GPUDirect RDMA.
For both Power Systems servers and x86 servers, the NVIDIA CUDA Toolkit 7.5 is
required.

By default, GPU support is turned off. To turn it on, use the mpirun -gpu flag:
mpirun -gpu

The restrictions that apply to GPU support under IBM Spectrum MPI are: v The following collectives cannot be used in GPU-accelerated applications: 
– MPI_Alltoallw
– MPI_Ialltoallw
– MPI_Reduce_local 

One-sided communication is restricted. When -gpu is specified on the mpirun command line, libcollectives must be the
preferred collective component. This is because libcollectives is the only
collective component that is able to support CUDA buffers. Therefore, you
cannot specify mpirun -gpu with any of the following options: 
– -mxm/-MXM
– -mxmc/-MXMC
– -tcp/-TCP
– -ibv/-IBV
– -ib/-IB
– -openib/-OPENIB
– -fca/-FCA
– -hcoll\-HCOLL
```

It's hard to see what the mpirun command is since it's wrapped by jsrun. We do have `--smpiargs="-gpu"` so it's not obvious what is wrong.

**Pull request merged**
