### PR TITLE
SCREAM: download all p3 tables

### LINKED ISSUE #1540: Problem at build with p3_tables_setup exe on Cori with optimized build
Using a scream master of Apr12th, can reproduce with `SMS_Ld1_P16x1.ne4_ne4.F2000SCREAMv1.cori-knl_gnu` (ie OPT build) after commenting out abort as noted here https://github.com/E3SM-Project/scream/issues/1539.

Note that after upstream merge that pushed gnu version to 10.3 on cori, we need the same flag that treats certain errors as warnings for now, which I will get into repo soon via this branch `ndk/scream/cori-allow-gnuv10-builds` 

```
[ 98%] Generating /global/cscratch1/sd/ndk/e3sm_scratch/cori-knl/bio-apr11/f30cpu.F2000SCREAMv1.ne30_ne30.bio-apr11.gnu.12s.n011b16x1.RECe.N576.ts150.s8.barr/run/data/mu_r_table_vals.dat8, /global/cscratch1/sd/ndk/e3sm_scratch/cori-knl/bio-apr11/f30cpu.F2000SCREAMv1.ne30_ne30.bio-apr11.gnu.12s.n011b16x1.RECe.N576.ts150.s8.barr/run/data/revap_table_vals.dat8, /global/cscratch1/sd/ndk/e3sm_scratch/cori-knl/bio-apr11/f30cpu.F2000SCREAMv1.ne30_ne30.bio-apr11.gnu.12s.n011b16x1.RECe.N576.ts150.s8.barr/run/data/vm_table_vals.dat8, /global/cscratch1/sd/ndk/e3sm_scratch/cori-knl/bio-apr11/f30cpu.F2000SCREAMv1.ne30_ne30.bio-apr11.gnu.12s.n011b16x1.RECe.N576.ts150.s8.barr/run/data/vn_table_vals.dat8
cd /global/cscratch1/sd/ndk/e3sm_scratch/cori-knl/bio-apr11/f30cpu.F2000SCREAMv1.ne30_ne30.bio-apr11.gnu.12s.n011b16x1.RECe.N576.ts150.s8.barr/bld/cmake-bld/scream/src/physics/p3 && /global/common/software/nersc/cori-2022q1/spack/cray-cnl7-haswell/cmake-3.22.1-zdiyyvt/bin/cmake -E env /global/cscratch1/sd/ndk/e3sm_scratch/cori-knl/bio-apr11/f30cpu.F2000SCREAMv1.ne30_ne30.bio-apr11.gnu.12s.n011b16x1.RECe.N576.ts150.s8.barr/bld/cmake-bld/scream/src/physics/p3/p3_tables_setup
Illegal instruction
make[2]: *** [scream/src/physics/p3/CMakeFiles/p3_create_tables.dir/build.make:79: /global/cscratch1/sd/ndk/e3sm_scratch/cori-knl/bio-apr11/f30cpu.F2000SCREAMv1.ne30_ne30.bio-apr11.gnu.12s.n011b16x1.RECe.N576.ts150.s8.barr/run/data/mu_r_table_vals.dat8] Error 1
make[2]: Leaving directory '/global/cscratch1/sd/ndk/e3sm_scratch/cori-knl/bio-apr11/f30cpu.F2000SCREAMv1.ne30_ne30.bio-apr11.gnu.12s.n011b16x1.RECe.N576.ts150.s8.barr/bld/cmake-bld'
make[1]: *** [CMakeFiles/Makefile2:2183: scream/src/physics/p3/CMakeFiles/p3_create_tables.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
```

It may be that exe is built, but it's trying to run that exe on the login node, which we can't really do on machines where the login node is different than compute node.  Yea I think that's it.  Executable is there, but cant run it on login node:

```
cori08% pwd
/global/cscratch1/sd/ndk/e3sm_scratch/cori-knl/bio-apr11/f30cpu.F2000SCREAMv1.ne30_ne30.bio-apr11.gnu.12s.n011b16x1.RECe.N576.ts150.s8.barr/bld/cmake-bld/scream/src/physics/p3
cori08% ls
./  ../  CMakeFiles/  CTestTestfile.cmake  Makefile  cmake_install.cmake  libp3.a  p3_tables_setup*
cori08% ./p3_tables_setup
Illegal instruction
```

With Intel compiler, I get an "internal error" which I originally thought was related to this issue, but does not seem to be -- 
moved to https://github.com/E3SM-Project/scream/issues/1543.

### PR DESCRIPTION
**Pull request by bartgol**
Even those that could be downloaded. We still provide the executable to generate tables, in case there's a change in P3, to allow regenerating them. But they would have to be uploaded on the e3sm input data server.

#1540  explains the reason for this change. Bottom line: our executables may not work on the login node, which is where the build phase is likely happening.

@jgfouca remove WIP as soon as the tables are uploaded on the input data server.

Fixes #1540

### CODE REVIEW

**Comment by bartgol** [comment]
This PR has evolved into much more. A recap:

- P3 tables are downloaded via GetInputFile, if not present, just like any other input file
- We still keep the target `p3_tables_setup`, but we don't build it as part of ALL. If in the future we need to re-generate tables, we can build/run this target.
- SCREAM_DATA_DIR is no longer in the build (for standalone) or run (for CIME cases) folder. Instead, it is set equal to ${SCREAM_INPUT_ROOT}/atm/scream
- As a consequence, GetInputFile no longer copies the downloaded files from SCREAM_INPUT_DIR/atm/scream into SCREAM_DATA_DIR, since the two are the same
- All tests use, when possible, input files from SCREAM_DATA_DIR. This reduces copies of nc/dat files around the bld tree (in fact, it eliminates all copies).
- Cleanup leftovers of homme tests using vcoord folder. Vertical coordinates are now read from an NC file (should match the IC file).
- Fixed an undesired behavior of --quick-rerun in test-all-scream: we don't need to skip cmake; we simply need to not remove CMake files (e.g., CMakeCache.txt), so that if nothing changes by running CMake, most of the build phase is skipped by make. But if the user is doing development, and a cmake file (or a file that triggers cmake) changes, we do want --quick-rerun to _NOT_ skip the config phase.
- Increased verbosity of p3 table read, so that we know which table failed the read phase.

NOTE: it is possible that some build will fail, due to a slightly different version of the p3 tables. In fact, all builds will now use the same version of the tables, which we download from input data, while before each build was generating the tables. In particular, the release and debug build were for sure generating non-bfb equivalent tables. So some build will throw a fit, with p3_run_and_cmp failing all comparisons. However, it's worth pointing out that the tables that were generated from release and debug builds were _basically_ the same, just not BFB. Hence, using a single version for all builds is justified. It is no different that using the same nc file for IC across all machs/builds.

**Comment by bartgol** [comment]
@jgfouca a lot of the changes are in CMakeLists.txt and yaml input files, and are minor (e.g., prepending `${SCREAM_DATA_DIR}/init/` to a bunch of initial conditions nc files). So the 40 files changed sounds worse than it actually is.

**Review by jgfouca — APPROVED** [review]

**Comment by bartgol** [comment]
I manually tested the branch on blake. Everything passes, except for p3_run_and_cmp (both cxx and f90) for debug SP/DP builds. The diffs are all "small", with rel errors usually below 1e-15, with some occurrences of 1e-12. This is expected since the tables were no longer generated "in house", but an externally provided one was used (with possibly slightly different values). A simple `diff` of the tables in the input root, with those generated by the code (running `p3_tables_setup`) shows that they differ.

@jgfouca do you remember if the p3 tables you copied on the server were generated on mappy? That would explain why blake/weaver fail, while mappy doesn't.

Meanwhile, weaver fails the same tests. I am going to check that the diffs are relatively small, and if so, I think we can merge this.

**Comment by jgfouca** [comment]
@bartgol , yes, they were generated on mappy.

**Comment by jgfouca** [comment]
I agree, this is ready to merge. My mouse is hovering over the red button...

**Comment by wlin7** [comment]
Just a note: I needed to manually downloaded the new tables to NERSC's inputdata path to run the test `SMS_D_Ln2_P24x1.ne4_ne4.F2000SCREAMv1.cori-knl_intel`. Is it the way how it works for now?

**Comment by bartgol** [comment]
You should not need to download them. But we did not update the `Input Files` section in our namelist defaults, to include these new files, so they are not getting downloaded. We should be able to fix this really easily.

**Comment by wlin7** [comment]
I see. Thanks.

**Comment by bartgol** [comment]
Btw, #1553 should fix that behavior.

**Pull request merged**
