### PR TITLE
Homme: Fix planar-mode pgN get_latlon routines.

### PR DESCRIPTION
**Pull request by ambrad**
Optional PR if we want to get the commits from https://github.com/E3SM-Project/E3SM/pull/6586 into SCREAM sooner than the next upstream merge.

### CODE REVIEW

**Comment by ambrad** [comment]
pg2 (black) and GLL (red) coordinates from an output file after the fix is applied: https://web.lcrc.anl.gov/public/e3sm/diagnostic_output/ac.ambradl/scream/dp/latlon.html

**Review by tcclevenger — APPROVED** [review]
I'm fine with merging.

**Review by bogensch — APPROVED** [review]
Thanks so much for fixing this @ambrad !  I ran a couple cases and all appears to be good on my end.

**Comment by ambrad** [comment]
Mappy diffs in DP tests are on the lat/lon output fields.

**Comment by tcclevenger** [comment]
Thanks, @ambrad! I'll merge.

**Comment by tcclevenger** [comment]
@ambrad Do you see any chance that things are changed in the upstream PR? I'll go ahead and merge if so.

**Pull request merged**
