### PR TITLE
Fixes a bug when copying grid data for a geo data of scalar type.

### PR DESCRIPTION
**Pull request by AaronDonahue**
When copying the grid geo data from one grid to the another there is a check if the geo data has COL or not.  This led to an error for the unique case of a geo data that is a scalar and thus the layout is essentially empty.

This happens for DPxx cases.

### CODE REVIEW

**Comment by AaronDonahue** [comment]
@bogensch , this should fix the issue you were hitting w/ horizontal remapping of DPxx runs.  I tested it w/ the DYCOMSrf01 case w/ the remap file you provided for me.

**Review by bartgol — DISMISSED** [review]

**Comment by bogensch** [comment]
@AaronDonahue thank you soooo much for working on this.  So, this worked perfectly fine for me on pm-cpu (yay), but when I ran the exact same case on pm-gpu it seg faulted on initialization....

**Comment by AaronDonahue** [comment]
Thanks for checking on pm-gpu.  Since our AT doesn't run a DPxx case w/ remapping I'll manually investigate and update the branch.

**Review by bartgol — APPROVED** [review]

**Comment by bogensch** [comment]
Can confirm this works for me now on pm-gpu.  Thanks!!!

**Comment by bartgol** [comment]
The AT timed out, but I verified that the mappy and weaver job actually passed. So I'll merge this, rather than get another round of testing. We've been testing a lot of PRs in the last 2 days, and we've been filling up scratch space faster than the clean up job can free it. So better save one run.

**Pull request merged**
