### PR TITLE
Aaron/p3 rad fix

### PR DESCRIPTION
**Pull request by AaronDonahue**
Bugfix for variables passed from P3 microphysics to radiation scheme.
    
    This commit fixes an issue where the values passed from the P3-microphysics
    scheme to the radiation scheme were inconsistent with P3.  This commit:
    
    1) Removes a number of subroutines taken from MG microphysics that are
    no longer needed/used.
    2) Uses the effective radius for liquid (rel) and ice (rei) as determined inside P3,
    instead of taking values that are calculated based on MG subroutines.
    3) Furthermore, the bulk density of ice used to calculate the effective diameter
    of ice (dei) is taken from P3 instead of being a fixed constant.

Below are two year annual climatologies for,

top)       this PR
center)  MG microphysics
bottom) w/ P3 after PR #82

image

image

image

### CODE REVIEW

**Comment by AaronDonahue** [comment]
@bogensch , once this PR goes through you should be able to test running SHOC+P3+RRTGMP together.

**Comment by pressel** [comment]
@AaronDonahue Are the variable descriptions involving MG on lines 483 and 484 still correct?

**Comment by AaronDonahue** [comment]
@pressel , good catch, yes, we should remove the reference to MG in the field description and leave it as just a general stratiform.

**Comment by AaronDonahue** [comment]
@jgfouca , I think something went wrong in the Tavis CI build.  How do we reset the check?

**Comment by ambrad** [comment]
Looks like this failure type (based on the apt-get error message: "There were unauthenticated packages") is a somewhat pervasive issue. You could sign in to Travis CI and then ask for a rebuild. Or make and push an empty commit: `git commit --allow-empty -m "Trigger"`, as suggested here: https://stackoverflow.com/questions/17606874/trigger-a-travis-ci-rebuild-without-pushing-a-commit

**Comment by AaronDonahue** [comment]
@ambrad , thanks for the help.  I tried the former but couldn't figure out how to get Travis to rebuild.  I remember in the past there was the option, but all I saw this time around was "resolve".  So I'm going to try the empty commit.

**Comment by ambrad** [comment]
I think the rebuild option appears only if you login to Travis, not just look at the page.

**Comment by AaronDonahue** [comment]
@brhillman pinged me about whether or not we will need to make changes to the radiation interface to accommodate P3 microphysics.  There may be some assumptions about MG microphysics baked into the current scheme.  In particular, what distribution mu_c and lambda_c are related too.  This may be work for a future PR, but I wanted to make a note about it here.

**Comment by AaronDonahue** [comment]
I did some investigating on how lambda_c and mu_c are calculated in P3 and MG microphysics.   They match with only one small difference.  In P3, mu_c is capped at a maximum of 15., while in MG that isn't the default behavior.  Without getting too much in the weeds, if the CLUBB_BFB compiler flag is turned on then it will cap mu_c at a max of 15., otherwise mu_c is allowed to be as big as we want.

side note, in both MG and P3 mu_c is lower bound by 2.

**Pull request merged**
