### PR TITLE
Jgfouca/upstream merge 2022 08 04

### PR DESCRIPTION
**Pull request by jgfouca**
No significant conflicts.

I am still wondering why we thought we needed entirely separate machines for summit (summit-cpu and summit-gpu). Upstream e3sm does not do that and seems to have the switches needed to support both.

### CODE REVIEW

**Comment by jgfouca** [comment]
I some a couple sanity checks on mappy and things look fine, so I will let the AT process this PR now.

**Comment by jgfouca** [comment]
In testing, all the V0 runs failed with:

```
Fortran runtime error: Cannot open file '/sems-data-store/ACME/inputdata/atm/cam/physprops/p3_lookup_table_1.dat-v4.1.1': No such file or directory
```

I had to add this change to get things to work:

```
components/eam/bld/namelist_files/namelist_defaults_eam.xml
@@ -918,7 +918,7 @@
 <micro_mincdnc        microphys="mg2">  -999.       </micro_mincdnc>
 
 <!-- P3 specific namelist variables -->
-<micro_p3_lookup_dir       > atm/cam/physprops </micro_p3_lookup_dir>
+<micro_p3_lookup_dir       > atm/scream/tables </micro_p3_lookup_dir>
```

When I test this locally, everything passes (except NLFAIL due to this change).

**Comment by AaronDonahue** [comment]
> In testing, all the V0 runs failed with:
> 
> ```
> Fortran runtime error: Cannot open file '/sems-data-store/ACME/inputdata/atm/cam/physprops/p3_lookup_table_1.dat-v4.1.1': No such file or directory
> ```
> 
> I had to add this change to get things to work:
> 
> ```
> components/eam/bld/namelist_files/namelist_defaults_eam.xml
> @@ -918,7 +918,7 @@
>  <micro_mincdnc        microphys="mg2">  -999.       </micro_mincdnc>
>  
>  
> -<micro_p3_lookup_dir       > atm/cam/physprops </micro_p3_lookup_dir>
> +<micro_p3_lookup_dir       > atm/scream/tables </micro_p3_lookup_dir>
> ```
> 
> When I test this locally, everything passes (except NLFAIL due to this change).

@jgfouca , this is also a fail that is occurring in master.  It looks like your change will fix that, right?  I wonder how the issue snuck into our current version of master.

**Comment by jgfouca** [comment]
@AaronDonahue , yes, it should fix it. I can't explain how it got onto master.

**Comment by jgfouca** [comment]
@AaronDonahue , if you approve, I will force merge this.

**Comment by AaronDonahue** [comment]
> @AaronDonahue , if you approve, I will force merge this.

@jgfouca , is this a non-BFB merge?  If so, we will want to coordinate with #1837 merging.

**Comment by AaronDonahue** [comment]
Although, if this is just non-BFB for SCREAMv0 and 1837 is non-BFB for SCREAMv1 then maybe we can merge both at around the same time.

**Comment by jgfouca** [comment]
@AaronDonahue , it is BFB. The only change is some namelist diffs in V0.

**Comment by jgfouca** [comment]
@AaronDonahue , ah, the output from the AT is a bit misleading. This PR is not BFB, at least with the current baselines. It's possible I just need to update.

**Comment by AaronDonahue** [comment]
Looking at the files that change I don't see any reason this would impact SCREAMv1 in the same way as #1837 .  So I would be comfortable merging this one and 1837 both today.  @bartgol , @ambrad - any push back on that plan?

**Comment by ambrad** [comment]
I agree: merge both.

**Pull request merged**
