### PR TITLE
Fix leap year logic in EAMxx

### PR DESCRIPTION
**Pull request by bartgol**
When running through CIME, we get the type of calendar from CIME. I manually verified that this works.

### CODE REVIEW

**Review by AaronDonahue — APPROVED** [review]
I'm a bit surprised we have DIFFs in the mappy tests.  None of those tests run through a leap year right?

**Comment by bartgol** [comment]
Yeah, diffs were not expected. I will investigate.

**Comment by bartgol** [comment]
Ah, wait, this could be due to #2487 that got merged ~3h before this PR got tested. We'll bless baselines, and see if it passes.

**Comment by bartgol** [comment]
@tcclevenger The failed test on weaver is `tms_tests_omp1`, due to a diff

```
/home/e3sm-jenkins/weaver/workspace/SCREAM_PullRequest_Autotester_Weaver/4863/scream/components/eamxx/src/physics/tms/tests/compute_tms_tests.cpp:79: FAILED:
  REQUIRE( d_f90.ksrf[i] == d_cxx.ksrf[i] )
with expansion:
  0.0001042416 == 0.0001042416
```
The PR does not change anything that should affect tms, so I wasn't expecting this. If one of the two sides was a NaN, I may say we hit an unlucky set of random input values. But here, the diff is at the roundoff level, which makes me wonder if there are some places in the tms code where we re-arranged inputs. Do you know if that's possible? It's not that obvious that's the case though, since I would have assumed we would have gotten a fail in our nightlies by now, if that was the case. But maybe this special value triggered some additional chunk of code? I don't know. If it helps, here's the rng seed to reproduce it.
```
For test compute_tms_bfb, random number generator seed: 1417415078
```
Could you please take a quick look?

**Comment by tcclevenger** [comment]
@bartgol Taking a look now

**Comment by tcclevenger** [comment]
Reproducible on master, so you are just getting unlucky here. Should be fine to merge if that's the only fail.

**Pull request merged**
