### PR TITLE
Fix usage of code deprecated Kokkos code, and updates ekat

### PR DESCRIPTION
**Pull request by bartgol**
We can now build with `Kokkos_ENABLE_DEPRECATED_CODE_4=OFF`. Also, brings in an update in ekat that suppresses the zillion warnings we were getting.

@jgfouca I did not set `Kokkos_ENABLE_DEPRECATED_CODE_4=OFF` in our test-all-scream builds. But maybe we should consider doing it at some point?

### CODE REVIEW

**Comment by jgfouca** [comment]
Am i going crazy? I don't see the ekat submodule being updated?

**Comment by bartgol** [comment]
> Am i going crazy? I don't see the ekat submodule being updated?

I forgot to push the commit, but you should see it now.

**Review by jgfouca — APPROVED** [review]

**Comment by jgfouca** [comment]
Looks like weaver failed

**Comment by bartgol** [comment]
We still have the issue that test-all-scream does not really updates baselines when running through the AT (something is amiss with the master merge and the ahead/behind calculation). I am manually forcing baseline regen now.

**Review by jgfouca — APPROVED** [review]

**Pull request merged**
