### PR TITLE
Get scream CIME cases building on summit

### PR DESCRIPTION
**Pull request by jgfouca**
There's a segfault during RUN phase, but this PR at least gets us that far.

### CODE REVIEW

**Review by ambrad — APPROVED** [review]

**Comment by ambrad** [comment]
This looks fine on the scream side. I'm wondering if the seg fault is related to the fact that in cime_config/machines/config_machines.xml, ascent and summit-gpu don't load the same modules, including gnu and cuda modules.

**Comment by PeterCaldwell** [comment]
Sanity check - this PR was about getting CIME cases working on *ascent*, not summit - right?

**Comment by jgfouca** [comment]
@PeterCaldwell , wow, big brain fart on my part! Yes, this was for ascent.

**Comment by jgfouca** [comment]
@ambrad , I changed config_machines.xml for ascent to more-closely match summit-gpu and unfortunately the segfault remains.

**Comment by jgfouca** [comment]
@ambrad , whoops, didn't notice that one. Trying again now.

**Comment by jgfouca** [comment]
@ambrad , OK made it farther. I hit a yakl error which I bypassed with GATOR_DISABLE. Next errors are:

```
source_func_lw%alloc: not initialized so can't allocate
```

and

```
optical_props::alloc: spectral discretization hasn't been provided
```

**Comment by ambrad** [comment]
Those look like radiation things. Perhaps @brhillman knows. Is it possible there are missing input files and CIME doesn't know to download them?

**Pull request merged**
