### PR TITLE
Use rayleigh friction

### PR DESCRIPTION
**Pull request by tcclevenger**
Set `rayleigh_friction_decay_time` to turn on Rayleigh friction in Homme AD interface. We set to `5.0` to match EAM.

### CODE REVIEW

**Review by bartgol — DISMISSED** [review]

**Review by ambrad — APPROVED** [review]

**Comment by tcclevenger** [comment]
Mappy CIME fails show diffs around 1e-1 to 1e-6. I believe this is expected. Blake passed. Weaver looks like it terminated early unrelated.

@ambrad @bartgol I don't see this change having any GPU specific impact. Should we manually merge or wait for Weaver to run?

**Comment by ambrad** [comment]
@bartgol I see PASSes for the pg2 v1 tests but expect these to DIFF against baselines like the ne4 ones. Or do the pg2 tests not have baselines?
```
DIFF ERP_D_Lh4.ne4_ne4.F2010-SCREAMv1.mappy_gnu9 (phase BASELINE)
Case dir: /ascldap/users/e3sm-jenkins/acme/scratch/ERP_D_Lh4.ne4_ne4.F2010-SCREAMv1.mappy_gnu9.C.20220829_100951_99z6iy
PASS ERP_Ln22.ne4pg2_ne4pg2.F2010-SCREAMv1.mappy_gnu9 RUN
Case dir: /ascldap/users/e3sm-jenkins/acme/scratch/ERP_Ln22.ne4pg2_ne4pg2.F2010-SCREAMv1.mappy_gnu9.C.20220829_100951_99z6iy
PASS ERS_D_Ln22.ne4pg2_ne4pg2.F2010-SCREAMv1.mappy_gnu9 RUN
Case dir: /ascldap/users/e3sm-jenkins/acme/scratch/ERS_D_Ln22.ne4pg2_ne4pg2.F2010-SCREAMv1.mappy_gnu9.C.20220829_100951_99z6iy
DIFF ERS_Ln9.ne4_ne4.F2000-SCREAMv1-AQP1.mappy_gnu9 (phase BASELINE)
Case dir: /ascldap/users/e3sm-jenkins/acme/scratch/ERS_Ln9.ne4_ne4.F2000-SCREAMv1-AQP1.mappy_gnu9.C.20220829_100951_99z6iy
DIFF SMS_D_Ln9.ne4_ne4.F2010-SCREAMv1-noAero.mappy_gnu9 (phase BASELINE)
Case dir: /ascldap/users/e3sm-jenkins/acme/scratch/SMS_D_Ln9.ne4_ne4.F2010-SCREAMv1-noAero.mappy_gnu9.C.20220829_100951_99z6iy
test-scheduler took 1023.6408159732819 seconds
```

**Comment by ambrad** [comment]
@bartgol never mind; I see the problem.

@tcclevenger you're applying Rayleigh friction at a place that is not reached if pg2 is used. You should move the call up.

**Comment by tcclevenger** [comment]
Ok, now the AT shows each CIME test having "DIFF" status, and on all machines the `restarted_vs_monolithic_check` test fails with relatively small diffs (~1e-7). Should be ready to merge.

**Comment by bartgol** [comment]
> Ok, now the AT shows each CIME test having "DIFF" status, and on all machines the `restarted_vs_monolithic_check` test fails with relatively small diffs (~1e-7). Should be ready to merge.

Hold on, why is it ok that restarted vs monolithic fails?

**Comment by bartgol** [comment]
> @bartgol It does a diff check on output and includes homme. I could disable Rayleigh friction for that test.

But it should still be bfb, no? It's just checking that restarts pass, there's no comparison against pre-built baselines.

**Comment by tcclevenger** [comment]
@bartgol I think is because when I moved rayliegh friction up in the postprocess call to happen during pg2 runs, it went above actual computation on T_mid. I'm testing this now.

**Comment by ambrad** [comment]
Also note e.g. `FAIL ERS_Ln9.ne4_ne4.F2000-SCREAMv1-AQP1.mappy_gnu9 (phase COMPARE_base_rest)`. So it looks like there is a restart issue.

**Comment by tcclevenger** [comment]
@ambrad yep, that is probably the same issue. see may latest commit and see what you think.

**Comment by ambrad** [comment]
Yes, that should do it. pg2 was restarting fine but np4 wasn't because it was missing the p_mid/int and T_mid updates.

At some point we should clean up that chunk of code following the pg2 return b/c it's redundant with update_pressure. The pg2 code calls update_pressure and so avoids that redundant code; hence the early return.

**Comment by tcclevenger** [comment]
Tested manually and everything looks good. For the CIME test you mentioned @ambrad, the only fail is in baseline cmp
```
FAIL ERS_Ln9.ne4_ne4.F2000-SCREAMv1-AQP1.mappy_gnu9 BASELINE master: DIFF
```
with diffs around ~1e-1 - 1e-6.

The restarted_vs_monolithic test also passed on mappy.

Best to let the AT run again to make sure nothing else is broken as a result of the last change.

**Comment by tcclevenger** [comment]
@ambrad @bartgol Now blake and weaver pass, mappy fails with all CIME tests showing DIFF (no FAIL).

**Review by ambrad — APPROVED** [review]

**Comment by ambrad** [comment]
@AaronDonahue pinging you to let you know this non-BFB PR is ready to be merged when it comes up in the non-BFB queue.

**Pull request merged**
