### PR TITLE
Fix a bug in PotentialTemperature diagnostic

### PR DESCRIPTION
**Pull request by bartgol**
More precisely:

* Fix bug related to pack sizes
* Simplified implementation of run method

### CODE REVIEW

**Review by AaronDonahue — APPROVED** [review]
@bartgol , thank you for this fix.  I have the same fix in #1612 based on your review comment , but that PR has been bumped down in priority for me.  It will be good to get this in sooner than later, and have a template to make sure all of the other diagnostics in 1612 are correct as well.

**Comment by AaronDonahue** [comment]
Looks like `weaver` just had some issues during the build, so setting to `RETEST`.  The one mappy fail is the known issue with ne30 aquaplanet and so this shouldn't be an issue because of this PR.

**Comment by bartgol** [comment]
I merged master so ne30 tests are no longer triggered for the AT.

**Review by AaronDonahue — DISMISSED** [review]
I'm assuming this one needs to go in before #1669 , I can't see why its failing the AT.  But I approve the changes.

**Comment by bartgol** [comment]
Ah, I messed up the CUDA fix. Counter-fix coming.

**Comment by bartgol** [comment]
Failures on mappy brought up some potential issues with the restart test. I'm going to fix it real quick in this PR, even though it's a conceptually separate issue.

**Comment by bartgol** [comment]
Ok, last commit seems to fix the rpointer race condition for the two model_restart tests.

**Comment by AaronDonahue** [comment]
Just want to note that PR #1612 incorporates the changes to `potential_temperature` that are also in this PR.

**Pull request closed without merging**
