### PR TITLE
Improve SHOC numerical stability in stable PBL (and bug fix)

### PR DESCRIPTION
**Pull request by bogensch**
This PR extends the usage of the stable boundary layer diffusivities by introducing a ramp function for the eddy coefficients for mild to moderately stable layers.  This prevents occasional crashes in ne30 runs that may manifest after several years when shoc_timestep = 150 s (default) due to excessively weak turbulence in these layers.  It also prevents frequent crashes at ne30 when shoc_timestep is lengthened to 300 s.  

The PR also fixes a bug where the minimum TKE threshold was checked at an inconsistent point.  Instead of checking the minimum TKE value near the end of the TKE routine calls, this is now checked when the TKE equation is advanced forward in time.

### CODE REVIEW

**Comment by PeterCaldwell** [comment]
@bogensch and @jeff-cohere - I notice that the diff for wqls_sec and shoc_ql2 are both inf and had denominators of 0 in shoc_run_and_cmp. One question I have is what the denominator means - I thought these diffs were absolute rather than relative errors? The other question I have is whether these infs and/or denominators are expected to be zero for the test case... Sorry if this isn't a very well-posed question.

**Comment by PeterCaldwell** [comment]
Another comment for @bogensch - have you checked whether this PR affects vertical convergence? Since you're mucking with thesholds it might. Though it seems like you're mostly making thesholds more rational so maybe not worth checking?

**Comment by jeff-cohere** [comment]
> @bogensch and @jeff-cohere - I notice that the diff for wqls_sec and shoc_ql2 are both inf and had denominators of 0 in shoc_run_and_cmp. One question I have is what the denominator means - I thought these diffs were absolute rather than relative errors? The other question I have is whether these infs and/or denominators are expected to be zero for the test case... Sorry if this isn't a very well-posed question.

Hey Peter--can you point me at a line number? I'm having trouble figuring out where the issue you're mentioning occurs.

**Comment by PeterCaldwell** [comment]
@jeff-cohere - not a line number. I see this in the Autotester output for the last set of tests. Expand the "Console Output; last 100 lines" for Blake, for example, then look at the end of the first chunk of lines ending with "Ref impl failed".

**Comment by jeff-cohere** [comment]
Gotcha. If you look in the `compare` function within `shoc_run_and_cmp.cpp`, you can see that the error condition depends on whether `num > tol*den`, where `num = |a - b|. This condition makes it a relative difference test, and the denominator is the reference solution value.

I don't know the answer to your second question, given that both `wqls_sec` and `shoc_ql2` are outputs, and I'm not familiar enough with the physical configuration of the test problem. The initial conditions for the test are defined in `components/scream/src/physics/shoc/shoc_ic_cases.cpp`, in the `make_standard` function  (starting at line 137 or so), in case that helps.

**Comment by PeterCaldwell** [comment]
Thanks @jeff-cohere , this is really helpful. So I guess denom=0 means the new impl is returning zero for these variables and num=inf means the old impl was returning inf. Or is it the other way around? Does b correspond to the old or new impl?

**Comment by jeff-cohere** [comment]
I believe `a` is the reference solution from the baseline file (the old solution). and `b` is the newly-obtained solution. See the call to `compare` around line 108 of `shoc_run_and_cmp.cpp` (and its call to the version of `compare` we're discussing on line 54). In relative difference tests, the denominator is usually the reference solution, whose behavior is better understood than the newer candidate solution.

**Comment by bogensch** [comment]
@PeterCaldwell yes I checked vertical convergence and it's fine.  Though with the caveat that all the cases I've hooked up to this test (BOMEX, DYCOMS-RF01, and GABLS) are steady state where the surface stability is pretty much locked in and not changing with time.

**Comment by PeterCaldwell** [comment]
I've now confirmed that the infs we were seeing in shoc_run_and_cmp were due to master happening to have zero values (basically no turbulence), causing relative error to become inf even though the new implementation had reasonable values. We expect shoc_run_and_cmp to fail b/c this is a non-bfb change. No other tests are failing, so I'm going to merge this now.

**Pull request merged**
