### PR TITLE
Fixes a bug in how the tendency for rimed ice mass is handled in P3.

### PR DESCRIPTION
**Pull request by AaronDonahue**
Addresses an issue where ERP tests are failing.

[NBFB]

### CODE REVIEW

**Comment by AaronDonahue** [comment]
@crterai here is the bugfix I found.  As you can see it's relatively simple so you may be able to add the fix to whatever branch you are on if you want to try it right away.

**Comment by AaronDonahue** [comment]
I'm not sure either.  My more comprehensive PR which I will put in after this one cleans up the terminology and the unused variables.  So hopefully we don't see any other bugs like this one.

**Comment by PeterCaldwell** [comment]
Sounds good. I like the idea of fixing the ixqirim terminology in your next, cleanup PR. Let's merge this one without waiting for AT since we know AT doesn't test the interface code you changed anyways.

**Comment by AaronDonahue** [comment]
Sounds good.  I'll merge it now.

**Comment by AaronDonahue** [comment]
@PeterCaldwell, in preparation for the next PR, I see that the official name for the constituents follows: 

```cnst_names(8) = (/'CLDLIQ', 'CLDICE','NUMLIQ','NUMICE', &
                      'RAINQM', 'CLDRIM','NUMRAI','BVRIM '/)```

Should we change these names to match the variables themselves?  I think the main purpose of the names is in the output, and given that we haven't set the output fields for SCREAM yet it should be fine to change them now.  I'm mostly thinking of the "CLDRIM" and "BVRIM" which should probably be "QIRIM" and "BIRIM".  The names for "rain" are consistent with MG2, so keep these as is?

**Comment by PeterCaldwell** [comment]
Yeah, I just checked and qirim and birim match what was used in the P3 papers. My recollection is that these are the variable names in the interior of P3 as well, right? I hate it when the same variable has different names in different parts of the code...

**Comment by AaronDonahue** [comment]
Yes, qirim and birim is consistent with what they are called inside P3.  So best to stick with those.  The next question is cldice vs qitot, cldliq vs qc, rain vs. qr, etc.  It may be splitting hairs, but while we are at it and cleaning up the interface it is worth asking now.  Also, considering that we plan to port the interface to C++ soon it would be good to get this sorted out now to save some pain down the road.

**Comment by PeterCaldwell** [comment]
My personal feeling is that qc, qi, qr, ni, nr, etc are better better because they are more compact and in particular they are more precise: the q in qc always means water *mass* and i always means cloud liquid. By contrast, cldliq doesn't follow any clear pattern and therefore isn't clear whether it means mass, number, or what.

**Comment by AaronDonahue** [comment]
I agree.  It also simplifies debugging when you don't have to translate variable names between two different modules.  I can make the adjustment in my upcoming interface PR.

**Comment by PeterCaldwell** [comment]
Skipped AT because change is just in p3_interface, which AT doesn't check.

**Pull request merged**
