### PR TITLE
[WIP] Add a user-specific test with double the memleak tolerance

### PR DESCRIPTION
**Pull request by AaronDonahue**
This PR adds the test `double_memleak_tol` to the suite of user specified tests in CAM.  The new test has double the tolerance for reporting a MEMLEAK fail, 20% instead of 10%.  

This PR also changes the ERP nightly tests run for SCREAM to use the double memleak tolerance for ERP.

[BFB]

### CODE REVIEW

**Comment by AaronDonahue** [comment]
I'm not sure why the Autotester keeps failing on this PR.  Looking at the errors there is nothing in this PR that should impact the C++ unit tests that appear to be failing.

**Comment by AaronDonahue** [comment]
Addiing WIP, not sure this is working as expected.

**Comment by PeterCaldwell** [comment]
Uh oh. If you gather-all-data on master (without making any changes at all), does that fail? Or maybe instead just comment out the 3 lines you change in this PR and try again. 

Are you using an old version of master? A week ago we had a problem where shoc_run_and_cmp would always fail (but not p3_run_and_cmp). This is baffling.

**Comment by AaronDonahue** [comment]
ahhhh you know.  That is probably it, I'll resubmit with a new version of master.

**Comment by AaronDonahue** [comment]
ok, that should work now.  At least it tested fine for the sp testing suite on quartz, which was failing before.

**Comment by AaronDonahue** [comment]
Deleting this now, it was handled in PR #399

**Pull request closed without merging**
