### PR TITLE
aarondonahue/simple_io

### PR DESCRIPTION
**Pull request by AaronDonahue**
This PR brings in a "simple IO" interface, providing a means to write and read netCDF files through scream.

As a demonstration of the new interface the "p3_run_and_cmp" test has been changed to use netCDF for writing baselines and for later comparison against the baseline.  The files produced are also able to be compared using `cprnc`, however, automatic use of `cprnc` has not been integrated in this PR.

A major change that this PR will have for building scream is the need to link to netCDF-C to have access to the netcdf library.  This will require adding directives to the cmake build.

For an example of what needed to be added on the LC machine quartz:
```
NCDIR= Path-To-netCDF
PKG_CONFIG_PATH=${NCDIR}/lib/pkgconfig:$PKG_CONFIG_PATH
export PKG_CONFIG_PATH
NCFLGS=`pkg-config --cflags --libs netcdf`
...
cmake 
....
     -D CMAKE_C_FLAGS:STRING="-w ${NCFLGS}"                        \
     -D CMAKE_Fortran_FLAGS:STRING="-w ${NCFLGS}"              \
...
```

To the best of my knowledge netCDF-C should be available on all platforms that we run and test scream.

### CODE REVIEW

**Comment by AaronDonahue** [comment]
@jgfouca , I'm expecting this PR to not even build because of the dependency on netCDF.  I'm assuming netCDF is available on all of our testing platforms but we will have to update the cmake directives for each one to accommodate that dependency.

**Comment by jgfouca** [comment]
I should mention, we already have several instances of FindNetCDF.cmake in E3SM.

**Comment by AaronDonahue** [comment]
oops on the submodules.  Do I just need to issue a `git submodule sync` and `git submodule update` and push the branch?  Or shoudl I kill this PR and clean that all up and resubmit?

**Comment by AaronDonahue** [comment]
As for netCDF dependency.  Yes, if there is a way to have the netcdf automatically found I agree that would be best.  Is that difficult to set up?

**Comment by jgfouca** [comment]
@AaronDonahue , you should be able to set the submodules back to their original versions via:
```
git checkout origin/master $path_to_submodule
```

**Comment by jgfouca** [comment]
@AaronDonahue , I think setting-up findnetcdf should be pretty easy.

**Pull request closed without merging**
